-- =============================================================================
-- AviatorTutor — Phase 8: ATA 28 Fuel — 36 flashcards.
-- =============================================================================

SET @system_id := (SELECT id FROM systems WHERE slug = 'fuel' LIMIT 1);
SELECT @system_id AS resolved_system_id;

DELETE FROM flashcards WHERE system_id = @system_id;

INSERT INTO flashcards (system_id, front, back, hint, difficulty, tags) VALUES
(@system_id, 'How many fuel tanks does the Q400 have, and what does each feed?',
 'TWO integral wing tanks. No.1 (LEFT) feeds left engine + APU. No.2 (RIGHT) feeds right engine. NO engine crossfeed.', NULL, 'easy', JSON_ARRAY('fuel','tanks','architecture')),
(@system_id, 'Does the Q400 have engine crossfeed?',
 'NO. There is no engine crossfeed plumbing on the Q400. The only way to share or balance fuel between sides is tank-to-tank transfer through the central transfer plumbing.',
 'Mnemonic: NO-CROSSFEED-TANK-TO-TANK.', 'medium', JSON_ARRAY('fuel','crossfeed','quirk')),
(@system_id, 'Name the three bays inside each Q400 wing tank.',
 'SURGE bay (outboard, vent + fuel recovery), MAIN tank (bulk storage), COLLECTOR bay (inboard/aft, engine feed at any attitude).',
 'Mnemonic: 3-BAY-TANK.', 'medium', JSON_ARRAY('fuel','bays','tank')),
(@system_id, 'What is the total usable fuel quantity?',
 '5,318 kg total usable fuel.',
 'Mnemonic: 5318-USABLE.', 'medium', JSON_ARRAY('fuel','quantity','usable')),
(@system_id, 'What is the maximum lateral fuel imbalance?',
 '272 kg. Above this the FQC flashes a yellow [BALANCE] message just above the FUEL legend on the ED, and both analog quantity dials turn solid yellow.',
 'Mnemonic: 272-IMBALANCE.', 'hard', JSON_ARRAY('fuel','imbalance','balance')),
(@system_id, 'What three conditions must all be true for the #1 or #2 TANK FUEL LOW caution to illuminate?',
 '(1) Park brake OFF. (2) Related collector bay drops below approximately 150 kg. (3) Related engine running. ALL THREE required.',
 'Mnemonic: 150-COLLECTOR-LOW.', 'hard', JSON_ARRAY('fuel','low','caution')),
(@system_id, 'What type of pump is the auxiliary fuel pump in each collector bay?',
 'AC variable-frequency. One per collector bay.',
 'Mnemonic: AUX-AC-VF-COLLECTOR.', 'medium', JSON_ARRAY('fuel','pumps','aux')),
(@system_id, 'When are the auxiliary fuel pumps required to be ON?',
 'For TAKEOFF and LANDING — backup boost behind the primary ejector pump during high-thrust regimes.', NULL, 'medium', JSON_ARRAY('fuel','pumps','takeoff')),
(@system_id, 'What happens to the donor tank''s aux pump during fuel transfer?',
 'It activates AUTOMATICALLY. The ON segment of its switchlight turns green even though no one pushed it. Read this as a normal indication during transfer.',
 'Mnemonic: AUTO-AUX-DURING-TRANSFER.', 'hard', JSON_ARRAY('fuel','transfer','aux')),
(@system_id, 'What is the path of fuel from collector bay to the engine?',
 'Collector bay → primary ejector pump (or AC aux pump) → engine driven pump → FOHE → FMU.', NULL, 'medium', JSON_ARRAY('fuel','feed','path')),
(@system_id, 'What does FOHE stand for and what does it do?',
 'Fuel Oil Heat Exchanger. It both FILTERS and HEATS the fuel before it enters the FMU. Heating prevents ice crystal formation; filtering removes particulates.',
 'Mnemonic: FOHE-HEATS-FILTERS.', 'medium', JSON_ARRAY('fuel','fohe')),
(@system_id, 'What does the #1 or #2 FUEL FLTR BYPASS caution indicate?',
 'The fuel filter is clogging and bypass is impending. Fuel is being routed around the filter automatically. Continue but flag for maintenance.', NULL, 'medium', JSON_ARRAY('fuel','filter','bypass')),
(@system_id, 'What does the #1 or #2 ENG FUEL PRESS caution indicate, and what is the first action?',
 'Engine driven pump inlet pressure has dropped below preset limit. First action: select the AUX PUMP ON for that side. AC variable-frequency aux pump restores boost; caution typically clears.', NULL, 'medium', JSON_ARRAY('fuel','press','caution')),
(@system_id, 'What is the maximum altitude limitation when using JET B / JP-4 fuel with TANK temperature above 35°C?',
 'Maximum altitude FL200 (20,000 ft).',
 'Mnemonic: JP4-35-FL200.', 'hard', JSON_ARRAY('fuel','jet-b','jp-4','altitude')),
(@system_id, 'What power source is required for pressure refueling?',
 'DC POWER. Loss of DC during refuel halts the operation.',
 'Mnemonic: DC-FOR-REFUEL.', 'medium', JSON_ARRAY('fuel','refuel','dc')),
(@system_id, 'Where is the single-point pressure refuel/defuel access located?',
 'On the rear underside of the No.2 nacelle (right side). Flush access door.', NULL, 'medium', JSON_ARRAY('fuel','refuel','location')),
(@system_id, 'What does the FUELING ON caution indicate, and what does it inhibit?',
 'The refuel/defuel access door is OPEN (or sensor fault). It INHIBITS tank-to-tank fuel transfer entirely while illuminated.',
 'Mnemonic: FUELING-ON-INHIBITS-TRANSFER.', 'hard', JSON_ARRAY('fuel','fueling-on','inhibit')),
(@system_id, 'What two pressure-refuel modes does the Q400 offer?',
 'PRESELECT REFUEL (auto stop at preset KG via INCR/DECR toggle) and REFUEL (manual via PRECHECK/OPEN/CLOSE switches).', NULL, 'medium', JSON_ARRAY('fuel','refuel','modes')),
(@system_id, 'How does gravity refueling work on the Q400?',
 'Through wing-mounted gravity refuel adapters on top of each wing. No DC required, slower flow. Backup when pressure refuel is unavailable.', NULL, 'medium', JSON_ARRAY('fuel','refuel','gravity')),
(@system_id, 'What is the function of the surge bay?',
 'Tank venting (through 2 outboard float vent valves + 1 inboard vent line + 2 NACA vents on the underside of each wing) AND fuel recovery (any spill is sucked back into the main tank by the partial vacuum as fuel is consumed).', NULL, 'hard', JSON_ARRAY('fuel','surge-bay','venting')),
(@system_id, 'What do scavenge ejector pumps do?',
 'Continuously draw fuel from the tank low points back to the COLLECTOR bay so that pitch/roll attitudes never starve the engine. Driven by high-pressure motive flow.', NULL, 'hard', JSON_ARRAY('fuel','scavenge','ejector')),
(@system_id, 'What happens on the MFD fuel page when there is an imbalance?',
 'The analog pointer on BOTH tank dials changes from WHITE to YELLOW. The [BALANCE] message flashes yellow above the FUEL legend on the Engine Display.',
 'Mnemonic: YELLOW-IMBALANCE.', 'medium', JSON_ARRAY('fuel','imbalance','indication')),
(@system_id, 'What does the aux pump pressure-status circle on the MFD indicate, and what colour means what?',
 'Indicates aux pump output pressure. WHITE-fill circle = LOW or NO pressure. GREEN-fill circle = NORMAL pressure.', NULL, 'medium', JSON_ARRAY('fuel','aux','pressure')),
(@system_id, 'How does the FUEL TRANSFER switch work?',
 'Three positions: TO TANK 1 / CENTER / TO TANK 2. Lever-latched. Selecting toward a receiver tank automatically activates the donor tank''s aux pump and opens the transfer shutoff valves.', NULL, 'medium', JSON_ARRAY('fuel','transfer','switch')),
(@system_id, 'How does fuel transfer stop?',
 '(1) Crew deselects the FUEL TRANSFER switch to CENTER. (2) Receiver tank''s high-level sensor detects an overfill condition and automatically halts transfer.', NULL, 'medium', JSON_ARRAY('fuel','transfer','stop')),
(@system_id, 'How is the engine fuel feed shutoff valve commanded closed?',
 'By PULLING the corresponding PULL FUEL/HYD OFF T-handle on the Fire Protection Panel. This is the same handle that arms the fire extinguisher bottles.', NULL, 'medium', JSON_ARRAY('fuel','shutoff','t-handle')),
(@system_id, 'What is the digital display range for total fuel quantity?',
 '0 to 15,000 KG, displayed in 5-KG increments. White dashes if data invalid.', NULL, 'medium', JSON_ARRAY('fuel','indication','digital')),
(@system_id, 'What is the tank temperature display range?',
 '-99 to +99°C, displayed in 1° increments with a sign. White ± sign and digits, blue °C unit.', NULL, 'hard', JSON_ARRAY('fuel','temperature','indication')),
(@system_id, 'How many NACA vents are there per surge bay, and where?',
 'TWO NACA vents per surge bay, located on the BOTTOM of each wing. Tank pressure controlled through these vents via integral standpipes.', NULL, 'hard', JSON_ARRAY('fuel','venting','naca')),
(@system_id, 'What is the function of the magnetic dipsticks?',
 'Ground quantity check on the underside of each wing. A float inside the tank contains a magnet; the dipstick magnet attaches to it at the fuel level, holding the dipstick at the correct depth for reading.', NULL, 'hard', JSON_ARRAY('fuel','dipstick','ground')),
(@system_id, 'What is the role of the flapper check valves at the base of the collector bay?',
 'Ensure GRAVITY fuel flow into the collector bay if the scavenge ejector flow is not sufficient. Backup to the active scavenging.', NULL, 'hard', JSON_ARRAY('fuel','flapper','collector')),
(@system_id, 'What is the FQC and what does it do?',
 'Fuel Quantity Computer. It drives the MFD fuel page indications and continuously monitors lateral imbalance. Triggers the [BALANCE] message above 272 kg.', NULL, 'medium', JSON_ARRAY('fuel','fqc')),
(@system_id, 'During pressure refuel, what is the role of the vent/dump valve?',
 'Opens during refuel to vent air from the tank as fuel fills it. Prevents tank damage from overfill — if both normal and backup shutoffs fail, fuel spills via surge bay → standpipe → NACA vent overboard rather than rupturing the tank.', NULL, 'hard', JSON_ARRAY('fuel','refuel','vent')),
(@system_id, 'TRUE or FALSE — fuel transfer can be initiated while the FUELING ON caution is illuminated.',
 'FALSE. Fuel transfer is INHIBITED while FUELING ON is illuminated (refuel/defuel door open or sensor fault).', NULL, 'medium', JSON_ARRAY('fuel','transfer','inhibit')),
(@system_id, 'TRUE or FALSE — on a fuel leak, the captain should immediately initiate transfer toward the lighter tank to balance.',
 'FALSE. NEVER transfer into a leaking tank — you just waste fuel into the leak. Identify burn rate vs quantity math first; run QRH FUEL LEAK; secure affected engine if directed; divert.', NULL, 'hard', JSON_ARRAY('fuel','leak','procedure')),
(@system_id, 'How many FUEL system pushbuttons appear on the ESCP, and what does pressing FUEL SYS do?',
 'One FUEL SYS pushbutton on the ESCP. Press: shows the fuel page on the MFD set to SYS. Press-and-hold (with both MFDs not at SYS): shows the fuel page on the Engine Display until released.', NULL, 'medium', JSON_ARRAY('fuel','escp','mfd'));

SELECT COUNT(*) AS flashcards_inserted FROM flashcards WHERE system_id = @system_id;
