-- =============================================================================
-- AviatorTutor — Phase 14: ATA 35 Oxygen — 36 flashcards.
-- =============================================================================

SET @system_id := (SELECT id FROM systems WHERE slug = 'oxygen' LIMIT 1);
SELECT @system_id AS resolved_system_id;

DELETE FROM flashcards WHERE system_id = @system_id;

INSERT INTO flashcards (system_id, front, back, hint, difficulty, tags) VALUES
(@system_id, 'How many crew oxygen masks are on the Q400, and how are they supplied?',
 'THREE full-face microphone-equipped masks (pilot, copilot, observer) supplied from a SINGLE common cylinder.',
 'Mnemonic: 3-MASKS-1-CYLINDER.', 'easy', JSON_ARRAY('oxygen','masks','cylinder')),
(@system_id, 'Where is the crew oxygen cylinder located?',
 'In the right LOWER nose compartment.',
 'Mnemonic: RIGHT-NOSE-CYLINDER.', 'medium', JSON_ARRAY('oxygen','cylinder','location')),
(@system_id, 'Where is the green burst disc, and what does it do?',
 'On the right exterior of the nose. Ejects to relieve cylinder over-pressurisation. A missing or damaged burst disc = cylinder over-pressure event has occurred.',
 'Mnemonic: GREEN-BURST-RIGHT.', 'hard', JSON_ARRAY('oxygen','burst-disc')),
(@system_id, 'Where is the flight-deck oxygen pressure gauge located?',
 'On the COPILOT side console. Lighted display.',
 'Mnemonic: COPILOT-CONSOLE-GAUGE.', 'medium', JSON_ARRAY('oxygen','gauge')),
(@system_id, 'When the cylinder is turned OFF, what happens to mask pressure and gauge reading?',
 'Mask pressure automatically reduces to ATMOSPHERIC. The flight-deck gauge continues to show BOTTLE pressure (cylinder gauge reading is independent of supply state).',
 'Mnemonic: OFF-ATMO-GAUGE-BOTTLE.', 'hard', JSON_ARRAY('oxygen','cylinder','off')),
(@system_id, 'What capacity does the crew oxygen system have?',
 'Supplemental oxygen for a descent to 14,000 ft in 4 minutes AND flight at 14,000 ft for 116 minutes.',
 'Mnemonic: 14000-IN-4-LEVEL-116.', 'hard', JSON_ARRAY('oxygen','capacity')),
(@system_id, 'What is the crew oxygen mask donning time target?',
 'Less than 5 SECONDS. Via inflatable harness on each mask.',
 'Mnemonic: 5-SEC-DON.', 'medium', JSON_ARRAY('oxygen','mask','donning')),
(@system_id, 'How does the inflatable harness on the mask work?',
 'Press the red harness inflation button (momentary action). The harness inflates with O2 pressure to fit over the head. Release the button: harness deflates and compresses, securing the mask.', NULL, 'medium', JSON_ARRAY('oxygen','harness','red-button')),
(@system_id, 'What three positions does the mask regulator have?',
 'NORM (auto air/oxygen mixture varying with cabin altitude). 100% (100% oxygen regardless of cabin altitude). EMER (100% O2 at slight POSITIVE pressure, also purges smoke goggles).',
 'Mnemonic: NORM-100-EMER.', 'hard', JSON_ARRAY('oxygen','regulator')),
(@system_id, 'What is the caution about EMER position on the regulator?',
 'Keeping the regulator in EMER position will DEPLETE the oxygen system. Use EMER for actual smoke/fire events; return to NORM or 100% as soon as the situation is contained.',
 'Mnemonic: EMER-DEPLETES.', 'hard', JSON_ARRAY('oxygen','emer','caution')),
(@system_id, 'In addition to 100% positive pressure, what other function does EMER mode perform?',
 'Purges smoke from the smoke goggles. The positive pressure flushes contaminants out around the goggle seal.', NULL, 'hard', JSON_ARRAY('oxygen','emer','goggles')),
(@system_id, 'What is the in-line pressure indicator, and what colours does it show?',
 'On the mask supply hose. GREEN with correct pressure. RED if oxygen pressure is low. If donning gives breathing difficulty or red indicator, verify supply hose connection.', NULL, 'medium', JSON_ARRAY('oxygen','in-line','indicator')),
(@system_id, 'How is the observer mask supplied?',
 'It plugs into the DUAL outlet on the copilot oxygen supply line. Mask is kept adjacent to the copilot mask in stowage cups behind the seats.',
 'Mnemonic: OBSERVER-DUAL-COPILOT.', 'hard', JSON_ARRAY('oxygen','observer','dual-outlet')),
(@system_id, 'TRUE or FALSE — Crew oxygen mask outlets are dedicated and the masks cannot be plugged into different outlets.',
 'FALSE. Outlets are CROSS-COMPATIBLE. If an outlet fails, the mask can be plugged into another working outlet. If a mask itself fails, the observer mask may be used by either crew member.', NULL, 'medium', JSON_ARRAY('oxygen','outlet','crosscompat')),
(@system_id, 'What is the role of the microphone on the crew mask?',
 'Each mask has a microphone with an audio connector — preserves crew communication when masks are in use. Plug the audio connector into the related receptacle.', NULL, 'medium', JSON_ARRAY('oxygen','mask','mic')),
(@system_id, 'What are the safety rules around smoking and oxygen?',
 'Smoking is NOT permitted when oxygen is in use. Pure O2 + ignition source is a serious fire risk.',
 'Mnemonic: NO-SMOKE-O2.', 'easy', JSON_ARRAY('oxygen','safety','smoking')),
(@system_id, 'What additional oxygen systems are on the Q400 beyond the fixed crew system?',
 '(1) Portable passenger O2 cylinders kept in the cabin. (2) Protective Breathing Equipment (PBE) for both flight deck crew and cabin attendants. (3) First aid O2 in the passenger compartment.',
 'Mnemonic: PBE-FLT-CABIN.', 'medium', JSON_ARRAY('oxygen','portable','pbe')),
(@system_id, 'What is PBE used for?',
 'Protective Breathing Equipment. Self-contained smoke-hood-style units. Used in low-oxygen environments such as cabin fire or smoke evacuation. Available for both flight deck crew and cabin attendants.', NULL, 'medium', JSON_ARRAY('oxygen','pbe')),
(@system_id, 'What is the correct first action on a rapid depressurisation in cruise?',
 'Oxygen masks ON immediately. Don in less than 5 seconds via inflatable harness. Regulator to NORM or 100%. Then begin emergency descent and crew comm.', NULL, 'hard', JSON_ARRAY('oxygen','depressurisation','procedure')),
(@system_id, 'What is the correct first action on cockpit smoke?',
 'Oxygen masks ON. Regulator to EMER position (100% O2 positive pressure, purges smoke goggles). Smoke goggles on. Run SMOKE/FUMES QRH non-normal.', NULL, 'hard', JSON_ARRAY('oxygen','smoke','procedure')),
(@system_id, 'What in-line indicator state demands hose connection check?',
 'RED. If the in-line pressure indicator on the supply hose is RED, verify the supply hose is connected at both the mask and the outlet. The most common cause of post-don breathing difficulty is a disconnected hose.', NULL, 'medium', JSON_ARRAY('oxygen','red-indicator')),
(@system_id, 'TRUE or FALSE — A pre-flight walk-around check should include the burst disc.',
 'TRUE. The green burst disc on the right exterior of the nose is a pre-flight item — its absence or visible compromise indicates a cylinder over-pressurisation event has occurred. Maintenance write-up; do not dispatch.', NULL, 'medium', JSON_ARRAY('oxygen','burst-disc','pre-flight')),
(@system_id, 'How many minutes of supplemental oxygen does the system supply at 14,000 ft level flight?',
 '116 minutes. After a 4-minute emergency descent from cruise to 14,000 ft.', NULL, 'hard', JSON_ARRAY('oxygen','capacity','116-minutes')),
(@system_id, 'What does the cylinder ON-OFF knob do, and what is the gauge behaviour with it OFF?',
 'On the cylinder. Closes/opens the cylinder valve. With OFF, available mask pressure drops to atmospheric. The flight-deck gauge continues to show BOTTLE pressure regardless of valve position.', NULL, 'hard', JSON_ARRAY('oxygen','cylinder','knob')),
(@system_id, 'TRUE or FALSE — The crew oxygen system has multiple cylinders for redundancy.',
 'FALSE. Single common cylinder for the 3 crew masks. Loss of cylinder = no fixed crew oxygen.', NULL, 'medium', JSON_ARRAY('oxygen','cylinder','redundancy')),
(@system_id, 'What is the minimum cylinder pressure for normal dispatch?',
 'Per company OM/MEL — typically a charge level above which the system will provide rated capacity. Pre-flight check verifies this is met.', NULL, 'medium', JSON_ARRAY('oxygen','cylinder','minimum')),
(@system_id, 'In NORM mode, what does the regulator do?',
 'Automatically supplies an air/oxygen MIXTURE that varies with cabin altitude. At low cabin altitudes the mix is mostly ambient air; at higher cabin altitudes the O2 fraction increases.', NULL, 'medium', JSON_ARRAY('oxygen','norm','regulator')),
(@system_id, 'In 100% mode, what does the regulator do?',
 'Supplies 100% oxygen regardless of cabin altitude. Used when air contamination is a concern but no positive pressure is needed.', NULL, 'medium', JSON_ARRAY('oxygen','100','regulator')),
(@system_id, 'What is the difference between 100% mode and EMER mode?',
 '100% supplies pure O2 at ambient pressure (no positive pressure). EMER supplies pure O2 at slight POSITIVE pressure — flushes contaminants out around the mask seal AND purges smoke goggles. EMER also depletes the cylinder faster.', NULL, 'hard', JSON_ARRAY('oxygen','100-vs-emer')),
(@system_id, 'TRUE or FALSE — On a single mask failure, the observer mask can be used by either crew member.',
 'TRUE. The observer mask is designed for cross-crew use in this scenario. Plug it into a working outlet.', NULL, 'medium', JSON_ARRAY('oxygen','mask-failure','observer')),
(@system_id, 'What gas pressure inflates the harness?',
 'OXYGEN PRESSURE from the supply line. The red button opens a valve that admits O2 to the harness inflation tubes.', NULL, 'hard', JSON_ARRAY('oxygen','harness','inflation')),
(@system_id, 'When should EMER mode be used and when should you exit it?',
 'Use EMER for cabin smoke / fire events to flush smoke around mask seal and purge smoke goggles. Exit to NORM or 100% as soon as the smoke event is contained — EMER depletes the cylinder fast.', NULL, 'hard', JSON_ARRAY('oxygen','emer','use')),
(@system_id, 'TRUE or FALSE — Smoking is permitted with the regulator in NORM mode but not EMER.',
 'FALSE. Smoking is NOT PERMITTED when oxygen is in use, in any regulator mode. Pure O2 + ignition source is a fire risk.', NULL, 'easy', JSON_ARRAY('oxygen','smoking')),
(@system_id, 'What three pressure indications are associated with the crew O2 system?',
 '(1) Cylinder pressure gauge on the cylinder. (2) Lighted flight-deck pressure gauge on the COPILOT side console. (3) In-line pressure indicator on the mask supply hose (GREEN good / RED low).', NULL, 'hard', JSON_ARRAY('oxygen','indicators')),
(@system_id, 'What is the location of first aid oxygen on the Q400?',
 'In the passenger compartment. For medical use during normal flight (passenger illness, dizziness). Cabin attendants administer per their training.', NULL, 'medium', JSON_ARRAY('oxygen','first-aid')),
(@system_id, 'Where are the crew masks stowed on the flight deck?',
 'In stowage cups on the bulkhead behind the pilot and copilot seats. The observer mask is adjacent to the copilot mask, plugged into the dual outlet on the copilot oxygen supply line.', NULL, 'medium', JSON_ARRAY('oxygen','stowage'));

SELECT COUNT(*) AS flashcards_inserted FROM flashcards WHERE system_id = @system_id;
