-- =============================================================================
-- AviatorTutor — Phase 15: ATA 36 Pneumatics — 36 flashcards.
-- =============================================================================

SET @system_id := (SELECT id FROM systems WHERE slug = 'pneumatics' LIMIT 1);
SELECT @system_id AS resolved_system_id;

DELETE FROM flashcards WHERE system_id = @system_id;

INSERT INTO flashcards (system_id, front, back, hint, difficulty, tags) VALUES
(@system_id, 'Can the Q400 APU be operated in flight?',
 'NO. The APU CANNOT operate in flight. The shutoff valve closes automatically as soon as the aircraft becomes airborne. APU is a ground-only asset.',
 'Mnemonic: APU-GROUND-ONLY.', 'easy', JSON_ARRAY('apu','ground-only')),
(@system_id, 'What does the APU consist of, and what does it supply?',
 'A gas turbine engine driving a 28 VDC starter-generator. Supplies bleed air for the ECS AND 28 VDC to the electrical system.', NULL, 'medium', JSON_ARRAY('apu','overview')),
(@system_id, 'What replaces the standard composite tailcone for the APU?',
 'A TITANIUM tailcone with a firewall. Required for the APU fire-rating.',
 'Mnemonic: TITANIUM-TAIL-2-CLAMSHELL.', 'medium', JSON_ARRAY('apu','tailcone')),
(@system_id, 'How is the APU accessed for maintenance?',
 'Two clamshell-type doors on the BOTTOM of the tailcone.', NULL, 'medium', JSON_ARRAY('apu','access')),
(@system_id, 'Where is the APU air intake located?',
 'Screened inlet duct on the RIGHT REAR of the fuselage. An optional louvered cover protects against snow/sleet ingress.',
 'Mnemonic: RIGHT-REAR-INLET.', 'medium', JSON_ARRAY('apu','inlet')),
(@system_id, 'What controls APU start, normal operation, and malfunction monitoring?',
 'The APU FADEC (Full Authority Digital Engine Control). Auto-managed; crew interface is via switchlights on the APU control panel.', NULL, 'medium', JSON_ARRAY('apu','fadec')),
(@system_id, 'When does the APU starter disengage during start?',
 'When the APU reaches HALF its operating speed. The starter is engaged for the first half of the speed range, then disengages.',
 'Mnemonic: HALF-SPEED-STARTER.', 'hard', JSON_ARRAY('apu','starter')),
(@system_id, 'What three conditions must all be true for the APU PWR switchlight to arm?',
 '(1) Aircraft is on the GROUND. (2) NO FIRE detected. (3) EXTG switch is NOT selected.',
 'Mnemonic: 3-COND-PWR-ARM.', 'hard', JSON_ARRAY('apu','pwr','arming')),
(@system_id, 'What four conditions cause the APU fuel shutoff valve to close?',
 '(1) PWR switchlight pushed off (normal shutdown). (2) FIRE detected in tailcone. (3) EXTG switchlight pushed. (4) Aircraft in flight.',
 'Mnemonic: 4-COND-FUEL-CLOSE.', 'hard', JSON_ARRAY('apu','fuel','close')),
(@system_id, 'Where does the APU fuel come from?',
 'From the LEFT wing collector bay through the APU shutoff valve. Rigid fuel line outside the pressurised fuselage; gravity-fed APU-driven fuel pump.',
 'Mnemonic: LEFT-COLLECTOR-APU-FUEL.', 'medium', JSON_ARRAY('apu','fuel','source')),
(@system_id, 'What is the bus voltage drop during a battery-only APU start at 100% charge?',
 'Bus voltage drops to about 20 VDC. (Value varies with temperature.)',
 'Mnemonic: 100-20-50-18.', 'hard', JSON_ARRAY('apu','battery','start')),
(@system_id, 'What is the bus voltage drop during a battery-only APU start at 50% charge?',
 'Bus voltage drops to about 18 VDC. Insufficient battery charge can lead to system problems and start failure.', NULL, 'hard', JSON_ARRAY('apu','battery','low')),
(@system_id, 'What batteries are used for APU starting when no external DC is available?',
 'The 2×40 Ahr NiCad batteries (the same MAIN + AUX of the EPGDS — Phase 5 Electrical).', NULL, 'medium', JSON_ARRAY('apu','battery','source')),
(@system_id, 'What happens to APU GEN output if external AC or DC power is applied?',
 'APU GEN output is automatically PREVENTED. The system protects against parallel feeds.', NULL, 'hard', JSON_ARRAY('apu','gen','external-power')),
(@system_id, 'When and how does the APU bleed air valve open?',
 'When the APU is operating, push the BL AIR switchlight on the APU control panel. OPEN segment (green) illuminates. APU bleed supplies the ECS AND holds the CPCS aft safety valve open.', NULL, 'medium', JSON_ARRAY('apu','bleed','valve')),
(@system_id, 'What happens to the APU BL AIR if either main engine BLEED switch is at 1 or 2?',
 'The APU BL AIR switchlight is automatically DE-ENERGIZED. Prevents simultaneous APU + engine bleed supply.',
 'Mnemonic: BL-AIR-AUTO-OFF-WITH-ENG.', 'hard', JSON_ARRAY('apu','bleed','auto-off')),
(@system_id, 'What happens to APU bleed air supply if APU EGT reaches an established temperature limit?',
 'Bleed air supply is REDUCED. The system gives APU generator load priority over bleed air.',
 'Mnemonic: EGT-LIMIT-BLEED-DOWN.', 'hard', JSON_ARRAY('apu','bleed','egt')),
(@system_id, 'How does the APU fire detection system work?',
 'A loop sensor along the tailcone above the APU senses fire/overheat. Continuous monitoring whenever the right ESS 28 VDC bus is energized. On fire: FIRE light (red) on FPP, MASTER WARNING + CHECK FIRE DET flash, BTL ARM amber, fuel valve auto-closes.', NULL, 'hard', JSON_ARRAY('apu','fire','detection')),
(@system_id, 'How long after FIRE detection does the APU extinguishing agent automatically release?',
 '7 SECONDS. After 7 seconds the agent auto-releases and BTL ARM goes out.',
 'Mnemonic: 7-SEC-AUTO-EXTG.', 'hard', JSON_ARRAY('apu','fire','7-sec')),
(@system_id, 'What if automatic fire-extinguisher release fails (BTL ARM stays on)?',
 'Push the guarded EXTG switchlight on the FPP to manually discharge the bottle.', NULL, 'medium', JSON_ARRAY('apu','fire','manual-extg')),
(@system_id, 'After the APU fire bottle has discharged, can the APU be restarted?',
 'NO. Once the bottle has been discharged, APU restart is PREVENTED until the bottle is REPLACED. Plan around no APU until maintenance services the bottle.',
 'Mnemonic: NO-RESTART-AFTER-DISCHARGE.', 'hard', JSON_ARRAY('apu','fire','no-restart')),
(@system_id, 'What does GEN OHT (amber advisory) indicate?',
 'APU starter-generator overheat. The APU automatically shuts down when GEN OHT illuminates.', NULL, 'medium', JSON_ARRAY('apu','gen','overheat')),
(@system_id, 'What APU faults does the FADEC monitor?',
 'Overspeed, underspeed, start failure, accelerate failure, EGT overtemperature, low oil pressure, high oil temperature, failed sensors, failed valves/relays/circuits, internal failure.', NULL, 'hard', JSON_ARRAY('apu','fadec','faults')),
(@system_id, 'On any APU fault detected, what happens?',
 'APU automatically shuts down. FAIL segment of PWR switchlight illuminates amber. FUEL VALVE CLOSED white. APU caution amber. PWR must be RESELECTED after auto shutdown.', NULL, 'medium', JSON_ARRAY('apu','fault','shutdown')),
(@system_id, 'What is the normal APU shutdown sequence?',
 '(1) Close BL AIR (BL AIR switchlight push, OPEN out). (2) GEN off (GEN switchlight push, ON out). (3) Push PWR — fuel valve closes, APU stops. Order matters: BL AIR first to stabilise EGT, GEN second to manage load, PWR last to stop.', NULL, 'medium', JSON_ARRAY('apu','shutdown','sequence')),
(@system_id, 'What is the ambient temperature limitation with the composite cooling duct removed?',
 '30°C OR ISA+25°C, whichever is LOWER.',
 'Mnemonic: LOUVRE-21-DUCT-30.', 'hard', JSON_ARRAY('apu','limitation','temperature')),
(@system_id, 'What is the ambient temperature limitation with the Air Inlet Louvre installed?',
 '21°C ambient temperature.', NULL, 'hard', JSON_ARRAY('apu','limitation','louvre')),
(@system_id, 'How does the APU GEN behave once main engine DC GENs are on line?',
 'APU GEN continues to supply power in PARALLEL to the DC buses, until manually selected off (GEN switchlight push to ON out) or until normal shutdown.', NULL, 'medium', JSON_ARRAY('apu','gen','parallel')),
(@system_id, 'What advisory lights are on the APU Fire Protection Panel for the fuel valve?',
 'FUEL SHUT-OFF VALVE OPEN (green) when valve is open. FUEL SHUT-OFF VALVE CLOSED (white) when valve is closed.', NULL, 'medium', JSON_ARRAY('apu','fpp','fuel-valve')),
(@system_id, 'TRUE or FALSE — APU bleed air is used for airframe de-icing.',
 'FALSE. APU check valve and wing duct check valves PREVENT APU bleed air from entering the engine bleed supply, which includes airframe de-icing.', NULL, 'hard', JSON_ARRAY('apu','bleed','de-ice')),
(@system_id, 'What does the BTL ARM advisory light indicate?',
 'Amber: APU fire extinguisher bottle is ready to be activated. OUT: bottle has been activated, OR no power to the system.', NULL, 'medium', JSON_ARRAY('apu','btl-arm')),
(@system_id, 'What does the APU BOTTLE LOW advisory indicate?',
 'Amber. Fire extinguisher bottle is low or empty. Defer per MEL or replenish.', NULL, 'medium', JSON_ARRAY('apu','bottle-low')),
(@system_id, 'TRUE or FALSE — The APU starter-generator can be powered from external power for an APU start.',
 'TRUE. Either the aeroplane main batteries OR external power can supply the APU starter-generator.', NULL, 'medium', JSON_ARRAY('apu','starter','external')),
(@system_id, 'What does the APU louvered air-inlet cover do?',
 'Helps prevent snow and sleet from entering the APU air inlet during long turnarounds or overnight stops. Optional accessory.', NULL, 'medium', JSON_ARRAY('apu','louvre')),
(@system_id, 'Where is APU exhaust discharged?',
 'Through an exhaust ejector and an upwards-pointing outlet at the AFT END of the titanium tailcone. Directs hot exhaust away from ground crew.', NULL, 'hard', JSON_ARRAY('apu','exhaust')),
(@system_id, 'TRUE or FALSE — During an in-flight emergency, the APU can be started for backup electrical power.',
 'FALSE. The APU CANNOT be started or operated in flight. The shutoff valve auto-closes when airborne. In-flight redundancy is via engine GENs + TRUs + batteries (Phase 5 Electrical).', NULL, 'hard', JSON_ARRAY('apu','flight','restriction'));

SELECT COUNT(*) AS flashcards_inserted FROM flashcards WHERE system_id = @system_id;
