-- =============================================================================
-- AviatorTutor — Phase 5: ATA 24 Electrical Power — 36 flashcards.
-- =============================================================================

SET @system_id := (SELECT id FROM systems WHERE slug = 'electrical' LIMIT 1);
SELECT @system_id AS resolved_system_id;

DELETE FROM flashcards WHERE system_id = @system_id;

INSERT INTO flashcards (system_id, front, back, hint, difficulty, tags) VALUES
(@system_id, 'What does EPGDS stand for?',
 'Electrical Power Generation and Distribution System.', NULL, 'easy', JSON_ARRAY('electrical','epgds')),
(@system_id, 'How many independent sources of DC power does the Q400 have in flight?',
 'FOUR. Two engine-driven starter/generators + two Transformer Rectifier Units (TRUs).',
 'Mnemonic: 4-DC-SOURCES.', 'medium', JSON_ARRAY('electrical','sources')),
(@system_id, 'What two halves make up the EPGDS?',
 'AC generation system (115 VAC variable frequency from two engine-driven AC generators) AND DC generation system (28 VDC from starter/generators, TRUs, batteries, optional APU).',
 'Mnemonic: EPGDS-DC-AC.', 'easy', JSON_ARRAY('electrical','architecture')),
(@system_id, 'How many NiCad batteries does the Q400 have?',
 'THREE: two 40 Ahr (MAIN + AUXILIARY) and one 17 Ahr STANDBY.',
 'Mnemonic: 40-40-17.', 'easy', JSON_ARRAY('electrical','batteries')),
(@system_id, 'Where is the 17 Ahr standby battery located?',
 'In the forward fuselage, adjacent to the two 40 Ahr main and aux batteries.', NULL, 'medium', JSON_ARRAY('electrical','batteries','location')),
(@system_id, 'What is the nominal voltage of a 40 Ahr Q400 battery under load?',
 '24 VDC (20 cells × 1.2 VDC per cell).', NULL, 'medium', JSON_ARRAY('electrical','batteries','voltage')),
(@system_id, 'What is the no-load voltage of a 40 Ahr Q400 battery?',
 'Approximately 28 VDC at the battery terminals.', NULL, 'hard', JSON_ARRAY('electrical','batteries','voltage')),
(@system_id, 'What charging voltage is required to bring the 40 Ahr batteries to full charge?',
 '28–32 VDC (1.4–1.6 VDC per cell). Provided by any DC generator on line.',
 'Mnemonic: 28-VDC-CHARGE.', 'hard', JSON_ARRAY('electrical','batteries','charging')),
(@system_id, 'What happens if a DC GPU output voltage is below 28 VDC and connected with batteries paralleled?',
 'The batteries DISCHARGE into the aircraft loads. They cannot recharge regardless of how long the cart is connected.', NULL, 'hard', JSON_ARRAY('electrical','batteries','external-power')),
(@system_id, 'How many engine-driven AC generators does the Q400 have, and what is their output?',
 'Two AC generators. Output: 115 VAC variable frequency.', NULL, 'easy', JSON_ARRAY('electrical','ac','generators')),
(@system_id, 'What does each TRU do?',
 'Converts 115 VAC variable frequency to 28 VDC. Two TRUs total: TRU 1 fed by AC GEN 1, TRU 2 by AC GEN 2.', NULL, 'medium', JSON_ARRAY('electrical','tru')),
(@system_id, 'Where is the APU starter/generator located?',
 'In the tail cone section of the aeroplane.', NULL, 'medium', JSON_ARRAY('electrical','apu','location')),
(@system_id, 'What does the APU starter/generator supply, and where, on the ground?',
 '28 VDC to the essential MAIN and SECONDARY DC buses.', NULL, 'medium', JSON_ARRAY('electrical','apu','ground-ops')),
(@system_id, 'What is the EPCU?',
 'Electrical Power Control Unit — the system brain. Monitors all sources and buses; manages bus tie contactors automatically; re-configures power flow on any failure.',
 'Mnemonic: EPCU-BRAIN.', 'easy', JSON_ARRAY('electrical','epcu','architecture')),
(@system_id, 'What is the GCU?',
 'Generator Control Unit. One per generator. Receives EPCU TRIP commands; manages local generator behaviour.', NULL, 'medium', JSON_ARRAY('electrical','gcu')),
(@system_id, 'Where is the DC external power (GPU) receptacle located on the Q400?',
 'On the LEFT side of the forward fuselage.',
 'Mnemonic: DC-LEFT-AC-RIGHT.', 'medium', JSON_ARRAY('electrical','external-power','dc')),
(@system_id, 'Where is the AC external power (GPU) receptacle located on the Q400?',
 'On the RIGHT side of the forward fuselage near the nose cone.', NULL, 'medium', JSON_ARRAY('electrical','external-power','ac')),
(@system_id, 'While DC external power is connected, what does the EPCU do with the engine-driven generators?',
 'It INHIBITS the generator connections to the main buses. The cart powers the buses; generators wait. Main and auxiliary batteries stay connected.', NULL, 'hard', JSON_ARRAY('electrical','external-power','epcu')),
(@system_id, 'How is the standby battery connected during engine start with DC external power?',
 'It is DIODE-ISOLATED from the left main during start, to ensure ESS bus voltage stays acceptable.', NULL, 'hard', JSON_ARRAY('electrical','batteries','engine-start')),
(@system_id, 'On the MFD AC GEN LOAD digital display, what does "+1.30" indicate?',
 'OVERLOAD at 130% of rated capacity. The "+" prefix is the overload indicator.',
 'Mnemonic: +1.00-OVERLOAD.', 'medium', JSON_ARRAY('electrical','indications','load')),
(@system_id, 'On the MFD AC GEN LOAD display, what does ".60" indicate?',
 'Generator is loaded at 60% of maximum output. Leading zero is suppressed.', NULL, 'medium', JSON_ARRAY('electrical','indications','load')),
(@system_id, 'What does it mean when nothing is displayed in the AC GEN LOAD field?',
 'The load is in the EXPECTED range. Display only appears when there is something noteworthy (overload or specific value reading).', NULL, 'hard', JSON_ARRAY('electrical','indications','load')),
(@system_id, 'In a main bus fault, what is the FIRST caution that illuminates?',
 'DC BUS caution light. Indicates fault impending condition. The bus is being isolated.', NULL, 'medium', JSON_ARRAY('electrical','bus-fault','indications')),
(@system_id, 'How long does the EPCU give a main bus fault to clear before tripping the generator?',
 'Approximately 5 seconds. If the fault persists past 5 seconds, EPCU sends a TRIP signal to the GCU.',
 'Mnemonic: 5-SEC-TRIP.', 'medium', JSON_ARRAY('electrical','bus-fault','timing')),
(@system_id, 'After the EPCU sends the TRIP signal in a persistent main bus fault, what other actions occur?',
 'EPCU opens and locks-out the contactors connecting the batteries to the affected main bus. MAIN BATTERY (or AUX and STBY BATTERY) caution lights illuminate. Related DC GEN caution illuminates.', NULL, 'hard', JSON_ARRAY('electrical','bus-fault','cascade')),
(@system_id, 'On a single DC generator failure in flight, what does the crew typically experience?',
 'Almost nothing. EPCU re-configures bus ties; surviving DC gen + both TRUs feed all DC buses. DC GEN caution illuminates as the only indication.', NULL, 'medium', JSON_ARRAY('electrical','single-gen','operations')),
(@system_id, 'On dual generator failure with both TRUs operating, what happens?',
 'TRUs continue to provide DC (still fed by 115 VAC from windmilling AC gens if available). Essential buses remain alive. Non-essential loads automatically shed per EPCU logic.', NULL, 'hard', JSON_ARRAY('electrical','dual-gen','load-shed')),
(@system_id, 'What is the consequence of all four DC sources being lost?',
 'Battery-only operation. 40 Ahr main + aux serve essential buses; 17 Ahr standby covers ESS standby bus longest. Time-critical — divert to nearest suitable airport.', NULL, 'hard', JSON_ARRAY('electrical','battery-only','divert')),
(@system_id, 'TRUE or FALSE — In flight, the engine-driven DC starter/generators are the primary source of DC power.',
 'FALSE. The TRUs typically carry most of the DC load in flight. The starter/generators are sized primarily for engine starting.', NULL, 'hard', JSON_ARRAY('electrical','trivia','sources')),
(@system_id, 'TRUE or FALSE — The 17 Ahr standby battery is in the same compartment as the two 40 Ahr batteries.',
 'TRUE. The standby battery is in the forward fuselage adjacent to the two 40 Ahr batteries.', NULL, 'medium', JSON_ARRAY('electrical','batteries','location')),
(@system_id, 'TRUE or FALSE — DC GPU output below 28 VDC will charge the batteries slowly.',
 'FALSE. Below 28 VDC the batteries DISCHARGE into the aircraft loads. They will not charge at all regardless of time.', NULL, 'hard', JSON_ARRAY('electrical','external-power','batteries')),
(@system_id, 'TRUE or FALSE — The EPCU re-configures bus ties automatically without crew action.',
 'TRUE. Bus tie contactor management is fully automatic. Crew action is required only after the EPCU completes its re-configuration and a caution illuminates.', NULL, 'medium', JSON_ARRAY('electrical','epcu','automation')),
(@system_id, 'TRUE or FALSE — The DC BUS caution always means a generator has tripped.',
 'FALSE. DC BUS caution is the FIRST indication of a fault. The generator has not tripped yet — that takes 5 seconds of fault persistence.', NULL, 'medium', JSON_ARRAY('electrical','bus-fault','indications')),
(@system_id, 'TRUE or FALSE — AC external power can connect directly to the aircraft buses without quality monitoring.',
 'FALSE. The AC External Power Protection Unit (AC PPU) on the right ACCB monitors voltage / frequency / phase quality before letting power onto the variable-frequency buses. Bad power is rejected.', NULL, 'hard', JSON_ARRAY('electrical','external-power','ppu')),
(@system_id, 'What is the role of the AC PPU?',
 'External Power Protection Unit. Monitors AC ground power voltage, frequency, and phase. Rejects power that is outside acceptable limits. Located on the right ACCB.', NULL, 'hard', JSON_ARRAY('electrical','external-power','ppu')),
(@system_id, 'On engine start with DC external power connected, how do the contactors and batteries behave?',
 'Contactors connecting MAIN and AUX batteries to the main buses close AUTOMATICALLY upon engine-start selection. Batteries assist the start in parallel with the cart. Standby battery is diode-isolated from left main during start.', NULL, 'hard', JSON_ARRAY('electrical','engine-start','external-power'));

SELECT COUNT(*) AS flashcards_inserted FROM flashcards WHERE system_id = @system_id;
