-- =============================================================================
-- AviatorTutor — Phase 18: ATA 22B FMS — 36 flashcards.
-- =============================================================================

SET @system_id := (SELECT id FROM systems WHERE slug = 'fms' LIMIT 1);
SELECT @system_id AS resolved_system_id;

DELETE FROM flashcards WHERE system_id = @system_id;

INSERT INTO flashcards (system_id, front, back, hint, difficulty, tags) VALUES
(@system_id, 'What FMS is fitted to the Q400?',
 'Universal Avionics UNS-1 series Flight Management System. Standard Q400 build is typically single FMS; some operators have dual installations.', NULL, 'easy', JSON_ARRAY('fms','manufacturer')),
(@system_id, 'What are the four main components of the Q400 FMS?',
 'NCU (Navigation Computer Unit) + FPCDU (Flat-Panel Control Display Unit, 4" or 5") + DTU (Data Transfer Unit, model DTU 100) + Configuration Module.',
 'Mnemonic: UNS-1-NCU-FPCDU-DTU-CONFIG.', 'medium', JSON_ARRAY('fms','components')),
(@system_id, 'What does the NCU do?',
 'Navigation Computer Unit. The FMS brain. Performs position calculation, lateral guidance (LNAV), vertical guidance (VNAV), fuel management, frequency management. Outputs steering commands to the AFCS.', NULL, 'medium', JSON_ARRAY('fms','ncu')),
(@system_id, 'What does the DTU do?',
 'Data Transfer Unit (DTU 100). Loads the navigation database from a sealed memory cartridge into the NCU. Used during AIRAC database updates. Typically operated by maintenance.', NULL, 'medium', JSON_ARRAY('fms','dtu')),
(@system_id, 'What is the FMS position sensor priority?',
 'GPS (primary, with SBAS augmentation for LPV approaches) → scanning DME (backup, requires 2+ stations for triangulation) → VOR/DME (single-station fix) → AHRS+ADC (dead reckoning, last resort).',
 'Mnemonic: GPS-DME-VOR-AHRS.', 'hard', JSON_ARRAY('fms','sensors')),
(@system_id, 'What does the Sensor Watchdog do?',
 'Continuously monitors all available position sensors (GPS, DME, VOR/DME, AHRS+ADC). Selects the best source for FMS position. Excludes faulted sensors.',
 'Mnemonic: SENSOR-WATCHDOG.', 'hard', JSON_ARRAY('fms','watchdog')),
(@system_id, 'How does scanning DME work, and what does it require?',
 'FMS scans multiple DME stations simultaneously and triangulates a position from the distances. Requires AT LEAST 2 stations in range. Provides position when GPS unavailable.',
 'Mnemonic: SCAN-DME-2-STATIONS.', 'hard', JSON_ARRAY('fms','scanning-dme')),
(@system_id, 'What is the navigation database cycle structure?',
 'Dual-cycle: current AIRAC + next AIRAC simultaneously available in the FMS. Crew swaps cycles via FPCDU on the new cycle''s effective date. AIRAC cycle is 28 DAYS.',
 'Mnemonic: DUAL-CYCLE-28-DAYS.', 'hard', JSON_ARRAY('fms','database')),
(@system_id, 'How long is the standard ICAO AIRAC cycle?',
 '28 days. Determined by ICAO. Q400 FMS dual-cycle has the current 28-day AIRAC + the next 28-day AIRAC simultaneously available.', NULL, 'medium', JSON_ARRAY('fms','airac')),
(@system_id, 'What is pilot data storage, and is it preserved across database updates?',
 'Pilot data storage holds custom airports, routes, and waypoints in non-volatile memory. PRESERVED across database updates — your custom waypoints don''t get wiped when a new AIRAC cycle is loaded.', NULL, 'medium', JSON_ARRAY('fms','pilot-data')),
(@system_id, 'What are company routes?',
 'Pre-programmed operator-specific routes. Frequently-flown city pairs with standard routings. Loaded by dispatch/maintenance. Selecting a company route in the FPCDU loads the entire routing in one selection.', NULL, 'medium', JSON_ARRAY('fms','company-routes')),
(@system_id, 'What is offline flight planning, and how is the plan loaded into the FMS?',
 'External tools (e.g. Jeppesen Mission Planner, operator dispatch systems) generate complex flight plans. The plan is loaded into the FMS via the DTU using a memory module. Useful for international/complex routings.', NULL, 'hard', JSON_ARRAY('fms','offline-planning')),
(@system_id, 'What does LNAV provide?',
 'Lateral Navigation. FMS computes desired track from current position to next waypoint per the active flight plan. Output to AFCS as steering commands. Bearing pointer to FMS shows next waypoint.', NULL, 'medium', JSON_ARRAY('fms','lnav')),
(@system_id, 'What does VNAV provide?',
 'Vertical Navigation. FMS computes vertical profile per altitude constraints in flight plan: top-of-descent (TOD), descent angles, altitude/speed targets. Output to AFCS for vertical mode.', NULL, 'medium', JSON_ARRAY('fms','vnav')),
(@system_id, 'How does frequency management work?',
 'FMS automatically tunes the active nav radios (VOR1, VOR2, ADF1, ADF2) for the next waypoint or approach via the ARCDU. Manual override via the ARCDU.',
 'Mnemonic: FREQ-AUTO-FMS-MANUAL-ARCDU.', 'medium', JSON_ARRAY('fms','frequency')),
(@system_id, 'What three conditions cause the Position Uncertain message?',
 '(1) GPS LOST. (2) DME inputs INSUFFICIENT (fewer than 2 stations or inconsistent triangulation). (3) NO OTHER VALID position sensor (VOR/DME unavailable, AHRS dead reckoning degraded).',
 'Mnemonic: POSITION-UNCERTAIN-3.', 'hard', JSON_ARRAY('fms','position-uncertain')),
(@system_id, 'What does the Position Uncertain message demand of the crew?',
 'Revert to RAW NAV (VOR/ADF via Bearing pointers per Phase 13 navigation). Cross-check FMS position against raw nav. Run QRH non-normal. Consider divert to a station with adequate ground-based nav coverage.', NULL, 'hard', JSON_ARRAY('fms','position-uncertain','action')),
(@system_id, 'TRUE or FALSE — A GPS loss in cruise immediately triggers Position Uncertain.',
 'FALSE. Position Uncertain requires GPS LOST AND DME insufficient AND no other valid sensor — three conditions. GPS loss alone reverts to scanning DME (silent transition).', NULL, 'hard', JSON_ARRAY('fms','gps-loss')),
(@system_id, 'Where does the FMS bearing pointer point?',
 'NEXT WAYPOINT in the active flight plan — not destination. As waypoints are sequenced, the pointer updates.',
 'Mnemonic: FMS-NEXT-WPT.', 'medium', JSON_ARRAY('fms','bearing-pointer')),
(@system_id, 'How does the FMS handle high-latitude operations?',
 'At high latitudes (typically near 70°N/S or 80°N/S), the FMS automatically switches its heading reference from MAGNETIC to TRUE. Magnetic variation becomes extreme and unreliable near the poles. Standby compass remains magnetic — disagreement is normal.',
 'Mnemonic: HIGH-LAT-TRUE.', 'hard', JSON_ARRAY('fms','high-latitude')),
(@system_id, 'How does the FMS handle magnetic variation, and where does it come from?',
 'FMS uses magnetic variation from its database (per geographic position). VOR stations use their published declination (set when the station was established). Small discrepancies (<1°) are normal between FMS course and raw VOR course.',
 'Mnemonic: VAR-VS-DECLINATION-1.', 'hard', JSON_ARRAY('fms','variation')),
(@system_id, 'What is SBAS, and what does it support?',
 'Spaced-Based Augmentation System. Examples: WAAS (USA), EGNOS (Europe). SBAS augments GPS with correction signals. Supports LPV (Localiser Performance with Vertical guidance) approaches — precision-like approaches with vertical guidance from GPS+SBAS.',
 'Mnemonic: SBAS-LPV.', 'hard', JSON_ARRAY('fms','sbas','lpv')),
(@system_id, 'What is AFIS?',
 'Aircraft Flight Information Service. Datalink interface for weather, NOTAMs, and dispatch communications. Provides text-based information to the cockpit via FMS interface.',
 'Mnemonic: AFIS-UNILINK.', 'medium', JSON_ARRAY('fms','afis')),
(@system_id, 'What is UniLink?',
 'Universal Avionics datalink module. Provides ACARS-equivalent communications between aircraft and ground (operator dispatch, ATC, weather services). Universal-Avionics ecosystem product.', NULL, 'medium', JSON_ARRAY('fms','unilink')),
(@system_id, 'How does fuel management work in the FMS?',
 'FMS uses fuel sensor inputs (Phase 8) + fuel-flow data to predict fuel-on-board at each waypoint. Computes fuel reserves at destination + alternates. Alerts crew if fuel below threshold.', NULL, 'medium', JSON_ARRAY('fms','fuel-management')),
(@system_id, 'What is the recommended cross-check frequency for FMS vs raw nav in cruise?',
 'At least every 30 minutes (per Phase 13 navigation). Set Bearing 1 to VOR1 with appropriate radial; cross-check FMS position. Discrepancy <1° is normal.', NULL, 'medium', JSON_ARRAY('fms','cross-check')),
(@system_id, 'What FPCDU pages would you typically use during pre-flight?',
 'POS (position), FPL (flight plan), DEP (departure), ARR (arrival), PERF (performance), FUEL (fuel data), DATA (NAV aids/airports), TUNE (frequencies). Initialisation page on power-up shows AIRAC cycle.', NULL, 'medium', JSON_ARRAY('fms','fpcdu','pages')),
(@system_id, 'What is the priority order from best to worst for FMS position?',
 'GPS (best, with SBAS for LPV) > scanning DME (≥2 stations) > VOR/DME (single station) > AHRS+ADC dead reckoning (worst, degrades over time).', NULL, 'hard', JSON_ARRAY('fms','priority')),
(@system_id, 'TRUE or FALSE — The FMS auto-tunes nav radios; the ARCDU is just for display.',
 'FALSE. The FMS auto-tunes nav radios via the ARCDU. The ARCDU is also the manual override for tuning. The ARCDU is the radio tuner; the FMS sends frequencies to it.', NULL, 'medium', JSON_ARRAY('fms','frequency','arcdu')),
(@system_id, 'TRUE or FALSE — Pilot data storage is wiped when the navigation database is updated.',
 'FALSE. Pilot data (custom airports, routes, waypoints) is in non-volatile memory and PRESERVED across database updates.', NULL, 'medium', JSON_ARRAY('fms','pilot-data','preservation')),
(@system_id, 'What does the FMS do during a VNAV descent?',
 'Computes top-of-descent (TOD) point based on current position, target altitude, and aircraft performance. Provides descent angle and altitude/speed targets to AFCS. Crew sees vertical deviation indicator on PFD; AFCS flies the descent in VNAV mode.', NULL, 'hard', JSON_ARRAY('fms','vnav','descent')),
(@system_id, 'What is the role of the Configuration Module?',
 'Stores aircraft-specific configuration: sensor types installed, output formats, software options, customer-specific parameters. Read by NCU on power-up. Critical for correct FMS operation in this airframe.', NULL, 'hard', JSON_ARRAY('fms','config')),
(@system_id, 'TRUE or FALSE — Q400 FMS is GE Aviation manufactured.',
 'FALSE. Q400 FMS is Universal Avionics UNS-1 series. Universal Avionics is a specialty avionics manufacturer focused on FMS and related products.', NULL, 'easy', JSON_ARRAY('fms','manufacturer')),
(@system_id, 'TRUE or FALSE — A magnetic variation discrepancy of 0.8° between FMS course and raw VOR course indicates a fault.',
 'FALSE. Discrepancies <1° are normal. FMS uses database variation; VOR uses station declination — these can differ slightly. Don''t assume one is wrong.', NULL, 'hard', JSON_ARRAY('fms','variation')),
(@system_id, 'What does Position Uncertain look like on the FPCDU?',
 'A POSITION UNCERTAIN message displayed on the FPCDU + possibly on the PFD. The FMS continues to estimate position from available sensors but flags low confidence. Crew action required.', NULL, 'medium', JSON_ARRAY('fms','position-uncertain','indication')),
(@system_id, 'How does the FMS handle a database AIRAC cycle change mid-flight?',
 'Dual-cycle architecture: both current and next AIRAC are loaded. On the new cycle''s effective date/time (00:00 UTC standard), crew swaps via FPCDU. No ground service required for the cycle change.', NULL, 'hard', JSON_ARRAY('fms','airac','cycle-change'));

SELECT COUNT(*) AS flashcards_inserted FROM flashcards WHERE system_id = @system_id;
