-- =============================================================================
-- AviatorTutor — Phase 16: ATA 61 Propeller — 36 flashcards.
-- =============================================================================

SET @system_id := (SELECT id FROM systems WHERE slug = 'propeller' LIMIT 1);
SELECT @system_id AS resolved_system_id;

DELETE FROM flashcards WHERE system_id = @system_id;

INSERT INTO flashcards (system_id, front, back, hint, difficulty, tags) VALUES
(@system_id, 'How many blades does each Q400 propeller have, and what material?',
 'SIX composite blades per propeller. Counterweighted — natural moment toward HIGH pitch in flight.',
 'Mnemonic: 6-BLADE-COMPOSITE.', 'easy', JSON_ARRAY('propeller','blades')),
(@system_id, 'What does the PEC do?',
 'Propeller Electronic Control. Dual-channel microprocessor in each engine nacelle. Manages constant-speed governing, beta, reverse, autofeather, AUPC, UPTRIM. Commands PCU.', NULL, 'medium', JSON_ARRAY('propeller','pec')),
(@system_id, 'What does the PCU do?',
 'Pitch Control Unit. Hydromechanical, electrically commanded by PEC. Meters HP engine oil through a two-stage servo valve to fine or coarse pitch chambers of the pitch change cylinder.', NULL, 'medium', JSON_ARRAY('propeller','pcu')),
(@system_id, 'What happens to propeller blades on HP oil loss in flight?',
 'Blades AUTOCOARSEN to a safe high-pitch windmilling condition. Counterweight effort dominates centrifugal twisting moment toward HIGH pitch. Low drag, low yaw effect.',
 'Mnemonic: AUTOCOARSEN-HP-LOSS.', 'hard', JSON_ARRAY('propeller','autocoarsen')),
(@system_id, 'What happens to propeller blades on HP oil loss in REVERSE?',
 'Blades go to MAX REVERSE blade angle. Counterweight effort acts toward NEGATIVE pitch at negative blade angles. Different from in-flight HP loss behaviour.', NULL, 'hard', JSON_ARRAY('propeller','reverse-loss')),
(@system_id, 'At what RPMs does Constant Speed Mode enter, per Condition Lever position?',
 '850 RPM (MIN), 900 RPM (mid), 1020 RPM (MAX) per CL position selection.',
 'Mnemonic: 850-900-1020-CL.', 'medium', JSON_ARRAY('propeller','constant-speed')),
(@system_id, 'At what propeller RPM does the hydraulic OSG drop the HP oil supply?',
 'Approximately 1071 RPM (105% of 1020 RPM). Pitch coarsens via counterweights, RPM drops, OSG reconnects HP. Stable governing at ~1071 RPM until cause removed.',
 'Mnemonic: 1071-HYD-1122-ELEC.', 'hard', JSON_ARRAY('propeller','osg','hydraulic')),
(@system_id, 'At what propeller RPM does the FADEC electronic NP overspeed circuit signal fuel reduction?',
 'Approximately 1122 RPM. Signals FMU to reduce fuel — engine power drops, prop RPM follows. Restores normal fuel below threshold.', NULL, 'hard', JSON_ARRAY('propeller','osg','electronic')),
(@system_id, 'In which mode is the hydraulic OSG section LOCKED OUT, and what protects against overspeed there?',
 'Locked out in REVERSE. The FADEC NP electronic overspeed circuit is the primary overspeed protection in reverse.',
 'Mnemonic: OSG-LOCKED-REVERSE.', 'hard', JSON_ARRAY('propeller','reverse','osg')),
(@system_id, 'What is the propeller flight fine stop in CONSTANT SPEED mode (in flight)?',
 'HARD HYDRAULIC stop at 16°. SOFT PEC stop at 16.5° while PLA is at or above Flight Idle. Blade angle cannot fall below 16° during normal in-flight operation.',
 'Mnemonic: 16-HARD-16.5-SOFT.', 'hard', JSON_ARRAY('propeller','flight-fine-stop')),
(@system_id, 'What conditions must be met to enable blade angles below 16°?',
 'BOTH (a) PLA brought back BELOW Flight Idle AND (b) weight-on-wheels (WOW). PROPELLER GROUND RANGE lights illuminate when blade angles are below 16°.', NULL, 'hard', JSON_ARRAY('propeller','beta','ground')),
(@system_id, 'What does the GBE valve do, and when?',
 'Ground Beta Enable valve. Locks out the hydraulic OSG section during ground beta operations to prevent transient overspeed at flat pitch from interfering with pitch control. GBE failure caught by scheduled OSG test on the ground.',
 'Mnemonic: GBE-LOCKS-OSG-GROUND-BETA.', 'hard', JSON_ARRAY('propeller','gbe')),
(@system_id, 'What is the NP underspeed governing speed in beta range?',
 '660 RPM. Governed by FADEC + engine fuel system. Engine controls speed in beta (engine-driven rather than airspeed-driven).',
 'Mnemonic: BETA-660-NP.', 'medium', JSON_ARRAY('propeller','beta','660')),
(@system_id, 'What is the normal reverse RPM range and max SHP?',
 '660-950 RPM normal range. Maximum 1500 SHP. At low airspeeds may reach max reverse stop; engine OSG controls speed up to 1020 RPM.',
 'Mnemonic: REVERSE-660-950-1500.', 'medium', JSON_ARRAY('propeller','reverse')),
(@system_id, 'When does synchrophasing operate, and what does it do?',
 'PEC enters synchrophase mode when both prop speeds within predetermined difference, in flight. Reduces cabin noise by phase-controlling slave-vs-master propeller via MPU signals. Phase demand from CLA position. NOT active at takeoff.',
 'Mnemonic: SYNC-NO-TAKEOFF.', 'hard', JSON_ARRAY('propeller','synchrophase')),
(@system_id, 'What two conditions must be met for autofeather to ARM?',
 'Both engine torques >50% AND both PLAs advanced beyond 60°. Autofeather is selected ON for takeoff via the AUTOFEATHER switchlight.', NULL, 'hard', JSON_ARRAY('propeller','autofeather','arm')),
(@system_id, 'What conditions cause autofeather to TRIGGER (engine failure detection)?',
 'ONE engine torque drops below 25% OR Np drops below 816 (80%) for at least 3 SECONDS.',
 'Mnemonic: AF-50-25-816-3SEC.', 'hard', JSON_ARRAY('propeller','autofeather','trigger')),
(@system_id, 'What actions happen on autofeather trigger?',
 'A/F ARM light goes out, AUX FEATHER PUMP energized, prop feathers automatically, FADEC of OPERATING engine receives UPTRIM command (extra power).',
 'Mnemonic: AF-UPTRIMS-OPERATING.', 'hard', JSON_ARRAY('propeller','autofeather','actions')),
(@system_id, 'What does the AUTOFEATHER switchlight on the engine instrument panel show?',
 'SELECT segment when ON. ARM segment when both torque + PLA conditions met during takeoff. ARM goes out on autofeather trigger or when conditions removed.', NULL, 'medium', JSON_ARRAY('propeller','autofeather','switchlight')),
(@system_id, 'What is the role of the auxiliary propeller feathering pump?',
 '28 VDC electrical motor + external gear pump. Independent oil pressure source for feathering. Used for autofeather, alternate feather, manual feather, and maintenance feather/unfeather.', NULL, 'medium', JSON_ARRAY('propeller','feather-pump')),
(@system_id, 'What happens if PLA is moved below Flight Idle in flight?',
 'BETA WARNING HORN sounds. Move PLA back above the gate IMMEDIATELY. NEVER operate below Flight Idle in flight.',
 'Mnemonic: BETA-HORN-IN-FLIGHT.', 'hard', JSON_ARRAY('propeller','beta','horn')),
(@system_id, 'How is the OSG tested, and where?',
 'PROP O''SPEED GOVERNOR test switch on the Pilots Side Panel. Tested on the ground. Confirms hydraulic OSG functional and GBE valve in correct in-flight position.', NULL, 'medium', JSON_ARRAY('propeller','osg','test')),
(@system_id, 'What is the role of the MPU?',
 'Magnetic Pickup Unit. Provides propeller speed signal to PEC. Used for governing, synchrophasing, and ANVS propeller balance monitoring.', NULL, 'medium', JSON_ARRAY('propeller','mpu')),
(@system_id, 'What is AUPC?',
 'Automatic Underspeed Propeller Control. Function of the PEC. Causes propeller to operate on overspeed governor in event of drive coarse failure. Independent of basic PEC control functions.', NULL, 'hard', JSON_ARRAY('propeller','aupc')),
(@system_id, 'TRUE or FALSE — Propeller blades on the Q400 naturally seek LOW pitch in flight due to centrifugal twisting moment.',
 'FALSE. The blades are COUNTERWEIGHTED. The counterweight effort dominates centrifugal twisting moment in flight, biasing the natural moment toward HIGH pitch. This makes HP loss fail-safe (autocoarsen).', NULL, 'hard', JSON_ARRAY('propeller','counterweight')),
(@system_id, 'What is the detent on the PLA quadrant for?',
 'Prevents unintentional movement of the PLA below FLIGHT IDLE during flight. Combined with the beta warning horn, prevents inadvertent in-flight beta operation.', NULL, 'medium', JSON_ARRAY('propeller','pla','detent')),
(@system_id, 'How do power lever positions correspond to propeller modes?',
 'PLA above Flight Idle: in-flight constant speed mode (PEC). PLA below Flight Idle: ground beta range (blade angle control). PLA in reverse arc: reverse speed control.', NULL, 'medium', JSON_ARRAY('propeller','pla','modes')),
(@system_id, 'What is the in-flight constant-speed mode logic?',
 'PEC compares actual NP to demanded NP (per CL position 850/900/1020). Underspeed: more oil to fine pitch (less coarse-seeking). Overspeed: more oil to coarse pitch (less fine-seeking). HP oil for governing passes through OSG.', NULL, 'hard', JSON_ARRAY('propeller','constant-speed','logic')),
(@system_id, 'What is the in-flight constant-speed entry trigger?',
 'Propeller speed reaches 850, 900, or 1020 RPM per CL position. Below entry RPM, prop is in flight beta or constant-speed transitioning.', NULL, 'medium', JSON_ARRAY('propeller','entry')),
(@system_id, 'TRUE or FALSE — Synchrophasing operates during takeoff to reduce engine noise.',
 'FALSE. Synchrophasing does NOT operate at takeoff. High-power transients would confuse the master-slave timing. It activates after takeoff when speeds stabilise.', NULL, 'hard', JSON_ARRAY('propeller','sync')),
(@system_id, 'What protects against autofeather firing on momentary torque dips?',
 'The 3-SECOND minimum hold time on the trigger condition. Torque must be <25% (or Np <816) for at least 3 seconds before autofeather fires. Filters out transient dips.', NULL, 'medium', JSON_ARRAY('propeller','autofeather','filter')),
(@system_id, 'What is the maximum SHP allowed in reverse?',
 '1500 SHP max. Engine schedules fuel based on a power schedule vs PLA in reverse, with this maximum.', NULL, 'medium', JSON_ARRAY('propeller','reverse','shp')),
(@system_id, 'What happens to UPTRIM during normal cruise (no engine failure)?',
 'UPTRIM is not commanded during normal cruise — both engines on equal power. UPTRIM is commanded by autofeather to the OPERATING engine FADEC during an engine failure event.', NULL, 'hard', JSON_ARRAY('propeller','uptrim')),
(@system_id, 'TRUE or FALSE — The hydraulic OSG protects against overspeed in REVERSE mode.',
 'FALSE. The hydraulic OSG section is LOCKED OUT in reverse. The FADEC electronic NP overspeed circuit is the primary overspeed protection in reverse. Mnemonic: OSG-LOCKED-REVERSE.', NULL, 'hard', JSON_ARRAY('propeller','reverse','osg')),
(@system_id, 'What does the PROPELLER GROUND RANGE light indicate?',
 'Illuminates when blade angles are below 16° (PLA brought below Flight Idle). Confirms ground beta operation. Inhibited in flight (16° hard hyd stop).', NULL, 'medium', JSON_ARRAY('propeller','ground-range')),
(@system_id, 'What is the difference between the soft and hard flight fine stops?',
 'HARD stop (16°) is a hydraulic cut-off — physical limit on minimum blade angle in constant-speed mode. SOFT stop (16.5°) is a PEC software limit, operative while PLA is at or above Flight Idle. Both ensure counterweight effort effectiveness for OSG.', NULL, 'hard', JSON_ARRAY('propeller','fine-stop','soft-hard'));

SELECT COUNT(*) AS flashcards_inserted FROM flashcards WHERE system_id = @system_id;
