-- =============================================================================
-- AviatorTutor — Phase 6: ATA 26 Fire Protection — 36 flashcards.
-- =============================================================================

SET @system_id := (SELECT id FROM systems WHERE slug = 'fire-protection' LIMIT 1);
SELECT @system_id AS resolved_system_id;

DELETE FROM flashcards WHERE system_id = @system_id;

INSERT INTO flashcards (system_id, front, back, hint, difficulty, tags) VALUES
(@system_id, 'How many Advanced Pneumatic Detectors (APDs) does the Q400 have, and where?',
 'SEVEN total. Six in the engine nacelles (three per engine: PEZ, LEZ, MWW) plus one in the APU.',
 'Mnemonic: 7-APDs.', 'medium', JSON_ARRAY('fire','apd','count')),
(@system_id, 'Name the three engine zones each nacelle APD covers.',
 'Primary Engine Zone (PEZ), Leading Edge Zone (LEZ), and Main Wheel Well (MWW). One APD per zone, three per engine.',
 'Mnemonic: 3-PER-NACELLE.', 'medium', JSON_ARRAY('fire','apd','zones')),
(@system_id, 'How does an APD detect fire?',
 'Helium-filled sensor tube. Heat raises pressure; an alarm switch closes when the pressure threshold is reached, sending a fire signal to the Control Amplifier.', NULL, 'medium', JSON_ARRAY('fire','apd','principle')),
(@system_id, 'What does the integrity switch on an APD do?',
 'Monitors sensor element pressure. If the APD ruptures, pressure drops and the integrity switch opens — illuminates FAULT A or FAULT B (amber) on the fire protection panel.', NULL, 'hard', JSON_ARRAY('fire','apd','fault')),
(@system_id, 'Difference between FAULT and FIRE indications on the APD?',
 'FAULT = pressure DROP (loop ruptured) — integrity switch opens. FIRE = pressure RISE (heat) — alarm switch closes. Two switches, two distinct meanings.', NULL, 'hard', JSON_ARRAY('fire','apd','indications')),
(@system_id, 'How many smoke detectors are on the Q400, and where?',
 'FOUR total. Two in the aft baggage compartment (front and rear of compartment), one in the forward baggage compartment, one in the lavatory.',
 'Mnemonic: 2-2-1-1-SMOKE.', 'medium', JSON_ARRAY('fire','smoke','count')),
(@system_id, 'How many engine fire bottles are installed and where?',
 'TWO dual-port FIRE bottles, both in the LEFT wing root, in the FWD and AFT positions. Each plumbed to both engines.',
 'Mnemonic: 2-BOTTLES-LEFT-WING.', 'medium', JSON_ARRAY('fire','bottles','engine')),
(@system_id, 'How many shots of suppressant are available per engine?',
 'TWO. The forward bottle is the first shot; if the fire persists, the aft bottle is the second shot, into the same engine.', NULL, 'medium', JSON_ARRAY('fire','bottles','shots')),
(@system_id, 'Which engine zones receive suppressant when an engine bottle discharges?',
 'All three: PEZ, LEZ, and MWW. The bottle is plumbed to flood all three zones simultaneously.', NULL, 'hard', JSON_ARRAY('fire','bottles','plumbing')),
(@system_id, 'How many baggage HRD bottles and LRD bottles are there?',
 'TWO HRD bottles (one for each baggage compartment) plus ONE shared LRD bottle in the aft equipment bay.', NULL, 'medium', JSON_ARRAY('fire','baggage','hrd-lrd')),
(@system_id, 'What happens when you push the AFT BAGGAGE SMOKE/EXTG switchlight?',
 'AFT HRD bottle discharges immediately into aft baggage. LRD bottle discharges automatically 7 MINUTES later. AFT ARM goes out, AFT LOW (amber) illuminates.',
 'Mnemonic: HRD-AFT-7-LRD.', 'medium', JSON_ARRAY('fire','baggage','aft')),
(@system_id, 'What happens when you push the FWD BAGGAGE SMOKE/EXTG switchlight?',
 'FWD HRD bottle AND the shared LRD bottle BOTH discharge SIMULTANEOUSLY into fwd baggage. No 7-minute delay. FWD ARM goes out, FWD LOW illuminates.',
 'Mnemonic: FWD-BOTH-NOW.', 'medium', JSON_ARRAY('fire','baggage','fwd')),
(@system_id, 'What happens to the aft baggage vent valves on a smoke alarm?',
 'Control Amplifier drops power to the inlet and outlet vent valves — they close automatically. INLT and OTLT CLOSED (white) lights illuminate. The fire is starved of airflow.', NULL, 'hard', JSON_ARRAY('fire','baggage','vents')),
(@system_id, 'Where is the lavatory fire bottle located?',
 'Inside the waste-bin cabinet. Single dual-discharge bottle (Potty Bottle) directly above / on the bin.', NULL, 'medium', JSON_ARRAY('fire','lavatory','bottle')),
(@system_id, 'How is the lavatory fire bottle activated?',
 'Thermally. Fusible end-cap seals melt at the set point; end caps blow off; extinguishant discharges through dual outlets. NO electrical interface, no cockpit switch.',
 'Mnemonic: POTTY-FUSE.', 'hard', JSON_ARRAY('fire','lavatory','activation')),
(@system_id, 'TRUE or FALSE — Lavatory smoke is indicated on the flight-deck Fire Protection Panel.',
 'FALSE. Lavatory smoke is indicated in the CABIN ONLY: cabin repeater lights, smoke detector LED, audible chime through P/A. NO flight-deck indication.',
 'Mnemonic: LAV-CABIN-ONLY.', 'medium', JSON_ARRAY('fire','lavatory','indication')),
(@system_id, 'How many portable Halon 1211 fire extinguishers are on board, and where?',
 'FOUR. One in the flight compartment, three in the passenger compartment.',
 'Mnemonic: HALON-1-3-411.', 'easy', JSON_ARRAY('fire','portable','halon')),
(@system_id, 'What types of fires is Halon 1211 effective on?',
 'Electrical, oil, and fuel fires. Halon 1211 is non-corrosive, non-toxic, will not freeze, and will not cause cold burns.', NULL, 'medium', JSON_ARRAY('fire','portable','halon')),
(@system_id, 'What do the GREEN, YELLOW, and RED ranges on a portable extinguisher gauge indicate?',
 'GREEN = serviceable. YELLOW = overcharge. RED = recharge required.', NULL, 'medium', JSON_ARRAY('fire','portable','gauge')),
(@system_id, 'What MUST the crew do before discharging a Halon 1211 extinguisher in the cockpit?',
 'All crew don oxygen masks and select EMERGENCY position — 100% oxygen at positive pressure. Halon displaces oxygen.',
 'Mnemonic: 100%-MASK-COCKPIT.', 'hard', JSON_ARRAY('fire','portable','procedure')),
(@system_id, 'What does the PULL FUEL/HYD OFF T-handle do when pulled?',
 'Closes the fuel and hydraulic shut-off valves on that engine, AND arms the bottle squibs (yellow ARM lights illuminate).',
 'Mnemonic: PULL-ARMS-EXTG-FIRES.', 'medium', JSON_ARRAY('fire','engine','t-handle')),
(@system_id, 'What does the EXTG switch do?',
 'Selects FWD BTL or AFT BTL — sends an electrical signal to fire the chosen bottle squib (Electro-Explosive Device), ruptures the burst disc, releases extinguishant.', NULL, 'medium', JSON_ARRAY('fire','engine','extg')),
(@system_id, 'What does the BTL LOW (amber) advisory light indicate?',
 'One or both engine fire bottles are empty or pressure is low. Control Amplifier monitors bottle pressure constantly via a pressure switch.', NULL, 'medium', JSON_ARRAY('fire','indications','btl-low')),
(@system_id, 'What is the engine-fire memory chant on the Q400?',
 'FLASH · PRESS · PULL · EXTG · 30-sec · OTHER. Note FLASH on the affected engine; PRESS an ENGINE FIRE light to silence tone; PULL the affected T-handle; select EXTG FWD or AFT BTL; wait 30 seconds; if fire persists, OTHER position.', NULL, 'hard', JSON_ARRAY('fire','engine','memory-items')),
(@system_id, 'Why must the crew wait 30 seconds between bottle shots on an engine fire?',
 'Suppressant needs time to soak into the engine zone. Firing the second bottle too soon wastes the last shot — it will exit the zone before doing useful work.', NULL, 'hard', JSON_ARRAY('fire','engine','technique')),
(@system_id, 'Engine fire detection logic: APD in PEZ FAILS and APD in LEZ DETECTS FIRE — what happens?',
 'BOTH a fire indication AND a fault indication. The series logic still passes the fire signal because the LEZ detector is healthy.', NULL, 'hard', JSON_ARRAY('fire','apd','logic')),
(@system_id, 'Engine fire detection logic: APD in LEZ FAILS and APD in PEZ DETECTS FIRE — what happens?',
 'FAULT only — NO fire indication. The series wiring places LEZ upstream of PEZ in such a way that an LEZ failure breaks the path. The panel shows fault, no fire.', NULL, 'hard', JSON_ARRAY('fire','apd','logic')),
(@system_id, 'What runs the TEST DETECTION switch and what is the expected response?',
 'Spring-loaded ENGINE 1 / OFF / ENGINE 2. Pressing each side exercises the full warning chain: master warning flash, CHECK FIRE DET red, PULL FUEL/HYD OFF light, FAULT A and B amber, both ENGINE FIRE lights flash, fire tone (optional). Press an ENGINE FIRE light to acknowledge.', NULL, 'medium', JSON_ARRAY('fire','test','detection')),
(@system_id, 'Where is the shared baggage LRD (Low-Rate Discharge) bottle physically located?',
 'In the AFT equipment bay (rear fuselage). Single bottle, plumbed to discharge into either fwd or aft baggage compartment.', NULL, 'medium', JSON_ARRAY('fire','baggage','lrd-location')),
(@system_id, 'Why is there an LRD bottle in addition to HRD bottles?',
 'HRD knocks down the fire quickly with high pressure. LRD provides a slow soak that prevents reignition over time. Different jobs, different bottles.', NULL, 'hard', JSON_ARRAY('fire','baggage','technique')),
(@system_id, 'TRUE or FALSE — The lavatory smoke detector self-test is performed from the flight deck.',
 'FALSE. The self-test switch is on the smoke detector unit itself in the lavatory; cabin crew operate it. Confirms cabin repeater lights, single chime through P/A, red LED on detector.', NULL, 'medium', JSON_ARRAY('fire','lavatory','test')),
(@system_id, 'What is the difference between a baggage compartment fire response and an engine fire response on the panel?',
 'Engine fire = PULL the T-handle, then EXTG switch. Baggage fire = PUSH the SMOKE/EXTG switchlight. Different physical actions; do not confuse them.', NULL, 'medium', JSON_ARRAY('fire','panel','actions')),
(@system_id, 'What is the FIRE BOTTLE FWD ARM light and when does it illuminate?',
 'Amber advisory. Illuminates when the fwd baggage HRD bottle is armed (after smoke detection). Goes out when the bottle is discharged or the system is disarmed.', NULL, 'medium', JSON_ARRAY('fire','baggage','arm')),
(@system_id, 'What is the role of the Control Amplifier in the fire protection system?',
 'Detection and extinguishing monitoring; Built-In-Test (BIT) functions; drives advisory lights on the Fire Protection Panel; drives the CHECK FIRE DET warning on the Caution and Warning panel; sounds the optional fire tone.', NULL, 'hard', JSON_ARRAY('fire','control-amplifier')),
(@system_id, 'TRUE or FALSE — Loss of the Control Amplifier means complete loss of engine fire detection.',
 'FALSE. Loss of the Control Amplifier will NOT cause complete loss of engine detection or extinguishing capability — the system has redundancy in the alarm path.', NULL, 'hard', JSON_ARRAY('fire','control-amplifier','redundancy')),
(@system_id, 'In the cockpit, the captain decides to hand-fly an engine fire procedure. What is the FIRST action after both ENGINE FIRE lights start flashing?',
 'Press an ENGINE FIRE light to silence the audio fire tone and stop the lights flashing — they will then stay on steady for the duration. AVIATE first; do not pull anything yet.', NULL, 'hard', JSON_ARRAY('fire','engine','first-action'));

SELECT COUNT(*) AS flashcards_inserted FROM flashcards WHERE system_id = @system_id;
