-- =============================================================================
-- AviatorTutor — Phase 12: ATA 33 Lighting — 36 flashcards.
-- =============================================================================

SET @system_id := (SELECT id FROM systems WHERE slug = 'lighting' LIMIT 1);
SELECT @system_id AS resolved_system_id;

DELETE FROM flashcards WHERE system_id = @system_id;

INSERT INTO flashcards (system_id, front, back, hint, difficulty, tags) VALUES
(@system_id, 'What three categories does Q400 lighting split into?',
 'Interior lighting, exterior lighting, and emergency lighting.', NULL, 'easy', JSON_ARRAY('lighting','categories')),
(@system_id, 'What is the voltage and dimming method of cockpit panel/instrument lighting?',
 'Variable-intensity 5 VDC. Disc-shaped lamp assemblies behind Plexiglas, dimmed via rotary knobs OFF→BRT.', NULL, 'medium', JSON_ARRAY('lighting','panel','5vdc')),
(@system_id, 'Which lighting bus powers the cockpit DOME light, and what is the special property?',
 'BATTERY PWR bus. Operates regardless of BATTERY MASTER position — dome will work without battery master ON.',
 'Mnemonic: DOME-BATTERY-NO-MASTER.', 'hard', JSON_ARRAY('lighting','dome','bus')),
(@system_id, 'Which bus powers the cockpit STORM lights, and what is their purpose?',
 'L SECONDARY bus. Storm lights provide bright cockpit lighting to compensate for night-vision loss after lightning flashes.',
 'Mnemonic: STORM-FLASH-RECOVER.', 'hard', JSON_ARRAY('lighting','storm','recovery')),
(@system_id, 'What does the PILOTS FLT PNL knob control?',
 'Pilot side console + ICP1 + Standby Instruments lighting.', NULL, 'medium', JSON_ARRAY('lighting','pilot','panel')),
(@system_id, 'What does the COPILOTS FLT PNL knob control?',
 'Copilot side console + ICP2 + Landing Gear selector panel + GPWS/Hydraulic Control panel lighting.', NULL, 'hard', JSON_ARRAY('lighting','copilot','panel')),
(@system_id, 'What controls the cockpit clock lights?',
 'The GLARESHIELD knob on the PANEL LIGHTING control panel. Adjusting the glareshield brightness adjusts both clock lights.', NULL, 'hard', JSON_ARRAY('lighting','clock','glareshield')),
(@system_id, 'What controls the standby compass light?',
 'The CAUT/ADVSY LIGHTS DIM/BRT toggle switch. Different from the main panel knobs.', NULL, 'hard', JSON_ARRAY('lighting','standby-compass','dim')),
(@system_id, 'How many cabin overhead and sidewall fluorescent fixtures are installed?',
 'TWENTY-ONE overhead AND TWENTY-ONE sidewall fluorescent fixtures.',
 'Mnemonic: 21-OVER-21-SIDE.', 'medium', JSON_ARRAY('lighting','cabin','fluorescent')),
(@system_id, 'How many reading lights are in each Passenger Service Unit (PSU)?',
 'TWO reading lights per PSU. Each has an adjacent pushbutton. Operative only when PSU ON/OFF membrane switch is on.', NULL, 'medium', JSON_ARRAY('lighting','psu','reading')),
(@system_id, 'What auto-logic causes the NO SMOKING signs to illuminate?',
 'When the landing gear selector lever is moved to the DN position, the NO SMOKING signs come on automatically — even if the cockpit NO SMOKING switch is OFF. They go off only when gear is not at DN AND the cockpit switch is OFF.',
 'Mnemonic: NO-SMOKE-GEAR-DN.', 'hard', JSON_ARRAY('lighting','no-smoking','auto')),
(@system_id, 'What happens when the cockpit FASTEN BELTS switch is set to FASTEN BELTS?',
 'FASTEN SEAT BELTS signs (front of cabin + each PSU) illuminate. A low chime sounds through the PA. The lavatory RETURN TO SEAT sign also illuminates.', NULL, 'medium', JSON_ARRAY('lighting','fasten-belts','chime')),
(@system_id, 'What happens to the lavatory fluorescent lights?',
 'Two fluorescent lights are armed by the LAVATORY LTS membrane switch. They activate when the lavatory latch is moved to the OCCUPIED position. The OCCUPIED indicator above the F/A seat also illuminates.',
 'Mnemonic: LAV-OCCUPIED-LATCH.', 'hard', JSON_ARRAY('lighting','lavatory','occupied')),
(@system_id, 'What is the role of the single dimmer control on the C/A panel?',
 'It dims ALL the main cabin lights together — useful for the top-of-descent transition to a night arrival.', NULL, 'medium', JSON_ARRAY('lighting','cabin','dimmer')),
(@system_id, 'How many landing lights are on the Q400 wings, and how are they grouped?',
 'FOUR total — TWO per wing on the leading edge, outboard of each engine nacelle. The OUTBOARD lights are APPROACH lights; the INBOARD lights are FLARE lights (angled DOWN for the flare).',
 'Mnemonic: OUT-APPROACH-IN-FLARE.', 'medium', JSON_ARRAY('lighting','landing','approach','flare')),
(@system_id, 'Where is the taxi light located, and what is the inhibit condition?',
 'On the steerable section of the nose gear (shines in the direction nose gear points). The taxi light will NOT illuminate if the landing gear is not LOCKED DOWN.',
 'Mnemonic: TAXI-LOCK-DOWN.', 'medium', JSON_ARRAY('lighting','taxi','inhibit')),
(@system_id, 'What colours are the position lights, and where are they located?',
 'GREEN at the right wing tip (transparent). RED at the left wing tip (transparent). WHITE at the aft end of the vertical stabiliser bullet fairing.',
 'Mnemonic: GREEN-RIGHT-RED-LEFT-WHITE-AFT.', 'easy', JSON_ARRAY('lighting','position','colour')),
(@system_id, 'How many position lights are at each location, and what is the failover logic?',
 'TWO at each location: a primary and a secondary. POSN switch ON: both illuminate together. After ~1 second, secondaries go off but stay ARMED. If a primary fails, the related armed secondary auto-illuminates.',
 'Mnemonic: PRI-SEC-1-SEC-ARM.', 'hard', JSON_ARRAY('lighting','position','failover')),
(@system_id, 'How many anti-collision lights are installed and where?',
 'TWO: an upper anti-collision light on the bullet fairing and a lower anti-collision light on the fuselage.', NULL, 'medium', JSON_ARRAY('lighting','anti-collision')),
(@system_id, 'Where is the recognition light located and what colour is it?',
 'RED, on the top fuselage centreline, just forward of the wings.', NULL, 'medium', JSON_ARRAY('lighting','recognition')),
(@system_id, 'What does the EMER LIGHTS switch do in each of its three positions?',
 '3-position lever-locked: ON = lights on now (powered from emergency battery packs). ARM = auto-illuminate when normal AC power is lost. OFF = inhibits emergency lights.',
 'Mnemonic: EMER-3-POS-ARM.', 'hard', JSON_ARRAY('lighting','emergency','switch')),
(@system_id, 'What components does the emergency lighting system include?',
 'Ceiling lights, reflective floor markings, locator signs, exit signs, and an egress light at each passenger exit.', NULL, 'medium', JSON_ARRAY('lighting','emergency','components')),
(@system_id, 'TRUE or FALSE — A single position-light bulb failure on the Q400 illuminates a cockpit caution.',
 'FALSE. Position lights have automatic primary→secondary failover. Single bulb failure is silent — secondary takes over, no cockpit caution. Found on the next pre-flight inspection.', NULL, 'hard', JSON_ARRAY('lighting','position','failover')),
(@system_id, 'How many forward passenger door step lights are installed, and on which bus?',
 'FOUR step lights on the risers of the forward passenger door. Powered from the LEFT MAIN bus.', NULL, 'hard', JSON_ARRAY('lighting','door','step')),
(@system_id, 'How many boarding lights are installed, and on which bus?',
 'TWO boarding lights — a lower threshold light and a forward boarding light. Powered from the BATTERY bus.', NULL, 'hard', JSON_ARRAY('lighting','boarding','battery-bus')),
(@system_id, 'How many dome lights are in the forward and aft baggage compartments?',
 'Forward baggage: ONE dome light. Aft baggage: TWO dome lights. Both auto-on when their respective doors are unlocked.',
 'Mnemonic: 1-FWD-2-AFT-BAG.', 'medium', JSON_ARRAY('lighting','baggage','dome')),
(@system_id, 'How are circuit breaker panel lights controlled?',
 'Two white floodlights above each side''s circuit breaker panels. Separate toggle switch per pilot — pilot side switch on the pilot side panel; copilot side switch on the copilot side panel.', NULL, 'medium', JSON_ARRAY('lighting','cb-panel')),
(@system_id, 'What does the W/S WIPER ICE DETECT pushbutton do?',
 'Illuminates a light above the glareshield that shines on the windshield wiper spigot, to allow visual ice detection on the wiper.', NULL, 'medium', JSON_ARRAY('lighting','wiper','ice-detect')),
(@system_id, 'TRUE or FALSE — The Storm/Dome switch position STORM/DOME activates only the storm lights.',
 'FALSE. STORM/DOME activates BOTH storm and dome lights together.', NULL, 'hard', JSON_ARRAY('lighting','storm','dome')),
(@system_id, 'What is the EMER LIGHTS switch ARM behaviour?',
 'ARM = lights stay off in normal operation. If normal AC power is lost, the emergency lights auto-illuminate from emergency battery packs without any crew action. ARM is the standard flight setting.', NULL, 'hard', JSON_ARRAY('lighting','emergency','arm')),
(@system_id, 'What lighting source does the cabin emergency egress chain use when AC is lost?',
 'Emergency battery packs. They power ceiling lights, reflective floor markings, locator signs, exit signs, and the egress light at each passenger exit. The system is designed to function without AC for the time required to evacuate.', NULL, 'hard', JSON_ARRAY('lighting','emergency','battery')),
(@system_id, 'How many utility lights are on the flight deck, and where?',
 'TWO swivel-ball utility lights on the flight deck ceiling, one above each pilot. Plus ONE observer''s utility light on the overhead ceiling at the flight deck threshold.', NULL, 'medium', JSON_ARRAY('lighting','utility')),
(@system_id, 'Where is the F/A control panel located, and what membrane switches drive cabin lighting?',
 'Forward cabin attendant panel near the boarding area. Membrane switches: CABIN OVERHD, CABIN SIDEWALL, DIM OVERHD, DIM SIDEWALL, BOARDING, LAVATORY LTS, AIRSTAIR DOOR LTS, PSU ON/OFF, PSU TEST, plus a single cabin dimmer.', NULL, 'hard', JSON_ARRAY('lighting','f-a','panel')),
(@system_id, 'What does the wardrobe light use, and how is it activated?',
 'Incandescent ceiling light in the wardrobe interior. Activated by a door switch — comes on when the wardrobe door is opened.', NULL, 'medium', JSON_ARRAY('lighting','wardrobe')),
(@system_id, 'TRUE or FALSE — The Q400 dome light requires the BATTERY MASTER switch to be ON.',
 'FALSE. Dome light is on the BATTERY PWR bus and operates without BATTERY MASTER. Useful for pre-flight inspection before battery master is selected.', NULL, 'hard', JSON_ARRAY('lighting','dome','battery-master')),
(@system_id, 'What information sign also illuminates with the FASTEN BELTS sign and where?',
 'The lavatory RETURN TO SEAT sign also illuminates when FASTEN BELTS is selected. A low tone chime sounds over the PA simultaneously.', NULL, 'medium', JSON_ARRAY('lighting','signs','lavatory'));

SELECT COUNT(*) AS flashcards_inserted FROM flashcards WHERE system_id = @system_id;
