-- =============================================================================
-- AviatorTutor — Phase 9: ATA 30 Ice & Rain Protection — 36 flashcards.
-- =============================================================================

SET @system_id := (SELECT id FROM systems WHERE slug = 'ice-rain' LIMIT 1);
SELECT @system_id AS resolved_system_id;

DELETE FROM flashcards WHERE system_id = @system_id;

INSERT INTO flashcards (system_id, front, back, hint, difficulty, tags) VALUES
(@system_id, 'Is the Q400 approved for flight into known icing?',
 'YES. Q400 is approved for flight into KNOWN ICING conditions.', NULL, 'easy', JSON_ARRAY('ice','approval')),
(@system_id, 'How many Ice Detector Probes (IDPs) does the Q400 have, and where?',
 'TWO IDPs — one on the left and one on the right side of the front fuselage. Operate automatically with 115 VAC available — NO flight-deck control switch.',
 'Mnemonic: 2-IDP-AUTO.', 'medium', JSON_ARRAY('ice','idp','detection')),
(@system_id, 'What ice thickness triggers the IDP detection?',
 'More than 0.5 mm of ice on the probe.',
 'Mnemonic: 0.5-MM-ICE.', 'medium', JSON_ARRAY('ice','idp','threshold')),
(@system_id, 'When does the ICE DETECT FAIL caution illuminate?',
 'When BOTH ice detector probes fail. A single probe failure is silent — the system is redundant.',
 'Mnemonic: BOTH-IDPS-FAIL-CAUTION.', 'hard', JSON_ARRAY('ice','idp','fail')),
(@system_id, 'Which surfaces have pneumatic de-icing boots?',
 'Wing leading edges (extension + outboard + outboard centre + inboard centre + inboard sections), horizontal stabilizer (inboard + outboard), vertical stabilizer (upper + lower), and the nacelle inlet lips.',
 'Mnemonic: BOOTS-LIPS-WINGS-TAIL.', 'medium', JSON_ARRAY('ice','boots','locations')),
(@system_id, 'What surfaces have ELECTRIC anti-icing?',
 'Pilot/copilot/standby pitot-static probes, left/right AOA vanes, left/right engine intake flanges, both windshields, pilot side window.',
 'Mnemonic: ELEC-PROBES-WINDOWS-INTAKE-AOA.', 'medium', JSON_ARRAY('ice','electric','locations')),
(@system_id, 'What is the regulated boot pressure on the Q400?',
 '18 PSI ± 3 PSI. Shown on the DEICE PRESS gauge on the copilot side panel.',
 'Mnemonic: 18-PSI-BOOTS-15-LIGHT.', 'medium', JSON_ARRAY('ice','boots','pressure')),
(@system_id, 'At what boot pressure does the green BOOT INFLATION advisory light illuminate?',
 'When boot pressure is 15 PSI or above. Different from the 18 PSI regulated normal pressure.', NULL, 'medium', JSON_ARRAY('ice','boots','indication')),
(@system_id, 'Where does boot air come from, and is it dependent on the BLEED switch position?',
 'Bleed port of each engine. The boot air supply is INDEPENDENT of the BLEED control switch — even with BLEED OFF, boots will still inflate.',
 'Mnemonic: BLEED-INDEPENDENT.', 'hard', JSON_ARRAY('ice','boots','bleed')),
(@system_id, 'What does the BOOT AIR switch do?',
 'NORM = isolator valve open, both left and right systems connected. ISO = isolator valve closed, sides isolated for individual pressure check or to isolate a leak.', NULL, 'medium', JSON_ARRAY('ice','boots','iso')),
(@system_id, 'What is the cycle timing for AIRFRAME MODE SELECT SLOW vs FAST?',
 'SLOW: 3-minute cycle, 144-second dwell between end-of-cycle and restart. FAST: 1-minute cycle, 24-second dwell.',
 'Mnemonic: SLOW-3-MIN-FAST-1-MIN.', 'medium', JSON_ARRAY('ice','boots','cycle')),
(@system_id, 'How many boot combinations are in one cycle, and how long does each combination inflate?',
 'SIX combinations per cycle. Each combination inflates for 6 seconds.',
 'Mnemonic: 6-COMB-6-SEC.', 'medium', JSON_ARRAY('ice','boots','sequence')),
(@system_id, 'What does AIRFRAME MODE SELECT MANUAL position do?',
 'DDVs (Dual Distributing Valves) and check-valve heaters power on permanently. Boot inflation requires manual selection via the AIRFRAME MANUAL SELECT 6-detent rotary.', NULL, 'hard', JSON_ARRAY('ice','boots','manual')),
(@system_id, 'When the TMU fails (DE-ICE TIMER caution), how do you recover boot operation?',
 'Set AIRFRAME MODE SELECT to MANUAL. Use AIRFRAME MANUAL SELECT 6-detent rotary to fire each pair sequentially. Hold each detent until the corresponding pair of green BOOT INFLATION lights illuminate. Minimum 24-second dwell before re-firing the same pair.', NULL, 'hard', JSON_ARRAY('ice','tmu','manual')),
(@system_id, 'What other systems share the regulated boot air?',
 'Forward passenger door seal, aft baggage door seal, AND the AFT safety-valve ejector for the pressurization system.', NULL, 'hard', JSON_ARRAY('ice','boots','shared')),
(@system_id, 'How many propeller blades are on each Q400 prop, and what percentage of each blade is heated?',
 'SIX blades per propeller. Electric heating element covers 70% of each blade leading edge.', NULL, 'medium', JSON_ARRAY('ice','prop','blades')),
(@system_id, 'What controls the propeller heater cycle?',
 'TMCU (Timer Monitor Control Unit). One per propeller. Cycles based on TAT.', NULL, 'medium', JSON_ARRAY('ice','prop','tmcu')),
(@system_id, 'What three conditions must be met for the propeller heaters to cycle?',
 '(1) PROP switch ON. (2) TAT ≤ +5°C. (3) NP > 400 RPM. All three required.',
 'Mnemonic: TAT-5-NP-400.', 'hard', JSON_ARRAY('ice','prop','conditions')),
(@system_id, 'How are the two propellers heated relative to each other?',
 'They alternate. One propeller is heated, then the other. This balances the electrical load on the 115 VAC variable-frequency bus. The PROPS advisory light shows which propeller is currently heating.', NULL, 'medium', JSON_ARRAY('ice','prop','load')),
(@system_id, 'What is the PROP TEST sequence?',
 'PROP selector to TEST: each propeller heated for 5 seconds separately. NP must be > 400 RPM (CL at MIN or higher). AC power must be available. Mandatory 30-second cooldown before another TEST can begin.',
 'Mnemonic: 30-SEC-PROP-TEST-COOL.', 'hard', JSON_ARRAY('ice','prop','test')),
(@system_id, 'Why does the PROP TEST have a 30-second cooldown?',
 'To prevent overheating of the blade heater elements. Trying to retest within 30 sec will not start.', NULL, 'medium', JSON_ARRAY('ice','prop','cooldown')),
(@system_id, 'What is the prop heater cycle time at TAT between -7°C and +5°C?',
 '12 seconds ON / 78 seconds OFF (default mode).', NULL, 'hard', JSON_ARRAY('ice','prop','cycle')),
(@system_id, 'What is the prop heater cycle time at TAT ≤ -22°C?',
 '92 seconds ON / 108 seconds OFF (cold mode — longest heat).', NULL, 'hard', JSON_ARRAY('ice','prop','cold')),
(@system_id, 'Why might prop heaters not cycle even when SAT is below +5°C?',
 'Because the trigger is TAT, not SAT. At high airspeed, TAT can be many degrees warmer than SAT. With visible ice accumulation, however, the system functions regardless of indicated SAT.', NULL, 'hard', JSON_ARRAY('ice','prop','tat-sat')),
(@system_id, 'What does setting REF SPEEDS to INCR do?',
 'Tells the SPS (Stall Protection System) to adjust stall margin for icing conditions. The [INCR REF SPEED] message appears in white below ICE DETECTED on the ED.',
 'Mnemonic: INCR-FOR-ICING.', 'medium', JSON_ARRAY('ice','sps','ref-speed')),
(@system_id, 'When does the ICE DETECTED message appear, and what does it look like?',
 'Appears when one or both IDPs detect more than 0.5 mm of ice. White, REVERSE VIDEO, FLASHING for the first 5 seconds. Then transitions to normal video (steady) if REF SPEEDS is set to INCR.', NULL, 'medium', JSON_ARRAY('ice','ed','indication')),
(@system_id, 'What conditions enable the DDV and check valve heaters to come on automatically?',
 'AIRFRAME MODE SELECT at OFF, SLOW, or FAST. SAT < +5°C. TMU temperature monitor parameter not failed. Under MANUAL mode, valve heaters are permanently ON.', NULL, 'hard', JSON_ARRAY('ice','ddv','heaters')),
(@system_id, 'When does the DE-ICE PRESS caution illuminate?',
 'Main de-ice pressure on either side < 15 PSI; OR boot pressure fails to reach 15 PSI after the DDV opens; OR boot pressure stays at 15 PSI after the DDV closes (stuck-open valve).', NULL, 'hard', JSON_ARRAY('ice','press','caution')),
(@system_id, 'What does DE-ICE TIMER caution indicate, and how is recovery done?',
 'TMU failure: auto sequencer / logic / input disagreement. Recovery: AIRFRAME MODE SELECT to MANUAL, then use AIRFRAME MANUAL SELECT 6-detent rotary with 24-sec dwell minimum between same-pair re-firings.', NULL, 'hard', JSON_ARRAY('ice','timer','manual')),
(@system_id, 'In holding or descent, how do you maintain boot pressure if it slumps below 15 PSI?',
 'Advance the POWER levers to raise NL — engine bleed scales with NL. Higher NL → higher bleed pressure → boots back to 18 PSI.',
 'Mnemonic: NL-FOR-PRESSURE.', 'hard', JSON_ARRAY('ice','boots','nl')),
(@system_id, 'What are the windshield wiper speeds on the Q400?',
 'PARK / OFF / LOW / HIGH. Plus an alternate pilot-side pushbutton (guarded) — pushed in drives pilot wiper at HIGH.', NULL, 'medium', JSON_ARRAY('ice','wiper','speeds')),
(@system_id, 'What does the ENGINE INTAKE OPN HTR switch do?',
 'OPN HTR = Open Heater. Energises the heating elements on the engine intake flange to prevent ice formation around the intake. One switch per engine.', NULL, 'medium', JSON_ARRAY('ice','intake','heat')),
(@system_id, 'What is the icing-entry crew chant on the Q400?',
 'REF SPEEDS INCR · PROPS ON · AIRFRAME FAST (or SLOW) · ENGINE INTAKE heaters ON · monitor DEICE PRESS.', NULL, 'hard', JSON_ARRAY('ice','procedure','chant')),
(@system_id, 'TRUE or FALSE — Boot air will not inflate the boots if the BLEED switch is OFF.',
 'FALSE. Boot air is taken directly from each engine''s bleed port and is INDEPENDENT of the BLEED control switch. Boots inflate regardless of BLEED switch position.', NULL, 'hard', JSON_ARRAY('ice','boots','bleed')),
(@system_id, 'TRUE or FALSE — Single IDP failure illuminates the ICE DETECT FAIL caution.',
 'FALSE. The system is redundant. ICE DETECT FAIL only illuminates when BOTH probes fail.', NULL, 'medium', JSON_ARRAY('ice','idp','redundancy')),
(@system_id, 'What is the alternate pilot wiper pushbutton, and when is it used?',
 'A guarded pushbutton (alternate action). Pushed in: pilot windshield wiper operates at HIGH speed (independent of normal wiper control). Used if the normal wiper control fails.', NULL, 'hard', JSON_ARRAY('ice','wiper','alternate'));

SELECT COUNT(*) AS flashcards_inserted FROM flashcards WHERE system_id = @system_id;
