-- =============================================================================
-- AviatorTutor — Phase 13: ATA 34 Navigation — 36 flashcards.
-- =============================================================================

SET @system_id := (SELECT id FROM systems WHERE slug = 'navigation' LIMIT 1);
SELECT @system_id AS resolved_system_id;

DELETE FROM flashcards WHERE system_id = @system_id;

INSERT INTO flashcards (system_id, front, back, hint, difficulty, tags) VALUES
(@system_id, 'How many VHF NAV receivers does the Q400 have, and what do they cover?',
 'TWO. Each handles VOR + Localizer + Glideslope + DME + integral Marker Beacons.',
 'Mnemonic: VHF-NAV-DUAL.', 'medium', JSON_ARRAY('navigation','vhf')),
(@system_id, 'What is the VOR frequency range and channel spacing?',
 '108.00 to 117.95 MHz with 50 kHz EVEN spacing.',
 'Mnemonic: VOR-EVEN-LOC-ODD.', 'hard', JSON_ARRAY('navigation','vor','frequency')),
(@system_id, 'What is the Localizer frequency range and channel spacing?',
 '108.10 to 111.95 MHz with 50 kHz ODD spacing. Glideslope auto-paired.', NULL, 'hard', JSON_ARRAY('navigation','loc','frequency')),
(@system_id, 'What colours and labels are used on the EFIS marker beacon indicators?',
 'OUT (blue) at outer marker. MID (amber) at middle marker. INN (white) at inner/airway marker.',
 'Mnemonic: OUT-BLUE-MID-AMBER-INN-WHITE.', 'medium', JSON_ARRAY('navigation','marker','colour')),
(@system_id, 'How is marker beacon sensitivity selected, and from where?',
 'HI or LO selectable from the ARCDU on the centre console.', NULL, 'medium', JSON_ARRAY('navigation','marker','sensitivity')),
(@system_id, 'How many DME units are installed, and how are they channeled?',
 'TWO DME units (DME1, DME2). Each is dual-channel — Channel 1 + Channel 2. Each channel can independently track a DME.', NULL, 'medium', JSON_ARRAY('navigation','dme')),
(@system_id, 'How are DME signals distributed between pilot and copilot EFIS?',
 'Pilot EFIS uses DME1. Copilot EFIS uses DME2. Each side gets VOR1 + VOR2 distance via Channel 1 + Channel 2 of its own DME unit.',
 'Mnemonic: DME-CROSS-USE.', 'hard', JSON_ARRAY('navigation','dme','cross')),
(@system_id, 'What happens to DME data if one DME unit fails?',
 'Both EFIS sides automatically use the remaining DME receiver. Silent auto-failover; no crew action required.', NULL, 'hard', JSON_ARRAY('navigation','dme','failover')),
(@system_id, 'What does DME HOLD do?',
 'Keeps the current DME station active when a new VOR/LOC frequency is selected. Useful for maintaining distance from a station while tuning a new approach.', NULL, 'medium', JSON_ARRAY('navigation','dme','hold')),
(@system_id, 'How many ADF receivers are on the Q400, and what 4 modes do they have?',
 'TWO ADF receivers. Modes: ADF, ANT, BFO, TEST.',
 'Mnemonic: 4-MODE-ADF.', 'medium', JSON_ARRAY('navigation','adf','modes')),
(@system_id, 'In what conditions does the ADF bearing pointer park at 90°?',
 'In ANT mode (loop disabled, audio only). In TEST mode (confidence test). When signal/frequency is invalid in ADF mode.',
 'Mnemonic: ADF-PARKS-90.', 'hard', JSON_ARRAY('navigation','adf','park')),
(@system_id, 'What audio cue indicates a valid station in ADF BFO mode?',
 'Intermittent 1000 Hz tone. BFO is used for non-modulated CW signals.',
 'Mnemonic: BFO-1000-HZ.', 'hard', JSON_ARRAY('navigation','adf','bfo')),
(@system_id, 'What positions does the EFCP Bearing 1 selector have?',
 '5-position rotary: OFF / VOR1 / ADF1 / FMS1 / AUX1. (Bearing 2 selects from VOR2/ADF2/FMS2/AUX2.)',
 'Mnemonic: BRG-5-POS.', 'medium', JSON_ARRAY('navigation','bearing','selector')),
(@system_id, 'What does the bearing pointer do for each source: VOR, ADF, FMS, AUX?',
 'VOR: removed if frequency invalid or ILS frequency selected. ADF: parks at 90° if signal/frequency invalid. FMS: points to next waypoint. AUX: requires optional MLS equipment.', NULL, 'hard', JSON_ARRAY('navigation','bearing','behaviour')),
(@system_id, 'What does the EFCP FORMAT pushbutton do — Push 1, Push 2/3, Push and Hold 1 sec?',
 'Push 1: ARC mode with VOR/ILS source. Push 2 or 3: ARC with FMS source (default). Push and HOLD 1 SECOND: FULL mode, 360° north-up, A/C centred.',
 'Mnemonic: FORMAT-1-SEC-FULL.', 'hard', JSON_ARRAY('navigation','format')),
(@system_id, 'At what range does TCAS show continuous traffic on the EFIS?',
 '40 nautical miles or less. Above 40 nm, traffic is not continuously displayed (range-dependent).',
 'Mnemonic: TCAS-40-NM.', 'medium', JSON_ARRAY('navigation','tcas','range')),
(@system_id, 'What happens to TCAS mode if the EFCP malfunctions?',
 'TCAS automatically goes to AUTO mode. No crew action required.', NULL, 'hard', JSON_ARRAY('navigation','tcas','auto')),
(@system_id, 'What does the EFCP WX/TERR pushbutton cycle through?',
 'Weather radar (default) → EGPWS terrain → off. Cycle through with each push.', NULL, 'medium', JSON_ARRAY('navigation','wx','terr')),
(@system_id, 'What ranges does the EFCP RANGE selector offer, and what is the default?',
 '6 positions: 10 / 20 / 40 / 80 / 160 / 240 nm. Default 40 nm at NAV initialisation.',
 'Mnemonic: RANGE-6-DEFAULT-40.', 'medium', JSON_ARRAY('navigation','range')),
(@system_id, 'What does the EFCP DATA pushbutton offer?',
 '10 nearest nav aids → 10 nearest airports → both → off (default). 4-cycle pushbutton. Push and HOLD 1 sec removes all options.', NULL, 'medium', JSON_ARRAY('navigation','data')),
(@system_id, 'What is the AHRS architecture on the Q400?',
 '2 AHRS Control Panels (AHCP1, AHCP2), 2 AHRUs, 2 remote flux valves (FDU1, FDU2), 2 remote memory modules (RMM1, RMM2).',
 'Mnemonic: 2-AHRU-2-ADC-2-FLUX-2-RMM.', 'hard', JSON_ARRAY('navigation','ahrs')),
(@system_id, 'What does the RMM (Remote Memory Module) do?',
 'Stores AHRU calibration so the unit can realign quickly after power loss. One per AHRU.', NULL, 'hard', JSON_ARRAY('navigation','rmm')),
(@system_id, 'What sensors does the AHRU use to compute attitude and heading?',
 'Vertical and directional gyros + accelerometers. Measures rates of aircraft movement.', NULL, 'medium', JSON_ARRAY('navigation','ahru','sensors')),
(@system_id, 'What systems does the AHRU output to?',
 'EIS (EADI/EHSI/ALT/IVSI), AFCS, SPS. Plus FDR via IFC, FDPS, WXR, GPWS, TCAS, CDS.', NULL, 'hard', JSON_ARRAY('navigation','ahru','outputs')),
(@system_id, 'How is cross-side AHRS source selected, and how is cross-side selection indicated?',
 'EFIS ATT/HDG SOURCE selector NORM / 1 / 2. Cross-side selection illuminates a YELLOW indication on the PFD as a continuous reminder.', NULL, 'hard', JSON_ARRAY('navigation','ahrs','cross')),
(@system_id, 'How many Air Data Computers are on the Q400?',
 'TWO ADCs. Cross-side via ADC SOURCE selector NORM / 1 / 2. Yellow indication on PFD when cross-side.', NULL, 'medium', JSON_ARRAY('navigation','adc')),
(@system_id, 'What is the Marker Beacon receiver — separate or integral?',
 'INTEGRAL to the dual VOR/LOC navigation receivers. Not a separate unit.', NULL, 'medium', JSON_ARRAY('navigation','marker','integral')),
(@system_id, 'In ADF ANT mode, why is the loop antenna disabled?',
 'To give higher audio sensitivity for station identification. Without the loop, only the audio path is active.', NULL, 'hard', JSON_ARRAY('navigation','adf','ant')),
(@system_id, 'TRUE or FALSE — When the FMS is operating, the bearing pointer set to FMS1 points to your destination airport.',
 'FALSE. FMS bearing pointer points to the NEXT WAYPOINT — not the destination. As waypoints are sequenced, the pointer updates.',
 'Mnemonic: WPT-FMS-PT.', 'hard', JSON_ARRAY('navigation','fms','waypoint')),
(@system_id, 'What does the FORMAT pushbutton FULL mode show?',
 '360° north-up display, aircraft-centred. Optional navigation data may be displayed via the DATA pushbutton, but NOT the weather radar image (WX disabled in FULL).', NULL, 'hard', JSON_ARRAY('navigation','format','full')),
(@system_id, 'What does the EGPWS TAD inhibit and what does TCF do?',
 'TAD = Terrain Awareness Display. TCF = Terrain Clearance Floor. The TERRAIN INHIBIT switchlight (white, alternate) inhibits BOTH TAD AND TCF. Other GPWS modes remain active.', NULL, 'hard', JSON_ARRAY('navigation','egpws','tad')),
(@system_id, 'What does GPWS FLAP OVERRIDE inhibit?',
 'GPWS mode 4B ONLY. Permits 0° flap landings without aural warning. All other modes remain active.', NULL, 'hard', JSON_ARRAY('navigation','gpws','flap-override')),
(@system_id, 'What positions are on the GPWS LANDING FLAP SELECT switch?',
 '10 / 15 / 35. Rotary action with green segment indicators. TOO LOW FLAPS aural sounds at AGL <200 ft if flaps are less than the LFSS setting.', NULL, 'medium', JSON_ARRAY('navigation','gpws','lfss')),
(@system_id, 'TRUE or FALSE — In FULL format mode the weather radar image is displayed.',
 'FALSE. Weather radar is NOT displayed in FULL format mode. Only ARC mode shows weather radar.', NULL, 'hard', JSON_ARRAY('navigation','format','wx')),
(@system_id, 'What are the EFIS DME parameters displayed?',
 'Slant Range, Ground Speed, DME HOLD indication.', NULL, 'medium', JSON_ARRAY('navigation','dme','params')),
(@system_id, 'What pushbuttons are on the EFCP, and what do each do?',
 'BEARING 1 + BEARING 2 selectors (rotary, 5-position). FORMAT (push to cycle ARC; push+hold 1 sec FULL). TCAS (continuous / auto). WX/TERR (cycle WX/terrain/off). RANGE selector (rotary, 6-position). DATA pushbutton (cycle nav aids / airports / both / off). PFD/MFD/BRG brightness knobs.', NULL, 'hard', JSON_ARRAY('navigation','efcp','controls'));

SELECT COUNT(*) AS flashcards_inserted FROM flashcards WHERE system_id = @system_id;
