-- =============================================================================
-- AviatorTutor — Phase 17: ATA 71 Powerplant — 36 flashcards.
-- =============================================================================

SET @system_id := (SELECT id FROM systems WHERE slug = 'powerplant' LIMIT 1);
SELECT @system_id AS resolved_system_id;

DELETE FROM flashcards WHERE system_id = @system_id;

INSERT INTO flashcards (system_id, front, back, hint, difficulty, tags) VALUES
(@system_id, 'How many engines does the Q400 have, and what model?',
 'TWO Pratt & Whitney PW150A turboprop engines. Drive Dowty R408 6-blade composite propellers via reduction gearbox.',
 'Mnemonic: PW150A-2-ENG.', 'easy', JSON_ARRAY('powerplant','engines')),
(@system_id, 'What is normal takeoff SHP and MTOP UPTRIM SHP?',
 'Normal takeoff: 4,580 SHP per engine. MTOP UPTRIM: 5,071 SHP per engine for brief period (engine failure during takeoff). Emergency = 1.25 × MTOP.',
 'Mnemonic: 4580-NTOP-5071-MTOP.', 'medium', JSON_ARRAY('powerplant','shp')),
(@system_id, 'What type is the NL compressor, and what type is the NH compressor?',
 'NL = AXIAL (1st stage low pressure). NH = CENTRIFUGAL (2nd stage high pressure). NH drives the accessory gearbox.',
 'Mnemonic: NL-AXIAL-NH-CENTRIFUGAL.', 'medium', JSON_ARRAY('powerplant','compressor')),
(@system_id, 'How many turbines does the PW150A have, and how are they arranged?',
 'FOUR turbine stages total: single-stage NL turbine (drives NL compressor), single-stage NH turbine (drives NH compressor), and a TWO-STAGE power turbine on an independent third shaft (drives reduction gearbox to propeller).', NULL, 'hard', JSON_ARRAY('powerplant','turbine')),
(@system_id, 'What does the accessory gearbox drive, and what drives the accessory gearbox?',
 'Driven by the NH compressor (high pressure rotor). Operates: Oil Pressure + Scavenge Pumps, HP Fuel Pump, PMA (Permanent Magnet Alternator), DC Starter/Generator.', NULL, 'hard', JSON_ARRAY('powerplant','accessory-gearbox')),
(@system_id, 'What does the Power Lever (PLA) control in the forward range vs beta/reverse?',
 'Forward range: drives FADEC for engine power. Beta/reverse range (PLA below Flight Idle): drives propeller blade angle directly via PEC closed-loop blade angle control.',
 'Mnemonic: PLA-FADEC-FORWARD-PEC-BETA.', 'hard', JSON_ARRAY('powerplant','pla')),
(@system_id, 'What does the Condition Lever (CL) control?',
 'Drives PEC for: propeller RPM in forward thrust range; engine power rating selection; manual propeller feathering; fuel on/off control for engine start (START & FEATHER) and shutdown (FUEL OFF).',
 'Mnemonic: CL-PEC-RPM-FUEL.', 'medium', JSON_ARRAY('powerplant','cl')),
(@system_id, 'What are the five core engine ratings displayed on the Engine Display?',
 'NTOP (Normal Takeoff), MTOP (Max Takeoff), MCP (Max Continuous Power), MCL (Max Climb), MCR (Max Cruise). Plus RDC TOP variant when reduced takeoff power is selected.',
 'Mnemonic: 5-RATINGS-CORE.', 'hard', JSON_ARRAY('powerplant','ratings')),
(@system_id, 'NTOP rating conditions on the ED?',
 'CL at MAX/1020 AND BLEED selection at MIN/OFF or ON/MIN. Displayed as NTOP on the ED.', NULL, 'hard', JSON_ARRAY('powerplant','ntop')),
(@system_id, 'MTOP rating conditions on the ED?',
 'CL at MAX/1020 AND MTOP pushbutton ON (or auto via UPTRIM on engine failure). BLEED MIN/OFF or ON/MIN. 4,580 SHP normal, 5,071 SHP UPTRIM.', NULL, 'hard', JSON_ARRAY('powerplant','mtop')),
(@system_id, 'MCP rating conditions on the ED?',
 'CL at MAX/1020 AND BLEED selection at ON/NORM or MAX. The bleed load forces the rating to MCP (Max Continuous Power) instead of NTOP/MTOP.', NULL, 'hard', JSON_ARRAY('powerplant','mcp')),
(@system_id, 'MCL rating conditions on the ED?',
 'CL at MIN/850 AND MCL pushbutton selected. The ED displays MCL with 900 RPM (not 850).', NULL, 'hard', JSON_ARRAY('powerplant','mcl')),
(@system_id, 'MCR rating conditions on the ED?',
 'CL at 900 AND MCR pushbutton selected. The ED displays MCR with 850 RPM (not 900).', NULL, 'hard', JSON_ARRAY('powerplant','mcr')),
(@system_id, 'What does the RDC TOP TRQ DEC pushbutton do?',
 'Reduces NTOP requested power in steps of 2% per push, to a maximum reduction of 10%. CANNOT be activated while in MTOP or MCP rating. The RDC TOP TRQ RESET pushbutton restores normal takeoff power.',
 'Mnemonic: RDC-TOP-2-10.', 'hard', JSON_ARRAY('powerplant','rdc-top')),
(@system_id, 'What is the RDC NP LDG procedure?',
 '(1) Power Levers between Flight Idle and ~50% rating. (2) Condition Lever at MIN/850. (3) Push RDC NP LDG pushbutton. (4) Within 15 seconds, advance Condition Lever to MAX/1020. NP remains at 850 RPM. ED indicates REDUCED NP LANDING.',
 'Mnemonic: RDC-NP-LDG-15-65.', 'hard', JSON_ARRAY('powerplant','rdc-np')),
(@system_id, 'What cancels RDC NP LDG mode?',
 'PLA ≥ 65 degrees, OR pushing the RDC NP LDG button again. Also: if CL not advanced to MAX/1020 within 15 seconds of the original push, the mode auto-cancels.', NULL, 'medium', JSON_ARRAY('powerplant','rdc-np','cancel')),
(@system_id, 'What does the EVENT MARKER pushbutton do?',
 'Places a bookmark in the Engine Monitoring System (EMS). Stores a data snapshot + data trace covering 2 MINUTES before the event AND 1 MINUTE after.',
 'Mnemonic: EVENT-2-1.', 'medium', JSON_ARRAY('powerplant','event-marker')),
(@system_id, 'What is the PMA, and at what NH threshold is it active?',
 'Permanent Magnet Alternator. Mounted on accessory gearbox. PRIMARY electrical source for engine control system. Independent coils provide power to individual FADEC channels. Active when NH > 20% MINIMUM. Below NH 20% the aeroplane essential power buses provide alternate electrical power to FADEC.',
 'Mnemonic: PMA-NH-20.', 'hard', JSON_ARRAY('powerplant','pma')),
(@system_id, 'What are HBOVs and how many are on each engine?',
 'Handling Bleed-Off Valves. TWO per engine: one LP + one HP. Bleed engine air from main gas path for increased SURGE MARGIN during starting, steady state, and transient operation. FADEC controls automatically — no crew action.',
 'Mnemonic: 2-HBOV-LP-HP.', 'medium', JSON_ARRAY('powerplant','hbov')),
(@system_id, 'When are bypass doors opened?',
 'Open in: ICING conditions, HEAVY PRECIPITATION, BIRD activity, CONTAMINATED RUNWAYS. Manual selection via switchlights on the ICE PROTECTION panel — does NOT auto-open.',
 'Mnemonic: BYPASS-ICING-PRECIP-BIRD-CONTAM.', 'medium', JSON_ARRAY('powerplant','bypass')),
(@system_id, 'What parameters does the Engine Display (ED) show from the FADEC?',
 'TRQ (Torque %, 0-199 in 1% increments), PROP (Prop speed RPM), NH (% of max), ITT (Indicated Turbine Temp °C), NL (% of max), Fuel Flow (hundreds of kg/hr), dual Oil temp + pressure (analog/digital), Engine Rating Mode annunciation (green: NTOP/MTOP/MCP/MCL/MCR/RDC TOP).', NULL, 'medium', JSON_ARRAY('powerplant','ed')),
(@system_id, 'What is the normal engine shutdown procedure, and what does it test?',
 'Move CL to FUEL OFF. The Engine System tests the NH overspeed (O/S) protection circuitry by USING IT to shut down the engine. Every normal shutdown is also a test of the OS protection.',
 'Mnemonic: FUEL-OFF-TESTS-OS.', 'hard', JSON_ARRAY('powerplant','shutdown')),
(@system_id, 'What is the engine fire shutdown path, and how does it differ from normal shutdown?',
 'Fire handle path: PULL FUEL/HYD OFF handle on Fire Protection Panel energizes (closed) a DEDICATED fuel shutoff switch in the FMU (Fuel Metering Unit). Different path from CL FUEL OFF, which goes through the engine system test. Both achieve fuel cutoff via different components.', NULL, 'hard', JSON_ARRAY('powerplant','fire-shutdown')),
(@system_id, 'At what blade angle do the PROPELLER GROUND RANGE lights illuminate?',
 '10 DEGREES blade angle and below. Confirms ground beta operation. Different from the 16° flight fine stop in Phase 16 — the GROUND RANGE light is at 10°, well below the 16° hyd hard stop.',
 'Mnemonic: 10-DEG-GROUND-RANGE.', 'hard', JSON_ARRAY('powerplant','ground-range')),
(@system_id, 'What is the PLA position for IDLE in the forward range?',
 'Approximately 35°. The PLA-vs-power curve is non-linear: small movements at low PLA produce small power changes; large movements at high PLA produce proportionally larger power changes.', NULL, 'hard', JSON_ARRAY('powerplant','pla','idle')),
(@system_id, 'What PLA values correspond to NTOP, MCR, MCL, MTOP, and overtravel?',
 'IDLE ~35°. MCR 77.5°. NTOP 80°. MCL 82.5°. MTOP 95°. O/T (overtravel) 100°. Emergency rating = 1.25 × MTOP.', NULL, 'hard', JSON_ARRAY('powerplant','pla','ratings')),
(@system_id, 'TRUE or FALSE — The PMA powers the FADEC during engine start.',
 'FALSE. PMA is INACTIVE below NH 20%. During engine start, the aeroplane essential power buses provide electrical power to the FADEC. PMA takes over when NH passes 20%.', NULL, 'hard', JSON_ARRAY('powerplant','pma','start')),
(@system_id, 'What does UPTRIM mean in the Q400 powerplant context?',
 'An automatic power increase commanded to the operating engine''s FADEC when an engine failure is detected during takeoff (per Phase 16 autofeather). UPTRIM raises max power from 4,580 SHP NTOP to 5,071 SHP MTOP automatically.', NULL, 'hard', JSON_ARRAY('powerplant','uptrim')),
(@system_id, 'TRUE or FALSE — Bypass doors open automatically when icing is detected.',
 'FALSE. Bypass doors are MANUALLY selected via switchlights on the ICE PROTECTION panel. Crew opens them in icing, heavy precipitation, bird activity, or contaminated runway operations.', NULL, 'medium', JSON_ARRAY('powerplant','bypass','manual')),
(@system_id, 'What does Bleed display state YELLOW vs WHITE indicate on the ED?',
 'BLEED in WHITE: bleed selected MIN with NTOP rating, OR bleed forced MCP rating. BLEED in YELLOW: bleed selection NORM/MAX has forced NTOP rating to change to MCP — informational warning of rating change.', NULL, 'hard', JSON_ARRAY('powerplant','bleed','display')),
(@system_id, 'What does the dual analog/digital oil display on the ED show?',
 'Engine oil temperature (in degrees Celsius) and engine oil pressure (in PSI). Both are dual split analog + digital format for quick scan and precise readout.', NULL, 'medium', JSON_ARRAY('powerplant','oil')),
(@system_id, 'TRUE or FALSE — RDC TOP TRQ DEC can be activated while in MTOP rating.',
 'FALSE. RDC TOP TRQ DEC pushbutton CANNOT be activated while in MTOP or MCP rating. Only in NTOP. Reduces NTOP power 2% per push, max 10%.', NULL, 'hard', JSON_ARRAY('powerplant','rdc-top','restriction')),
(@system_id, 'What CL position is used for engine start?',
 'START & FEATHER position. The propeller is feathered for safe ground operations during start. After NH builds, CL moves to MIN/850 for normal idle.', NULL, 'medium', JSON_ARRAY('powerplant','start','cl')),
(@system_id, 'TRUE or FALSE — When the BLEED is at NORM with CL at MAX/1020, the ED displays NTOP.',
 'FALSE. With BLEED at NORM or MAX and CL at 1020, the rating changes to MCP (Max Continuous Power), not NTOP. The bleed load displaces the takeoff rating.', NULL, 'hard', JSON_ARRAY('powerplant','rating','bleed')),
(@system_id, 'What information does the ED display the rating annunciation in, and what colour?',
 'Green colour. Located on the Engine Display, indicates the selected engine rating mode. Possible values: NTOP / MTOP / MCP / MCL / MCR + RDC TOP variant. White dashes if data invalid.', NULL, 'medium', JSON_ARRAY('powerplant','ed','rating')),
(@system_id, 'TRUE or FALSE — The torque bug digital value on the ED is shown in cyan.',
 'TRUE. Torque bug digits are always displayed in CYAN — except when replaced by white dashes if the parameter is no longer valid. 0-199% in 1% increments.', NULL, 'medium', JSON_ARRAY('powerplant','ed','torque-bug'));

SELECT COUNT(*) AS flashcards_inserted FROM flashcards WHERE system_id = @system_id;
