-- =============================================================================
-- AviatorTutor — Phase 11: ATA 32 Landing Gear — 36 flashcards.
-- =============================================================================

SET @system_id := (SELECT id FROM systems WHERE slug = 'landing-gear' LIMIT 1);
SELECT @system_id AS resolved_system_id;

DELETE FROM flashcards WHERE system_id = @system_id;

INSERT INTO flashcards (system_id, front, back, hint, difficulty, tags) VALUES
(@system_id, 'Which hydraulic system powers landing gear retraction/extension?',
 'No.2 hydraulic system. Same system also powers nosewheel steering.',
 'Mnemonic: N2-GEAR-N1-BRAKES.', 'easy', JSON_ARRAY('gear','hydraulic')),
(@system_id, 'Which hydraulic system powers normal anti-skid brakes?',
 'No.1 hydraulic system.', NULL, 'easy', JSON_ARRAY('gear','brakes','hydraulic')),
(@system_id, 'In which direction does the nose gear retract, and the main gears retract?',
 'Nose gear retracts FORWARD into the nose section. Main gears retract AFT into the engine nacelles.',
 'Mnemonic: NOSE-FWD-MAINS-AFT.', 'medium', JSON_ARRAY('gear','retraction','direction')),
(@system_id, 'What is the role of the PSEU?',
 'Proximity Sensor Electronics Unit. Monitors and controls landing gear; supplies WOW + gear up/locked signals to the ASCU and FCECU.', NULL, 'medium', JSON_ARRAY('gear','pseu')),
(@system_id, 'What hydraulically powers the emergency/parking brake?',
 'No.2 hydraulic system, OR the parking brake accumulator if No.2 is unavailable.', NULL, 'medium', JSON_ARRAY('gear','park-brake','hydraulic')),
(@system_id, 'How many brake applications does a fully charged park brake accumulator give?',
 'Approximately 6 applications.',
 'Mnemonic: 6-APP-500-PSI-PARK.', 'hard', JSON_ARRAY('gear','park-brake','accumulator')),
(@system_id, 'What is the minimum park brake accumulator pressure required before engine start?',
 '500 PSI on the PK BRK indicator (PSA on the MFD).', NULL, 'hard', JSON_ARRAY('gear','park-brake','min-pressure')),
(@system_id, 'How is park brake accumulator pressure increased on the ground?',
 '(1) Hand pump in the right main wheel well, OR (2) run the SPU + PTU on AC power.', NULL, 'medium', JSON_ARRAY('gear','park-brake','recharge')),
(@system_id, 'What is the nosewheel deflection range via the Steering Hand Control (tiller)?',
 '±70° either side of centre. Used for low-speed taxi.',
 'Mnemonic: 70-HAND-8-PEDAL-120-CASTER.', 'medium', JSON_ARRAY('gear','steering','tiller')),
(@system_id, 'What is the nosewheel deflection range via the rudder pedals?',
 '±8° either side of centre. Used for high-speed taxi, take-off, and landing roll.', NULL, 'medium', JSON_ARRAY('gear','steering','pedals')),
(@system_id, 'What is the passive caster range of the nosewheel?',
 '±120° either side of centre. No powered steering. Triggered by angle >70°, SCU fault, or STEERING switch OFF. Differential brake/power for direction.', NULL, 'hard', JSON_ARRAY('gear','steering','caster')),
(@system_id, 'What rules apply to nosewheel steering during reverse taxi?',
 'STEERING switch MUST be ON. NO tiller or rudder pedal steering input is allowed. Direction control only via differential braking + power.', NULL, 'hard', JSON_ARRAY('gear','steering','reverse')),
(@system_id, 'What two distinct conditions trigger the NOSE STEERING caution?',
 '(1) SCU detects a fault with STEERING switch ON. (2) Hydraulic pressure detected in the steering system with STEERING switch OFF. NOTE: caution does NOT come on if electrical power is removed from the SCU.', NULL, 'hard', JSON_ARRAY('gear','steering','caution')),
(@system_id, 'What is the most important caution about nosewheel steering with a tow bar connected?',
 'NEVER set the STEERING switch to STEERING with a tow bar connected. Torque from the tow bar can damage the SCU.', NULL, 'medium', JSON_ARRAY('gear','steering','tow')),
(@system_id, 'When does anti-skid arm and modulate brake pressure?',
 'When wheel speed is more than 10 kts (with ANTI SKID switch at ON).',
 'Mnemonic: 10-17-35-BRAKE.', 'medium', JSON_ARRAY('gear','antiskid','arm')),
(@system_id, 'Above what wheel speed is anti-skid self-test prevented?',
 '17 kts wheel speed. The system blocks self-test above this speed to prevent ground/air state confusion.', NULL, 'hard', JSON_ARRAY('gear','antiskid','test')),
(@system_id, 'What is the 5-second brake delay, and at what wheel speed is it cancelled?',
 'After WOW on touchdown, if main wheels have not spun up, the ASCU delays brake pressure by 5 seconds (prevents lock-up). Immediately cancelled when wheel speed exceeds 35 kts.',
 'Mnemonic: 5-SEC-BRAKE-DELAY.', 'hard', JSON_ARRAY('gear','antiskid','delay')),
(@system_id, 'How long do the anti-skid caution lights illuminate during TEST on the ground?',
 '6 seconds, then they extinguish.', NULL, 'medium', JSON_ARRAY('gear','antiskid','test')),
(@system_id, 'How long do the anti-skid caution lights illuminate during TEST in air with gear extended?',
 '3 seconds.', NULL, 'hard', JSON_ARRAY('gear','antiskid','test-air')),
(@system_id, 'What three trigger groups can sound the gear warning tone?',
 '(1) flaps >8.5° + either engine torque <50% + both PLA <RATING detent. (2) both PLA <FLT IDLE +12° + KIAS <156 + RA <1053 ft. (3) one PLA <FLT IDLE +12° + both PLA <RATING detent + HORN not at MUTE + KIAS <156 + RA <1053 ft.', NULL, 'hard', JSON_ARRAY('gear','warning','tone')),
(@system_id, 'Which gear warning tone case may be MUTED, and why?',
 'ONLY case 3 (single-engine failure at low speed). The HORN switch may be set to MUTE in this scenario so the crew can hear FO calls during engine-failure handling. Cases 1 and 2 cannot be muted.',
 'Mnemonic: 3-TONE-GROUPS-MUTE-3.', 'hard', JSON_ARRAY('gear','warning','mute')),
(@system_id, 'What KIAS and RA threshold are used in the gear warning tone logic (cases 2 and 3)?',
 'KIAS < 156. RA < 1053 ft (321 m) if RA is valid.',
 'Mnemonic: 156-KIAS-1053-RA.', 'hard', JSON_ARRAY('gear','warning','threshold')),
(@system_id, 'What three triggers initiate alternate gear extension?',
 '(1) LDG GEAR INOP caution. (2) Landing gear indication failure. (3) Loss of No.2 hydraulic system pressure.', NULL, 'medium', JSON_ARRAY('gear','alternate','triggers')),
(@system_id, 'What is the FIRST step of alternate gear extension?',
 'Set the LANDING GEAR INHIBIT switch (overhead, guarded) to INHIBIT. This isolates all hydraulic pressure from the gear system.',
 'Mnemonic: 3-DOOR-ALT-EXTEND (INHIBIT first).', 'hard', JSON_ARRAY('gear','alternate','inhibit')),
(@system_id, 'What does pulling the MAIN L/G RELEASE handle do?',
 'Releases the main landing gear hydraulic doors and main gear uplocks. Hydraulic gear doors stay open. Main gear free-falls (may not fully extend without further action).', NULL, 'hard', JSON_ARRAY('gear','alternate','main')),
(@system_id, 'What does pulling the NOSE L/G RELEASE handle do?',
 'Releases the nose gear hydraulic doors and the nose gear uplock. Nose gear free-falls; airflow assists to a down-and-locked position.', NULL, 'hard', JSON_ARRAY('gear','alternate','nose')),
(@system_id, 'When and how do you use the alternate extension hand pump?',
 'If the main landing gear has not reached the down-and-locked position after pulling the MAIN L/G RELEASE handle. The hand pump handle is stowed behind the copilot''s seat; insert into the floor socket; pump until the handle is stiff. This drives fluid from the emergency hydraulic reservoir to the auxiliary main landing gear actuators to complete downlock.', NULL, 'hard', JSON_ARRAY('gear','alternate','pump')),
(@system_id, 'What does the ALTERNATE DOWNLOCK VERIFICATION switch do?',
 'Set to AFT activates the alternate downlock verification system. Three green downlock verification lights under the LANDING GEAR ALTERNATE EXTENSION panel in the floor confirm individual gear downlock status.',
 'Mnemonic: 3-GREEN-FLOOR-LIGHTS.', 'hard', JSON_ARRAY('gear','alternate','verification')),
(@system_id, 'After alternate gear extension, what must be done with the two doors?',
 'Both the LANDING GEAR ALTERNATE EXTENSION door (floor) AND the MAIN LANDING GEAR ALTERNATE RELEASE door (overhead) must be left FULLY OPEN. Closing them defeats the alternate path.',
 'Mnemonic: BOTH-DOORS-OPEN-AFTER.', 'hard', JSON_ARRAY('gear','alternate','doors')),
(@system_id, 'What three positions does the NOSE GEAR GND LOCK CONTROL HANDLE have, and what do they mean?',
 'IN (flush with fuselage) = nose gear unlocked. OUT not rotated = downlock disengaged. OUT rotated CW = downlock engaged. Used for towing/maintenance.', NULL, 'hard', JSON_ARRAY('gear','ground-lock')),
(@system_id, 'TRUE or FALSE — Continuous hydraulic pressure acts on the gear when down-and-locked, and that pressure is what holds the gear down.',
 'PARTIALLY TRUE. Continuous hyd pressure DOES act on the gear when down-and-locked, but the PRIMARY DOWNLOCK is by mechanical overcenter locks — not by hydraulic pressure.', NULL, 'hard', JSON_ARRAY('gear','downlock','overcenter')),
(@system_id, 'What is the EMERG BRAKE lever, and what are its key limitations?',
 'Lever on the engine-control quadrant. Operates against a spring with proportional pressure. Powered by No.2 hyd or accumulator. NO differential braking, NO anti-skid protection. PARK detent at full back illuminates PARKING BRAKE caution.', NULL, 'hard', JSON_ARRAY('gear','emerg-brake')),
(@system_id, 'What are the gear advisory lights on the LANDING GEAR control panel?',
 'L./N./R. DOOR amber (door open). LEFT/NOSE/RIGHT green (down + locked). LEFT/NOSE/RIGHT red (unsafe — not locked up or down). HANDLE amber (handle position vs gear position disagree).', NULL, 'medium', JSON_ARRAY('gear','indications')),
(@system_id, 'TRUE or FALSE — The aft nose doors and forward main doors close hydraulically after the gear retracts.',
 'FALSE. The aft nose doors are MECHANICALLY LINKED to the nose gear and close with the retracting gear. The forward main doors are MECHANICALLY LINKED to the main gear. The HYDRAULIC doors are the forward nose door and the aft main doors — they close hydraulically after the gear is up.', NULL, 'hard', JSON_ARRAY('gear','doors')),
(@system_id, 'What does the LDG GEAR INOP caution indicate?',
 'A landing gear hydraulic sequencing valve has failed, OR the PSEU is unable to control the gear sequencing. Procedure: ALTERNATE GEAR EXTENSION.', NULL, 'medium', JSON_ARRAY('gear','inop','caution')),
(@system_id, 'TRUE or FALSE — Park brake set + engine power applied causes the T/O warning horn to sound.',
 'TRUE. With park brake set, application of engine power triggers the T/O warning horn — a guard against attempting takeoff with the brake on.', NULL, 'medium', JSON_ARRAY('gear','park-brake','warning'));

SELECT COUNT(*) AS flashcards_inserted FROM flashcards WHERE system_id = @system_id;
