-- =============================================================================
-- AviatorTutor — Phase 7: ATA 27 Flight Controls — 36 flashcards.
-- =============================================================================

SET @system_id := (SELECT id FROM systems WHERE slug = 'flight-controls' LIMIT 1);
SELECT @system_id AS resolved_system_id;

DELETE FROM flashcards WHERE system_id = @system_id;

INSERT INTO flashcards (system_id, front, back, hint, difficulty, tags) VALUES
(@system_id, 'What does PFCS stand for and which surfaces are included?',
 'Powered Flight Control Surfaces. Elevators, spoilers, and rudder. All hydraulically powered. Ailerons are NOT in this group — they are mechanical/cable.', NULL, 'easy', JSON_ARRAY('flight-controls','pfcs')),
(@system_id, 'Are Q400 ailerons hydraulically powered?',
 'NO. Ailerons are MECHANICAL / cable-driven. Each surface has a geared tab for aerodynamic assist. Right aileron has a ground-adjustable trim tab.', NULL, 'medium', JSON_ARRAY('flight-controls','aileron')),
(@system_id, 'How many PCUs does each elevator have, and how are they powered?',
 'THREE PCUs per elevator. OUTBOARD = No.1 hyd (active). CENTRE = No.2 hyd (active). INBOARD = No.3 hyd (STANDBY).',
 'Mnemonics: 3-PCU-ELEV · 1-2-3-HYD-ELEV.', 'medium', JSON_ARRAY('flight-controls','elevator','pcu')),
(@system_id, 'When does the inboard elevator PCU activate?',
 'Auto-activates when No.1 OR No.2 hydraulic system fails. Manual activation via HYD #3 ISOL VLV pushbutton on the HYDRAULIC CONTROL panel — but doing so with No.1 and No.2 healthy illuminates the ELEVATOR PRESS caution.', NULL, 'hard', JSON_ARRAY('flight-controls','elevator','standby')),
(@system_id, 'How many roll spoilers does the Q400 have, and how are they hydraulically allocated?',
 'FOUR spoilers (2 inboard + 2 outboard). Inboards on No.1 hyd; outboards on No.2 hyd.',
 'Mnemonic: IN-N1-OUT-N2.', 'medium', JSON_ARRAY('flight-controls','spoilers','hydraulics')),
(@system_id, 'At what airspeed does the FCECU disable the outboard spoilers, and at what airspeed does it re-enable them?',
 'Disabled ABOVE 170 KIAS. Re-enabled BELOW 165 KIAS. The 5-knot deadband prevents hunting. SPLR OUTBD caution if outboards fail to disable above 185 or fail to enable below 150.',
 'Mnemonic: 170-OFF-165-ON.', 'medium', JSON_ARRAY('flight-controls','spoilers','airspeed')),
(@system_id, 'Which wheel controls which surfaces in normal flight?',
 'PILOT''S wheel controls SPOILERS. COPILOT''S wheel controls AILERONS. Both interconnected so either commands both.', NULL, 'medium', JSON_ARRAY('flight-controls','wheels','mapping')),
(@system_id, 'After ROLL DISC pulled and 90°, which surfaces does each pilot retain?',
 'PILOT keeps SPOILERS only. COPILOT keeps AILERONS only. The pilot with the UNJAMMED wheel has roll control.',
 'Mnemonic: ROLL-DISC-90.', 'hard', JSON_ARRAY('flight-controls','roll-jam','disconnect')),
(@system_id, 'What aileron deflection corresponds to full handwheel deflection?',
 '±17° aileron deflection from neutral. Handwheel turns 70° left or right of centre.', NULL, 'medium', JSON_ARRAY('flight-controls','aileron','deflection')),
(@system_id, 'What three conditions must be met for ground-mode lift dump on landing?',
 '(1) FLIGHT/TAXI switch in FLIGHT. (2) Both power levers below FLT IDLE +12°. (3) WOW (weight-on-wheels) on BOTH main gear.',
 'Mnemonic: 3-COND-LIFT-DUMP.', 'medium', JSON_ARRAY('flight-controls','lift-dump','ground')),
(@system_id, 'How long is the time delay before ROLL SPLR INBD/OUTBD GND caution illuminates if a lift-dump valve fails?',
 'FIVE SECONDS time delay before the caution illuminates after a failed extension on touchdown.', NULL, 'hard', JSON_ARRAY('flight-controls','lift-dump','fault')),
(@system_id, 'What does RUD 1 PUSH OFF control, and what does RUD 2 PUSH OFF control?',
 'RUD 1 PUSH OFF = LOWER rudder PCU. RUD 2 PUSH OFF = UPPER rudder PCU. Pushing depressurises that PCU.',
 'Mnemonic: RUD-1-LOWER-RUD-2-UPPER.', 'medium', JSON_ARRAY('flight-controls','rudder','pcu')),
(@system_id, 'AFM 4.18.12 — what is the rule about RUD PUSH OFF switchlights?',
 'Only ONE RUD PUSH OFF switchlight may be pushed at a time. Pushing both inadvertently extinguishes the OFF legends, illuminates both PUSH legends, and re-pressurises the previously-pushed PCU. To recover, push the NON-jammed switch again.', NULL, 'hard', JSON_ARRAY('flight-controls','rudder','afm')),
(@system_id, 'How does the FCECU limit rudder authority?',
 'By reducing hydraulic pressure available to the rudder PCUs as airspeed increases. Less pressure → less rudder deflection for the same pedal input. Airspeed information comes from the Air Data Units (ADUs).', NULL, 'hard', JSON_ARRAY('flight-controls','rudder','fcecu')),
(@system_id, 'What is the maximum yaw damper authority?',
 '±4.5° rudder deflection either side of centre. The yaw damper requires inputs from BOTH Flight Guidance Modules No.1 and No.2.',
 'Mnemonic: 4.5-DEG-YD.', 'medium', JSON_ARRAY('flight-controls','yaw-damper','authority')),
(@system_id, 'What is the pitch trim priority order?',
 'PILOT > COPILOT > AUTOPILOT. The FCECU enforces this priority — the trim signal with the highest priority controls the pitch trim actuator.', NULL, 'medium', JSON_ARRAY('flight-controls','pitch-trim','priority')),
(@system_id, 'What happens if a manual pitch trim command persists for more than 3 seconds?',
 'Aural warning sounds AND the ELEVATOR TRIM SHUTOFF switchlight on the glareshield illuminates. Pushing either left or right ELEVATOR TRIM SHUTOFF switchlight deactivates trim.',
 'Mnemonic: 3-SEC-TRIM.', 'medium', JSON_ARRAY('flight-controls','pitch-trim','shutoff')),
(@system_id, 'Pitch trim rate behaviour by airspeed?',
 'HIGH speed mode below 150 KIAS. LOW speed mode above 250 KIAS. FCECU scales the rate between 150 and 250 KIAS.', NULL, 'hard', JSON_ARRAY('flight-controls','pitch-trim','rate')),
(@system_id, 'When is flap auto-pitch trim active?',
 'Active ONLY when ALL of: flaps in transition between 15° and 35°, autopilot OFF, airspeed below 180 KIAS, no manual pitch trim being commanded. Nose-down on extension, nose-up on retraction.',
 'Mnemonic: 15-35-AUTO-TRIM.', 'hard', JSON_ARRAY('flight-controls','flaps','auto-trim')),
(@system_id, 'What are the five flap-selector lever gates on the Q400?',
 '0°, 5°, 10°, 15°, 35°. Five gates total.',
 'Mnemonic: FLAP-5-GATES.', 'easy', JSON_ARRAY('flight-controls','flaps','gates')),
(@system_id, 'What hydraulic system powers the flaps?',
 'No.1 hydraulic system. The Flap Power Unit (FPU) converts hydraulic power to rotary mechanical power, driving the flap actuators via a primary drive shaft.', NULL, 'medium', JSON_ARRAY('flight-controls','flaps','hydraulics')),
(@system_id, 'How many flap actuators are there per wing?',
 'FOUR actuators per wing — TWO per flap. Bi-directional no-backs in each actuator lock the flap in the selected position against aerodynamic forces.', NULL, 'medium', JSON_ARRAY('flight-controls','flaps','actuators')),
(@system_id, 'What does the FCU do when flaps are moved out of 0°?',
 'Turns ON the Standby Hydraulic Pump and the PTU. The Flap Control Unit (FCU) controls flap movement and turns on the FLAP POWER and FLAP DRIVE caution lights on faults.', NULL, 'hard', JSON_ARRAY('flight-controls','flaps','fcu')),
(@system_id, 'What is the IAS mismatch threshold and what cautions illuminate?',
 'Threshold: ±17 KNOTS between Airspeed #1 and Airspeed #2. Cascade of FOUR cautions: RUD CTRL + SPLR OUTBD + ELEV FEEL + PITCH TRIM. Plus IAS MISMATCH on PFD. Reduce airspeed below 200 KIAS.',
 'Mnemonic: 17-KTS-MISMATCH.', 'hard', JSON_ARRAY('flight-controls','ias-mismatch','cascade')),
(@system_id, 'What is the daily Stall Warning System pre-flight test sequence?',
 'STALL WARN switch to TEST1 (held >10 SECONDS), then to TEST2 (held >10 SECONDS). Tests SPM1 then SPM2 independently.',
 'Mnemonic: 10-SEC-STALL-TEST.', 'medium', JSON_ARRAY('flight-controls','sps','test')),
(@system_id, 'How many Stall Protection Modules and what inputs do they use?',
 'TWO SPMs (SPM1, SPM2). Inputs: Angle of Attack, Flap Position, Mach number, Engine Torque, Icing Status. Stick pusher uses the AVERAGE of AOA1 and AOA2 inputs.', NULL, 'hard', JSON_ARRAY('flight-controls','sps','inputs')),
(@system_id, 'What happens to the autopilot and GPWS when stick shaker activates?',
 'Stick shaker signal disengages the AUTOPILOT and inhibits GPWS PULL UP audible alerts.', NULL, 'hard', JSON_ARRAY('flight-controls','sps','autopilot')),
(@system_id, 'What does the CONTROL LOCK lever do?',
 'AILERON gust lock. FORWARD = OFF (ailerons free). AFT = ON (ailerons locked at neutral). When ON, the lever physically restricts power-lever travel — you cannot advance to takeoff thrust.',
 'Mnemonic: LOCK-FWD-OFF.', 'medium', JSON_ARRAY('flight-controls','gust-lock')),
(@system_id, 'How are the rudder and elevators gust-protected on the ground?',
 'By trapped hydraulic pressure / fluid in the flight control actuators. The retained pressure provides stiffness against external forces. NOT a mechanical gust lock.', NULL, 'hard', JSON_ARRAY('flight-controls','gust-lock','hydraulic')),
(@system_id, 'What is the FLIGHT/TAXI switch logic?',
 'Two positions: FLIGHT (lever-locked, mandatory for takeoff) and TAXI (held by hold-in solenoid). When power levers advance above FLT IDLE +12°, the solenoid de-energises and the switch auto-returns to FLIGHT, retracting all spoilers.', NULL, 'medium', JSON_ARRAY('flight-controls','flight-taxi')),
(@system_id, 'How is roll-spoiler position fed to the MFD?',
 'FOUR LVDTs (Linear Variable Differential Transformers) in the wing send spoiler positions to the FCECU and Integrated Flight Cabinet (IFC). The IFC drives the MFD spoiler position display.', NULL, 'hard', JSON_ARRAY('flight-controls','spoilers','indication')),
(@system_id, 'What does ELEVATOR PRESS caution indicate?',
 'No.1, No.2, AND No.3 hydraulic systems are unable to maintain pressure to the elevator PCUs. Reduce airspeed below 200 KIAS.', NULL, 'hard', JSON_ARRAY('flight-controls','elevator','press-caution')),
(@system_id, 'What does ELEVATOR ASYMMETRY caution mean and what is the action?',
 'FCECU detects mismatch between left and right elevator surfaces. Reduce airspeed below 200 KIAS. Run QRH non-normal.', NULL, 'medium', JSON_ARRAY('flight-controls','elevator','asymmetry')),
(@system_id, 'What does ROLL SPLR INBD HYD caution indicate?',
 'No.1 hydraulic pressure less than 900 PSI, OR SPLR1 PUSH OFF switch has been pressed. Inboard roll spoiler hydraulic loss.', NULL, 'hard', JSON_ARRAY('flight-controls','spoilers','caution')),
(@system_id, 'What does ROLL SPLR OUTBD HYD caution indicate, and at what airspeed?',
 'No.2 hydraulic pressure less than 900 PSI AND airspeed less than 165 KIAS, OR SPLR 2 PUSH OFF switch pressed. NO annunciation if airspeed greater than 170 kts (because outboard spoilers are normally disabled above 170).', NULL, 'hard', JSON_ARRAY('flight-controls','spoilers','caution')),
(@system_id, 'During a real roll jam with the ROLL DISC handle pulled, the LEFT control wheel is FREE. What works on that wheel and what is the handling tip?',
 'Only ROLL SPOILERS will operate (because the pilot wheel = spoilers). Roll forces will be LOW; resist the urge to over-control. Smooth, smaller inputs.', NULL, 'hard', JSON_ARRAY('flight-controls','roll-jam','handling'));

SELECT COUNT(*) AS flashcards_inserted FROM flashcards WHERE system_id = @system_id;
