-- =============================================================================
-- AviatorTutor — Phase 10: ATA 31 Indicating & Recording — 36 flashcards.
-- =============================================================================

SET @system_id := (SELECT id FROM systems WHERE slug = 'indicating-recording' LIMIT 1);
SELECT @system_id AS resolved_system_id;

DELETE FROM flashcards WHERE system_id = @system_id;

INSERT INTO flashcards (system_id, front, back, hint, difficulty, tags) VALUES
(@system_id, 'How many Display Units are in the Q400 Electronic Instrument System (EIS)?',
 'FIVE DUs total: PFD1, MFD1, ED, MFD2, PFD2. All identical and interchangeable.',
 'Mnemonic: 5-DU-IDENTICAL.', 'easy', JSON_ARRAY('indicating','eis','dus')),
(@system_id, 'How many DUs make up EFIS, and how many make up ESID?',
 'EFIS = 4 DUs (PFD1 + MFD1 + MFD2 + PFD2). ESID = 3 DUs (MFD1 + MFD2 + ED). MFDs are shared between the two.',
 'Mnemonic: EFIS-4-ESID-3.', 'medium', JSON_ARRAY('indicating','efis','esid')),
(@system_id, 'Which control panel owns PFD1 and MFD1?',
 'EFCP1 (the pilot-side EFIS Control Panel). EFCP2 owns PFD2 and MFD2.', NULL, 'medium', JSON_ARRAY('indicating','efcp')),
(@system_id, 'Which control panel owns MFD1, MFD2, and the ED?',
 'ESCP (the Engine and System Integrated Display Control Panel). One shared panel.', NULL, 'medium', JSON_ARRAY('indicating','escp')),
(@system_id, 'What positions are on the ESCP MFD1/MFD2 4-position rotary?',
 'PFD / NAV / SYS / ENG. Selecting PFD reroutes adjacent-side PFD content; SYS shows the system pages.', NULL, 'medium', JSON_ARRAY('indicating','escp','rotary')),
(@system_id, 'What happens to the MFD1 and MFD2 selectors after ESCP power loss?',
 'MFD1 selector REMAINS OPERATIVE. MFD2 selector does NOT operate (drops to default).',
 'Mnemonic: MFD2-DIES-WITH-ESCP.', 'hard', JSON_ARRAY('indicating','escp','reversion')),
(@system_id, 'What system pages can be called up via the ESCP system pushbuttons?',
 'ELEC SYS, ENG SYS, FUEL SYS, DOORS SYS, plus ALL (cycle pushbutton).', NULL, 'medium', JSON_ARRAY('indicating','system-pages')),
(@system_id, 'In what order does the ALL pushbutton cycle the system pages?',
 'ENG → FUEL → DOORS → ELEC → ENG (repeating).',
 'Mnemonic: ALL-CYCLE-EFDD-E.', 'hard', JSON_ARRAY('indicating','all','cycle')),
(@system_id, 'When both MFDs are failed or none is set to SYS, what happens if you press-and-hold a system pushbutton?',
 'The selected system page is displayed on the ED in composite format. Releasing the button returns the ED to its normal engine display format.', NULL, 'hard', JSON_ARRAY('indicating','reversion','ed')),
(@system_id, 'What does RED indicate in EIS color logic?',
 'WARNING — immediate recognition and corrective/compensatory action required (e.g. engine red-line exceedance, VMO, TCAS Resolution Advisory).', NULL, 'easy', JSON_ARRAY('indicating','color','red')),
(@system_id, 'What does YELLOW indicate?',
 'CAUTION — immediate awareness required and subsequent crew action (abnormal situations, mismatch, AFCS caution, altitude alert, TCAS Traffic Advisory).', NULL, 'easy', JSON_ARRAY('indicating','color','yellow')),
(@system_id, 'What does CYAN indicate on the EIS?',
 'Pilot-SELECTABLE parameters: Selected Heading / Course / Altitude, speed/torque bugs, baro correction, DH setting.',
 'Mnemonic: CYAN = mine.', 'medium', JSON_ARRAY('indicating','color','cyan')),
(@system_id, 'What does MAGENTA indicate?',
 'TCAS proximate and other traffics; VOR / ILS / DME data and pointers; FMS related data and pointers; flight director commands.',
 'Mnemonic: MAGENTA = FMS/TCAS.', 'medium', JSON_ARRAY('indicating','color','magenta')),
(@system_id, 'What does WHITE indicate?',
 'Aircraft actual parameters and status; advisory messages; legends; scales; aircraft reference; AFCS armed modes; non-active flight-plan parts; bearing pointer 1; units (on EFIS).', NULL, 'medium', JSON_ARRAY('indicating','color','white')),
(@system_id, 'What does GREEN indicate?',
 'Active controlling modes/functions: AFCS active modes, passed test, bearing pointer 2.', NULL, 'medium', JSON_ARRAY('indicating','color','green')),
(@system_id, 'What is the FLASHING attribute on the EIS — rate, duty, and time limit?',
 '1 Hz frequency, 50% duty cycle. Time-limited — typically 5 seconds OR maintained until crew action is completed.',
 'Mnemonic: FLASH-1HZ-5SEC.', 'medium', JSON_ARRAY('indicating','attribute','flash')),
(@system_id, 'What does REVERSE VIDEO indicate, and how long does it last?',
 'A change in operating state that was NOT pilot-initiated. Time-limited (typically 5 sec). Black digits/letters on a coloured rectangular background of the same colour as the indication would be in normal video.', NULL, 'hard', JSON_ARRAY('indicating','attribute','reverse')),
(@system_id, 'What do messages enclosed in BRACKETS [LIKE THIS] mean?',
 'They correspond to flight-crew instructions or required action. The bracketed message is telling you to do something.', NULL, 'medium', JSON_ARRAY('indicating','attribute','brackets')),
(@system_id, 'What primary flight information is shown on the PFD?',
 'FMA (Flight Mode Annunciator), ASI, EADI, ALT, EHSI, IVSI, TCAS II, FMS, GPS data.', NULL, 'medium', JSON_ARRAY('indicating','pfd','content')),
(@system_id, 'What is the Permanent System Data Area (PSDA), and where does it appear?',
 'A persistent area on the MFD that always shows certain critical system parameters regardless of which page is selected. MFD1 PSDA shows PFCS data. MFD2 PSDA shows Flap/Hydraulic data.', NULL, 'hard', JSON_ARRAY('indicating','mfd','psda')),
(@system_id, 'How many digital clocks are on the Q400, and how do they interface with the recorders?',
 'TWO digital clocks. No.1 (pilot side) interfaces directly with the CVR for real-time stamping AND with the FDR via the FDPS. No.2 (copilot side) interfaces with the FDR via the FDPS only.',
 'Mnemonic: TWO-CLOCKS-FDR-CVR.', 'hard', JSON_ARRAY('indicating','clocks','recorders')),
(@system_id, 'How does the FDR handle clock failure?',
 'The FDR normally records using clock No.1. If No.1 fails, the FDR auto-switches to clock No.2.', NULL, 'hard', JSON_ARRAY('indicating','fdr','clock')),
(@system_id, 'How is real-time synchronisation achieved between the FDR and CVR?',
 'Real time is recorded on both FDR and CVR. Post-event reconstruction matches by timestamp.', NULL, 'medium', JSON_ARRAY('indicating','recorder','sync')),
(@system_id, 'What does the WTG do?',
 'Warning Tone Generator. Computes and provides the warning aurals which alert the flight crew to specific events or system failures.', NULL, 'medium', JSON_ARRAY('indicating','wtg')),
(@system_id, 'What colour is the Master Warning switchlight, and what colour is Master Caution?',
 'Master Warning is RED (flashing). Master Caution is AMBER/yellow (flashing). Both are momentary action.',
 'Mnemonic: MASTER-RED-AMBER.', 'easy', JSON_ARRAY('indicating','master','color')),
(@system_id, 'When you push the Master Warning switchlight, what does it reset and what stays illuminated?',
 'Pushing resets the FLASH (audio drops, light stops flashing). The underlying caution/warning panel light remains steady if the fault persists.', NULL, 'medium', JSON_ARRAY('indicating','master','reset')),
(@system_id, 'What does the STALL WARN switch test, and how is it operated?',
 'Three-position spring-loaded centre OFF. TEST 1 = SPS channel 1 (L stick shaker, #1 STALL SYST FAIL on pilot PFD). TEST 2 = SPS channel 2 (R stick shaker, #2 STALL SYST FAIL on copilot PFD). Each position held > 10 seconds.',
 'Mnemonic: TEST1-LSHAKE-TEST2-RSHAKE.', 'hard', JSON_ARRAY('indicating','stall','test')),
(@system_id, 'What does the RA do during STALL WARN TEST 1?',
 'RA increases above 500 ft on the pilot PFD (analog indication is correct; may disappear above 550 ft). On test exit, RA decreases to 50 ft and analog reappears.', NULL, 'hard', JSON_ARRAY('indicating','stall','ra')),
(@system_id, 'What 5 conditions trigger the T/O Warning Horn (with engine running and TEST pressed)?',
 'Inboard or outboard spoilers extended; elevator trim out of takeoff range; parking brake at PARK; one or both condition levers not at MAX/1020; flaps extended >20° or <3.5°.',
 'Mnemonic: 5-COND-TO-HORN.', 'hard', JSON_ARRAY('indicating','to-warning')),
(@system_id, 'What does the STICK PUSHER SHUT-OFF switchlight do?',
 'Alternate-action switchlight. Push: turns off the stick pusher. PUSHER SYST FAIL caution illuminates. "OFF" inscription illuminates on both pilot and copilot pushbuttons. Stick shaker (warning) continues to function.', NULL, 'hard', JSON_ARRAY('indicating','pusher','shut-off')),
(@system_id, 'What does the TERRAIN INHIBIT switchlight do?',
 'Alternate-action white switchlight. Push: inhibits TAD (Terrain Awareness Display) and TCF (Terrain Clearance Floor) alerting and display. "TERRAIN INHIBIT" annunciation appears on the MFD. Push again to deactivate.',
 'Mnemonic: TERRAIN-INHIBIT-WHITE.', 'hard', JSON_ARRAY('indicating','gpws','terrain')),
(@system_id, 'What does the GPWS FLAP OVERRIDE switch do?',
 'Alternate-action amber-crosshatch switchlight. Inhibits GPWS mode 4B ONLY (permits 0° flap landings without aural warning). All other GPWS modes remain active.', NULL, 'hard', JSON_ARRAY('indicating','gpws','flap-override')),
(@system_id, 'What positions are on the GPWS LANDING FLAP SELECT switch?',
 'Three positions: 10° / 15° / 35° (rotary, green segments). When flap lever is set less than the LFSS setting AND AGL altitude < 200 ft, "TOO LOW FLAPS" aural alert sounds.', NULL, 'medium', JSON_ARRAY('indicating','gpws','flap-select')),
(@system_id, 'What does the BELOW G/S switch do?',
 'Momentary amber switch. Push cancels the "BELOW GLIDESLOPE" aural warning.', NULL, 'medium', JSON_ARRAY('indicating','gpws','below-gs')),
(@system_id, 'What is the EFIS ATT/HDG SOURCE selector for?',
 'Cross-side AHRS source selection: NORM / 1 / 2. If your AHRS fails, switch to the other side''s AHRS. Cross-side selection illuminates yellow on PFD.', NULL, 'hard', JSON_ARRAY('indicating','ahrs','source')),
(@system_id, 'What does AVAIL (white) in the centre of a failed PFD indicate?',
 'It confirms that PFD content is AVAILABLE for reversion to the adjacent MFD via the ESCP rotary. Set MFD to PFD on the rotary; PFD content displays.', NULL, 'medium', JSON_ARRAY('indicating','reversion','avail'));

SELECT COUNT(*) AS flashcards_inserted FROM flashcards WHERE system_id = @system_id;
