-- =============================================================================
-- AviatorTutor — Phase 5: ATA 24 Electrical Power — quizzes (Practice 25 + Mock 10)
-- =============================================================================

SET @system_id := (SELECT id FROM systems WHERE slug = 'electrical' LIMIT 1);
SELECT @system_id AS resolved_system_id;

DELETE FROM quizzes WHERE system_id = @system_id;

INSERT INTO quizzes (system_id, title, description, quiz_type, time_limit_mins, pass_score, is_published)
VALUES (@system_id, 'Electrical Power — Practice',
 'Twenty-five-question practice quiz covering EPGDS architecture, generators and TRUs, NiCad batteries, APU starter/generator, external power, EPCU bus management, indications, and abnormal operation.',
 'practice', NULL, 70, 1);
SET @quiz_practice := LAST_INSERT_ID();

INSERT INTO quiz_questions (quiz_id, question_text, question_type, options, correct_answer, explanation, difficulty, sort_order) VALUES
(@quiz_practice, 'How many independent sources of DC power does the Q400 have in flight?',
 'mcq', JSON_ARRAY('Two','Three','Four','Six'),
 JSON_OBJECT('correct_index', 2),
 'Four: 2 engine-driven starter/generators + 2 TRUs. Each normally powers its own dedicated bus.', 'medium', 10),
(@quiz_practice, 'How many NiCad batteries does the Q400 have, and what are their capacities?',
 'mcq', JSON_ARRAY(
   'Two batteries (one 40 Ahr, one 17 Ahr)',
   'Three batteries: two 40 Ahr (main + aux) + one 17 Ahr standby',
   'Three batteries all 40 Ahr',
   'Four batteries 28 VDC each'),
 JSON_OBJECT('correct_index', 1),
 'Three NiCads: 40 Ahr main, 40 Ahr aux, 17 Ahr standby. Mnemonic: 40-40-17.', 'easy', 20),
(@quiz_practice, 'What is the nominal voltage of a 40 Ahr battery under load?',
 'mcq', JSON_ARRAY('20 VDC','24 VDC','28 VDC','32 VDC'),
 JSON_OBJECT('correct_index', 1),
 '24 VDC under load (20 cells × 1.2 VDC). No-load is approximately 28 VDC.', 'medium', 30),
(@quiz_practice, 'A DC GPU output is 26 VDC, connected to the aircraft with batteries on. What happens?',
 'mcq', JSON_ARRAY(
   'Batteries charge slowly',
   'Batteries DISCHARGE into the aircraft loads — they cannot recharge at this voltage',
   'GPU is rejected automatically',
   'EPCU shuts down GPU connection'),
 JSON_OBJECT('correct_index', 1),
 '28 VDC is the minimum charging voltage. Below that, batteries discharge into loads. Cart cannot charge them regardless of time.', 'hard', 40),
(@quiz_practice, 'Where is the DC external power (GPU) receptacle located?',
 'mcq', JSON_ARRAY(
   'Right side of forward fuselage near nose cone',
   'Left side of forward fuselage',
   'Aft fuselage right side',
   'Wing root'),
 JSON_OBJECT('correct_index', 1),
 'DC GPU receptacle on LEFT forward fuselage. AC GPU receptacle on RIGHT forward fuselage near nose cone. Mnemonic: DC-LEFT-AC-RIGHT.', 'medium', 50),
(@quiz_practice, 'Where is the AC external power (GPU) receptacle located?',
 'mcq', JSON_ARRAY(
   'Left side of forward fuselage',
   'Right side of forward fuselage near nose cone',
   'Aft fuselage left side',
   'Tail cone'),
 JSON_OBJECT('correct_index', 1),
 'AC GPU on RIGHT forward fuselage near nose cone. DC GPU is on the LEFT.', 'medium', 60),
(@quiz_practice, 'What is the AC PPU?',
 'mcq', JSON_ARRAY(
   'Auxiliary Pressurization Pump',
   'External Power Protection Unit — monitors AC ground power quality',
   'AC Phase Pulse Unit',
   'APU Power Programming Unit'),
 JSON_OBJECT('correct_index', 1),
 'External Power Protection Unit. Monitors voltage, frequency, phase before allowing power onto the variable-frequency buses. Rejects bad power.', 'medium', 70),
(@quiz_practice, 'On the MFD AC GEN LOAD display, what does "+1.30" mean?',
 'mcq', JSON_ARRAY(
   '130% load — overload condition',
   '13% load',
   '1.30 amperes',
   'Generator off-line'),
 JSON_OBJECT('correct_index', 0),
 '1.00 = 100%. "+" prefix indicates overload. So +1.30 = 130%.', 'medium', 80),
(@quiz_practice, 'What does the MFD AC GEN LOAD display when load is in the expected range?',
 'mcq', JSON_ARRAY(
   '"OK"',
   'Nothing — display only appears for noteworthy values',
   '".00"',
   '"NORM"'),
 JSON_OBJECT('correct_index', 1),
 'When the load is in the expected range, nothing is displayed. The display appears only for specific values or overloads.', 'hard', 90),
(@quiz_practice, 'A DC BUS caution illuminates in flight. After how many seconds will the EPCU trip the affected generator?',
 'mcq', JSON_ARRAY('1 sec','5 sec','15 sec','30 sec'),
 JSON_OBJECT('correct_index', 1),
 '5 seconds of fault persistence. Then EPCU sends TRIP signal to GCU and locks-out battery contactors. Mnemonic: 5-SEC-TRIP.', 'medium', 100),
(@quiz_practice, 'After a persistent main bus fault past 5 seconds, what additional cautions illuminate?',
 'mcq', JSON_ARRAY(
   'Only DC BUS — no others',
   'MAIN BATTERY or AUX/STBY BATTERY caution(s) and the related DC GEN caution',
   'CABIN PRESS only',
   'AP DISENGAGED only'),
 JSON_OBJECT('correct_index', 1),
 'EPCU opens battery contactors and trips the generator → MAIN BATTERY (or AUX-STBY BATTERY) caution illuminates plus the related DC GEN caution.', 'hard', 110),
(@quiz_practice, 'Where is the APU starter/generator located?',
 'mcq', JSON_ARRAY('Forward equipment bay','Wing root','Tail cone section','Below the cockpit floor'),
 JSON_OBJECT('correct_index', 2),
 'Tail cone section. Supplies 28 VDC to ESS main + secondary DC buses on the ground.', 'medium', 120),
(@quiz_practice, 'When DC external power is connected, what does the EPCU do with the engine-driven generators?',
 'mcq', JSON_ARRAY(
   'Generators continue to power the buses in parallel with the cart',
   'EPCU INHIBITS generator-to-bus connections; cart powers buses; generators wait',
   'Generators are disconnected from their drives',
   'No effect; generators independent'),
 JSON_OBJECT('correct_index', 1),
 'EPCU inhibits generator connections to main buses while DC external power connected. Main and aux batteries stay connected.', 'hard', 130),
(@quiz_practice, 'How is the standby battery treated during engine start with DC external power?',
 'mcq', JSON_ARRAY(
   'Connected directly in parallel with main',
   'Diode-isolated from the left main to keep ESS bus voltage acceptable',
   'Disconnected entirely',
   'Charged at 32 VDC'),
 JSON_OBJECT('correct_index', 1),
 'Standby battery is diode-isolated from left main during engine start to keep ESS bus voltage acceptable.', 'hard', 140),
(@quiz_practice, 'What is the function of the EPCU?',
 'mcq', JSON_ARRAY(
   'Engine Power Control Unit — manages engine power',
   'Electrical Power Control Unit — system brain that monitors sources and re-configures bus ties automatically',
   'External Pressurization Cabin Unit',
   'Emergency Pneumatic Control Unit'),
 JSON_OBJECT('correct_index', 1),
 'EPCU = Electrical Power Control Unit. The brain. Monitors all sources and buses; manages bus tie contactors automatically.', 'easy', 150),
(@quiz_practice, 'What does each TRU do?',
 'mcq', JSON_ARRAY(
   'Converts 28 VDC to 115 VAC',
   'Converts 115 VAC to 28 VDC',
   'Stabilizes 28 VDC battery output',
   'Generates 115 VAC for cabin loads'),
 JSON_OBJECT('correct_index', 1),
 'Transformer Rectifier Unit converts 115 VAC to 28 VDC. Two TRUs (TRU 1 fed by AC GEN 1; TRU 2 by AC GEN 2).', 'medium', 160),
(@quiz_practice, 'On the MFD AC GEN LOAD display, ".60" indicates:',
 'mcq', JSON_ARRAY('60 amperes','60% of maximum load','6.0% of maximum','0.6 of capacity (overload)'),
 JSON_OBJECT('correct_index', 1),
 '60% of maximum load. Leading zero suppressed. 1.00 = 100%.', 'medium', 170),
(@quiz_practice, 'TRUE or FALSE — All four DC sources lost is a "land at nearest suitable" event.',
 'true_false', JSON_ARRAY('True','False'),
 JSON_OBJECT('correct_index', 0),
 'TRUE. Battery-only operation is time-critical. Nearest suitable airport. 17 Ahr standby keeps ESS standby bus alive longest.', 'medium', 180),
(@quiz_practice, 'TRUE or FALSE — In flight, TRUs typically carry most of the DC load.',
 'true_false', JSON_ARRAY('True','False'),
 JSON_OBJECT('correct_index', 0),
 'TRUE. Engine-driven DC starter/generators are sized primarily for engine starting. TRUs handle most of the running DC load.', 'hard', 190),
(@quiz_practice, 'TRUE or FALSE — A single DC generator failure in flight requires immediate descent.',
 'true_false', JSON_ARRAY('True','False'),
 JSON_OBJECT('correct_index', 1),
 'FALSE. EPCU re-configures bus ties automatically. Surviving DC gen + both TRUs feed all DC buses. Continue normally; QRH directs.', 'medium', 200),
(@quiz_practice, 'TRUE or FALSE — The standby battery is in the aft fuselage.',
 'true_false', JSON_ARRAY('True','False'),
 JSON_OBJECT('correct_index', 1),
 'FALSE. The 17 Ahr standby battery is in the FORWARD fuselage adjacent to the two 40 Ahr batteries.', 'medium', 210),
(@quiz_practice, 'TRUE or FALSE — APU starter/generator only operates on the ground.',
 'true_false', JSON_ARRAY('True','False'),
 JSON_OBJECT('correct_index', 1),
 'FALSE. APU starter/generator is "designed to supply 28 VDC to essential main and secondary DC buses on the ground" but the APU itself can be started in flight per QRH and serve as a backup source.', 'hard', 220),
(@quiz_practice, 'TRUE or FALSE — DC GPU output of 32 VDC is acceptable for charging the batteries.',
 'true_false', JSON_ARRAY('True','False'),
 JSON_OBJECT('correct_index', 0),
 'TRUE. Charging requires 28–32 VDC (1.4–1.6 VDC/cell). 32 VDC is the upper end of the acceptable range.', 'hard', 230),
(@quiz_practice, 'TRUE or FALSE — When the EPCU detects a bus fault, it immediately trips the generator.',
 'true_false', JSON_ARRAY('True','False'),
 JSON_OBJECT('correct_index', 1),
 'FALSE. EPCU first isolates the bus and illuminates DC BUS caution. Only after ~5 seconds of fault persistence does it trip the generator.', 'medium', 240),
(@quiz_practice, 'TRUE or FALSE — The EPCU is the same unit as the GCU.',
 'true_false', JSON_ARRAY('True','False'),
 JSON_OBJECT('correct_index', 1),
 'FALSE. EPCU = Electrical Power Control Unit (system brain). GCU = Generator Control Unit (one per generator). EPCU sends TRIP signals TO the GCUs.', 'medium', 250);

INSERT INTO quizzes (system_id, title, description, quiz_type, time_limit_mins, pass_score, is_published)
VALUES (@system_id, 'Electrical Power — Type Rating Mock',
 'Ten-question mock at type-rating standard. Twelve-minute timer, pass score 80%.',
 'exam', 12, 80, 1);
SET @quiz_exam := LAST_INSERT_ID();

INSERT INTO quiz_questions (quiz_id, question_text, question_type, options, correct_answer, explanation, difficulty, sort_order) VALUES
(@quiz_exam, 'How many independent DC sources in flight, and what are they?',
 'mcq', JSON_ARRAY(
   'Two — generators only',
   'Four — 2 engine-driven starter/gens + 2 TRUs',
   'Three — 2 generators + 1 APU',
   'Four — 2 generators + 2 batteries'),
 JSON_OBJECT('correct_index', 1),
 'Four DC sources: 2 engine-driven gens + 2 TRUs. Each normally on its own dedicated bus.', 'medium', 10),
(@quiz_exam, 'Battery configuration on the Q400.',
 'mcq', JSON_ARRAY(
   'Two batteries: 28 VDC each',
   'Three NiCads: 40 Ahr main + 40 Ahr aux + 17 Ahr standby',
   'Four batteries with diode isolation',
   'Single 80 Ahr battery'),
 JSON_OBJECT('correct_index', 1),
 'Three NiCads. Two 40 Ahr (main + aux) + one 17 Ahr standby in the forward fuselage. Mnemonic: 40-40-17.', 'medium', 20),
(@quiz_exam, 'External power receptacle locations.',
 'mcq', JSON_ARRAY(
   'DC RIGHT, AC LEFT',
   'DC LEFT forward fuselage; AC RIGHT forward fuselage near nose cone',
   'Both on the aft fuselage',
   'Both on the wing root'),
 JSON_OBJECT('correct_index', 1),
 'DC GPU LEFT forward fuselage; AC GPU RIGHT forward fuselage near nose cone. Mnemonic: DC-LEFT-AC-RIGHT.', 'medium', 30),
(@quiz_exam, 'What does "+1.30" on the AC GEN LOAD display indicate?',
 'mcq', JSON_ARRAY('30% load','130% load — overload','13% load','Generator failed'),
 JSON_OBJECT('correct_index', 1),
 '"+" prefix = overload. 1.00 = 100%, so +1.30 = 130%.', 'medium', 40),
(@quiz_exam, 'A DC BUS caution illuminates in flight. What is the timing logic?',
 'mcq', JSON_ARRAY(
   'Generator trips immediately',
   'Bus is isolated, then ~5 seconds of fault persistence triggers EPCU TRIP to GCU and battery contactor lockout',
   '30-second tolerance window',
   'No automatic action; crew must intervene'),
 JSON_OBJECT('correct_index', 1),
 'DC BUS caution first; ~5 seconds for the fault to clear; if persistent, EPCU sends TRIP, opens battery contactors, illuminates additional cautions.', 'hard', 50),
(@quiz_exam, 'Charging voltage requirements for the 40 Ahr batteries.',
 'mcq', JSON_ARRAY(
   '20–24 VDC',
   '28–32 VDC (1.4–1.6 VDC/cell)',
   '12–14 VDC',
   '36–40 VDC'),
 JSON_OBJECT('correct_index', 1),
 '28–32 VDC. Below 28 VDC: batteries discharge into loads. Mnemonic: 28-VDC-CHARGE.', 'hard', 60),
(@quiz_exam, 'Where is the APU starter/generator located, and what does it supply on the ground?',
 'mcq', JSON_ARRAY(
   'Forward equipment bay; supplies 115 VAC',
   'Tail cone; supplies 28 VDC to essential main + secondary DC buses',
   'Wing root; supplies 24 VDC to standby bus only',
   'Below the cockpit; supplies AC + DC mixed'),
 JSON_OBJECT('correct_index', 1),
 'Tail cone. 28 VDC to ESS main + secondary DC buses on the ground.', 'medium', 70),
(@quiz_exam, 'TRUE or FALSE — While DC external power is connected, the engine-driven generators are isolated from the main buses.',
 'true_false', JSON_ARRAY('True','False'),
 JSON_OBJECT('correct_index', 0),
 'TRUE. EPCU inhibits generator connections to main buses while DC external power connected. Generators wait; cart powers buses.', 'hard', 80),
(@quiz_exam, 'TRUE or FALSE — In flight, the TRUs typically carry most of the DC load.',
 'true_false', JSON_ARRAY('True','False'),
 JSON_OBJECT('correct_index', 0),
 'TRUE. DC starter/generators are sized primarily for engine starting. TRUs handle most of the running DC load.', 'hard', 90),
(@quiz_exam, 'On a single DC generator failure in flight, what is the immediate crew action?',
 'mcq', JSON_ARRAY(
   'Immediate descent',
   'Confirm bus tie reconfigured (EPCU automatic) and run QRH non-normal — continue flight',
   'Switch to MAN pressurisation',
   'Reset the EPCU breaker'),
 JSON_OBJECT('correct_index', 1),
 'EPCU re-configures bus ties automatically; surviving DC gen + both TRUs cover all DC buses. Run QRH; continue normally; brief approach for reduced electrical capacity.', 'medium', 100);

SELECT
    (SELECT COUNT(*) FROM quizzes WHERE system_id = @system_id) AS quizzes_inserted,
    (SELECT COUNT(*) FROM quiz_questions WHERE quiz_id IN
        (SELECT id FROM quizzes WHERE system_id = @system_id)) AS questions_inserted;
