-- =============================================================================
-- AviatorTutor — Phase 4: ATA 23 Communications — quizzes (Practice 25 + Mock 10)
-- =============================================================================

SET @system_id := (SELECT id FROM systems WHERE slug = 'communications' LIMIT 1);
SELECT @system_id AS resolved_system_id;

DELETE FROM quizzes WHERE system_id = @system_id;

INSERT INTO quizzes (system_id, title, description, quiz_type, time_limit_mins, pass_score, is_published)
VALUES (@system_id, 'Communications — Practice',
 'Twenty-five-question practice quiz covering ARMS architecture, ARCDU operation and colours, VHF testing and standby tuner, audio panels, ELT operation, ACARS, and CVR.',
 'practice', NULL, 70, 1);
SET @quiz_practice := LAST_INSERT_ID();

INSERT INTO quiz_questions (quiz_id, question_text, question_type, options, correct_answer, explanation, difficulty, sort_order) VALUES
(@quiz_practice, 'What does ARMS stand for?',
 'mcq', JSON_ARRAY('Audio and Radio Management System','Air Radio Management Suite','ATC Radio Modulation Subsystem','Audio Receiver Module Set'),
 JSON_OBJECT('correct_index', 0),
 'Audio and Radio Management System. The umbrella covering RCOM, PACIS, and AIS.', 'easy', 10),
(@quiz_practice, 'Which of the following is NOT part of ARMS?',
 'mcq', JSON_ARRAY('RCOM','PACIS','AIS','ELT'),
 JSON_OBJECT('correct_index', 3),
 'ELT is a separate communication-equipment item, not part of ARMS.', 'medium', 20),
(@quiz_practice, 'How many ARCDUs does the Q400 cockpit have?',
 'mcq', JSON_ARRAY('One','Two','Three','Four'),
 JSON_OBJECT('correct_index', 1),
 'Two ARCDUs (captain side, FO side).', 'easy', 30),
(@quiz_practice, 'Active frequency on the ARCDU is shown in WHITE digits. What does this mean?',
 'mcq', JSON_ARRAY('Normal valid data','Standby mode','Invalid or no data','Test in progress'),
 JSON_OBJECT('correct_index', 2),
 'Active green = valid; active white = invalid or no data.', 'medium', 40),
(@quiz_practice, 'How long does the highlighted preset stay before reverting?',
 'mcq', JSON_ARRAY('3 seconds','5 seconds','10 seconds','30 seconds'),
 JSON_OBJECT('correct_index', 1),
 '5-second timeout — no action and the highlight reverts to plain cyan.', 'medium', 50),
(@quiz_practice, 'How is a VHF test initiated on the ARCDU?',
 'mcq', JSON_ARRAY('Hold PTT for 5 sec','Side key VHF, then EXP, then side key TEST','Cycle the BLEED selector','Push the FAULT button'),
 JSON_OBJECT('correct_index', 1),
 'Three-step sequence: VHF · EXP · TEST. Squelch disabled for 1 sec; listen for noise.', 'medium', 60),
(@quiz_practice, 'How long does a Q400 VHF test run?',
 'mcq', JSON_ARRAY('1 second','3 seconds','5 seconds','10 seconds'),
 JSON_OBJECT('correct_index', 0),
 '1 second of squelch-disabled noise. No automatic pass/fail — your ear is the test.', 'medium', 70),
(@quiz_practice, 'During a VHF test, the green SQL with diagonal line means:',
 'mcq', JSON_ARRAY('Squelch closed','Squelch open (disabled)','Test failed','Test passed'),
 JSON_OBJECT('correct_index', 1),
 'Squelch is open — circuit is disabled so the receiver noise can be heard.', 'hard', 80),
(@quiz_practice, 'Both ARCDUs fail. Which radio is still tunable, and how?',
 'mcq', JSON_ARRAY(
   'No radios — both ARCDUs are required',
   'VHF1 via the VHF1 Standby Control and Display Unit on the side console',
   'VHF3 via the FMS',
   'Only HF via the audio control panel'),
 JSON_OBJECT('correct_index', 1),
 'VHF1 Standby Control and Display Unit is the dedicated backup. Switch ON, tune, declare.', 'medium', 90),
(@quiz_practice, 'What positions are on the VHF1 Standby Control and Display Unit rotary?',
 'mcq', JSON_ARRAY('OFF / ON','OFF / ON / TEST','OFF / TEST','TEST / ON / DUMP'),
 JSON_OBJECT('correct_index', 1),
 'Three positions: OFF / ON / TEST. TEST disables receiver squelch.', 'medium', 100),
(@quiz_practice, 'When PTT is pressed, the flight-deck speakers mute by:',
 'mcq', JSON_ARRAY('3 dB','6 dB','10 dB','Speakers mute completely'),
 JSON_OBJECT('correct_index', 1),
 '6 dB. Anti-feedback measure during transmission.', 'medium', 110),
(@quiz_practice, 'For INPH (interphone) to work, the mic/interphone selector on the ARCDU must be in:',
 'mcq', JSON_ARRAY('VHF1 only','SERV/INT or PA','OFF','TEST'),
 JSON_OBJECT('correct_index', 1),
 'INPH requires SERV/INT or PA selection on the ARCDU mic/interphone selector.', 'medium', 120),
(@quiz_practice, 'The transmitter keys on the Observer Audio Control Panel are:',
 'mcq', JSON_ARRAY('Independently selectable','Mechanically interlocked — only one at a time','Software-locked','PTT-only'),
 JSON_OBJECT('correct_index', 1),
 'Mechanically interlocked. Only one transmitter selected at a time.', 'hard', 130),
(@quiz_practice, 'The FWD segment of the Ground Crew Connection annunciator means:',
 'mcq', JSON_ARRAY(
   'Forward fuel pump on',
   'Ground crew connected at the DC external connection point',
   'Forward door open',
   'Forward baggage compartment unlocked'),
 JSON_OBJECT('correct_index', 1),
 'FWD amber = ground crew at DC external connection. AFT amber = REFUEL/DEFUEL or aft connection.', 'medium', 140),
(@quiz_practice, 'How many frequencies does the Q400 ELT transmit on?',
 'mcq', JSON_ARRAY('One — 121.5 only','Two — 121.5 and 243','Three — 121.5, 243, 406','Four'),
 JSON_OBJECT('correct_index', 2),
 'Three frequencies: 121.5, 243, 406 MHz. Kannad with COSPAS/SARSAT.', 'easy', 150),
(@quiz_practice, 'At what longitudinal G threshold does the ELT inertia switch activate?',
 'mcq', JSON_ARRAY('1–3 G','3–5 G','5–7 G','9–11 G'),
 JSON_OBJECT('correct_index', 2),
 'Between 5 and 7 G longitudinal acceleration. Mnemonic: 5-7-G-ARMED.', 'medium', 160),
(@quiz_practice, 'What three positions are on the ELT remote switch?',
 'mcq', JSON_ARRAY('ON / OFF / TEST','ON / ARMED / RESET & TEST','ARMED / RESET / DUMP','MANUAL / AUTO / OFF'),
 JSON_OBJECT('correct_index', 1),
 'ON (manual override), ARMED (automatic via inertia), RESET & TEST (momentary, re-arm).', 'medium', 170),
(@quiz_practice, 'Normal armed-state ELT monitor light behaviour?',
 'mcq', JSON_ARRAY('Steady on','One long flash every 3 seconds','Continuous flashing','Off until activation'),
 JSON_OBJECT('correct_index', 1),
 'One long flash every 3 seconds = normal armed. Series of short flashes = fault.', 'medium', 180),
(@quiz_practice, 'After a firm landing the ELT monitor light flashes every 4 seconds. Best action?',
 'mcq', JSON_ARRAY(
   'Ignore — will reset itself',
   'Set ELT remote switch to RESET & TEST momentarily; advise ATC; tech log',
   'Switch ELT to ON to confirm transmission',
   'Pull the ELT circuit breaker'),
 JSON_OBJECT('correct_index', 1),
 'Inadvertent activation. RESET & TEST clears it; advise tower; engineering check threshold.', 'hard', 190),
(@quiz_practice, 'ACARS uses which VHF comm radio for its data link?',
 'mcq', JSON_ARRAY('VHF 1','VHF 2','Dedicated 3rd VHF','HF only'),
 JSON_OBJECT('correct_index', 2),
 'Dedicated 3rd VHF Comm (Thompson EVR 76). Independent antenna; data only; no voice.', 'medium', 200),
(@quiz_practice, 'TRUE or FALSE — ACARS supports voice transmission on the dedicated 3rd VHF.',
 'true_false', JSON_ARRAY('True','False'),
 JSON_OBJECT('correct_index', 1),
 'FALSE. ACARS is data only. The dedicated 3rd VHF has no voice capability.', 'medium', 210),
(@quiz_practice, 'TRUE or FALSE — The Q400 SSCVR records the last 30 minutes only.',
 'true_false', JSON_ARRAY('True','False'),
 JSON_OBJECT('correct_index', 1),
 'FALSE. Solid-state CVR records the last 2 hours of audio.', 'medium', 220),
(@quiz_practice, 'TRUE or FALSE — Both ARCDUs are required to tune VHF1.',
 'true_false', JSON_ARRAY('True','False'),
 JSON_OBJECT('correct_index', 1),
 'FALSE. Either ARCDU can tune VHF1; the VHF1 Standby Control and Display Unit can also tune VHF1 even if both ARCDUs fail.', 'medium', 230),
(@quiz_practice, 'TRUE or FALSE — Lost-comms transponder code is 7700.',
 'true_false', JSON_ARRAY('True','False'),
 JSON_OBJECT('correct_index', 1),
 'FALSE. Lost-comms code is 7600. 7700 is general emergency. 7500 is hijack.', 'easy', 240),
(@quiz_practice, 'TRUE or FALSE — The CVR captures the flight deck area microphone.',
 'true_false', JSON_ARRAY('True','False'),
 JSON_OBJECT('correct_index', 0),
 'TRUE. The four data streams are: flight crew comms, flight deck area mic, PA announcements, clock data.', 'medium', 250);

INSERT INTO quizzes (system_id, title, description, quiz_type, time_limit_mins, pass_score, is_published)
VALUES (@system_id, 'Communications — Type Rating Mock',
 'Ten-question mock at type-rating standard. Twelve-minute timer, pass score 80%.',
 'exam', 12, 80, 1);
SET @quiz_exam := LAST_INSERT_ID();

INSERT INTO quiz_questions (quiz_id, question_text, question_type, options, correct_answer, explanation, difficulty, sort_order) VALUES
(@quiz_exam, 'Describe ARMS architecture.',
 'mcq', JSON_ARRAY(
   'Single Audio Receiver Module',
   'Audio and Radio Management System: RCOM + PACIS + AIS umbrella; CVR/FDR/ELT separate',
   'Air Radio Management Suite: VHF + HF + ELT integrated',
   'Two-channel radio system'),
 JSON_OBJECT('correct_index', 1),
 'ARMS = umbrella covering RCOM (radio comm/nav), PACIS (cabin), AIS (audio integration). CVR/FDR/ELT separate.', 'medium', 10),
(@quiz_exam, 'Frequency colour conventions on the ARCDU.',
 'mcq', JSON_ARRAY(
   'Active green/white; preset cyan/highlighted-cyan',
   'Active blue; preset green',
   'Active green; preset amber',
   'Active red; preset green'),
 JSON_OBJECT('correct_index', 0),
 'Active GREEN (valid) / WHITE (invalid). Preset CYAN (highlighted black-on-cyan when in tune window).', 'medium', 20),
(@quiz_exam, 'VHF test step sequence.',
 'mcq', JSON_ARRAY(
   'Hold PTT for 3 seconds',
   'VHF · EXP · TEST',
   'Cycle BLEED switch',
   'EMER mode'),
 JSON_OBJECT('correct_index', 1),
 'VHF side key → EXP key → TEST side key. 1-second squelch-disable; listen for noise.', 'medium', 30),
(@quiz_exam, 'Recovery if both ARCDUs are unusable in flight.',
 'mcq', JSON_ARRAY(
   'No recovery — declare on guard',
   'VHF1 Standby Control and Display Unit on side console; switch ON; tune VHF1; declare',
   'FMS comms page',
   'Cabin attendant panel'),
 JSON_OBJECT('correct_index', 1),
 'VHF1 Standby Control and Display Unit is the backup. Switch ON, tune, declare.', 'hard', 40),
(@quiz_exam, 'ELT inertia trigger threshold and direction.',
 'mcq', JSON_ARRAY(
   '1–3 G vertical',
   '5–7 G longitudinal',
   '9–11 G horizontal',
   '5–7 G vertical'),
 JSON_OBJECT('correct_index', 1),
 'Between 5 and 7 G LONGITUDINAL acceleration. Direction matters — not vertical.', 'medium', 50),
(@quiz_exam, 'ELT remote switch positions.',
 'mcq', JSON_ARRAY(
   'ON / OFF / TEST',
   'ON / ARMED / RESET & TEST',
   'AUTO / MAN / DUMP',
   'STBY / NORM / EMER'),
 JSON_OBJECT('correct_index', 1),
 'ON (manual override), ARMED (auto via inertia), RESET & TEST (momentary, re-arm). Spring-loaded away from RESET & TEST.', 'medium', 60),
(@quiz_exam, 'Normal armed-state ELT monitor light?',
 'mcq', JSON_ARRAY(
   'Steady on',
   'One long flash every 3 seconds',
   'Series of short flashes',
   'Off'),
 JSON_OBJECT('correct_index', 1),
 '1 long flash every 3 seconds = normal armed. Short flashes = fault.', 'medium', 70),
(@quiz_exam, 'ACARS uses which VHF, and is voice supported?',
 'mcq', JSON_ARRAY(
   'VHF 1 with voice support',
   'Dedicated 3rd VHF, NO voice (data only)',
   'VHF 2 with optional voice',
   'HF only'),
 JSON_OBJECT('correct_index', 1),
 'Dedicated 3rd VHF (Thompson EVR 76); data only; no voice; tuned by ACARS itself.', 'medium', 80),
(@quiz_exam, 'CVR recording duration.',
 'mcq', JSON_ARRAY('Last 30 min','Last 1 hr','Last 2 hours','Continuous since power-on'),
 JSON_OBJECT('correct_index', 2),
 'Solid-state CVR records the last 2 hours of audio (continuous loop).', 'medium', 90),
(@quiz_exam, 'Lost-comms transponder code on the Q400.',
 'mcq', JSON_ARRAY('7500','7600','7700','7777'),
 JSON_OBJECT('correct_index', 1),
 '7600 = lost comms. 7500 = hijack. 7700 = general emergency.', 'easy', 100);

SELECT
    (SELECT COUNT(*) FROM quizzes WHERE system_id = @system_id) AS quizzes_inserted,
    (SELECT COUNT(*) FROM quiz_questions WHERE quiz_id IN
        (SELECT id FROM quizzes WHERE system_id = @system_id)) AS questions_inserted;
