-- =============================================================================
-- AviatorTutor — Phase 11: ATA 32 Landing Gear — quizzes.
-- =============================================================================

SET @system_id := (SELECT id FROM systems WHERE slug = 'landing-gear' LIMIT 1);
SELECT @system_id AS resolved_system_id;

DELETE FROM quizzes WHERE system_id = @system_id;

INSERT INTO quizzes (system_id, title, description, quiz_type, time_limit_mins, pass_score, is_published)
VALUES (@system_id,
 'Landing Gear — Practice',
 'Twenty-five-question practice quiz on gear architecture, hydraulic allocation, steering, anti-skid, alternate extension, and warning tone logic. No time limit.',
 'practice', NULL, 70, 1);

SET @quiz_practice := LAST_INSERT_ID();

INSERT INTO quiz_questions (quiz_id, question_text, question_type, options, correct_answer, explanation, difficulty, sort_order) VALUES
(@quiz_practice, 'Which hydraulic system powers landing gear extension/retraction and nosewheel steering?',
 'mcq',
 JSON_ARRAY('No.1','No.2','No.3 standby','Independent gear hydraulic system'),
 JSON_OBJECT('correct_index', 1),
 'No.2 hyd. Same system also powers steering. Mnemonic: N2-GEAR-N1-BRAKES.',
 'easy', 10),
(@quiz_practice, 'Which hydraulic system powers normal anti-skid brakes?',
 'mcq',
 JSON_ARRAY('No.1','No.2','No.3 standby','Engine bleed pressure'),
 JSON_OBJECT('correct_index', 0),
 'No.1 hyd for normal brakes. EMERG BRAKE = No.2 or accumulator.',
 'easy', 20),
(@quiz_practice, 'In which directions do the nose and main landing gears retract?',
 'mcq',
 JSON_ARRAY(
   'Nose aft, mains forward',
   'Nose forward, mains aft',
   'All retract sideways into the wing',
   'Nose forward, mains forward'
 ),
 JSON_OBJECT('correct_index', 1),
 'Nose forward into the nose section; mains aft into the nacelles. Mnemonic: NOSE-FWD-MAINS-AFT.',
 'medium', 30),
(@quiz_practice, 'What is the nosewheel deflection range via the Steering Hand Control (tiller)?',
 'mcq',
 JSON_ARRAY('±8°','±30°','±70°','±120°'),
 JSON_OBJECT('correct_index', 2),
 '±70° via tiller for low-speed taxi. Pedals = ±8° for high-speed.',
 'medium', 40),
(@quiz_practice, 'What is the nosewheel deflection range via the rudder pedals?',
 'mcq',
 JSON_ARRAY('±8°','±15°','±30°','±70°'),
 JSON_OBJECT('correct_index', 0),
 '±8° via pedals for high-speed taxi, T-O, landing roll.',
 'medium', 50),
(@quiz_practice, 'What is the passive caster range of the nosewheel?',
 'mcq',
 JSON_ARRAY('±70°','±90°','±100°','±120°'),
 JSON_OBJECT('correct_index', 3),
 '±120° passive caster. Triggered by angle >70°, SCU fault, or STEERING OFF.',
 'medium', 60),
(@quiz_practice, 'What rule applies during reverse taxi?',
 'mcq',
 JSON_ARRAY(
   'STEERING switch OFF',
   'STEERING switch ON, but no tiller or rudder pedal input allowed',
   'Tiller only, no rudder pedals',
   'Rudder pedals only, no tiller'
 ),
 JSON_OBJECT('correct_index', 1),
 'STEERING ON but NO tiller or pedal input. Direction via differential brake + power.',
 'hard', 70),
(@quiz_practice, 'What two conditions trigger the NOSE STEERING caution?',
 'mcq',
 JSON_ARRAY(
   'SCU fault with STEERING ON, OR hyd pressure detected with STEERING OFF',
   'Towbar connected; tiller jammed',
   'Wheel speed below 5 kts; STEERING OFF',
   'Anti-skid fault'
 ),
 JSON_OBJECT('correct_index', 0),
 '(1) SCU fault + STEERING ON. (2) Hyd pressure detected + STEERING OFF. Caution does NOT illuminate on SCU power loss.',
 'hard', 80),
(@quiz_practice, 'At what wheel speed does the anti-skid system arm and start modulating brake pressure?',
 'mcq',
 JSON_ARRAY('5 kts','10 kts','17 kts','35 kts'),
 JSON_OBJECT('correct_index', 1),
 'Above 10 kts wheel speed (with ANTI SKID switch ON). Mnemonic: 10-17-35-BRAKE.',
 'medium', 90),
(@quiz_practice, 'Above what wheel speed is the anti-skid self-test prevented?',
 'mcq',
 JSON_ARRAY('10 kts','17 kts','35 kts','60 kts'),
 JSON_OBJECT('correct_index', 1),
 'Self-test prevented above 17 kts.',
 'medium', 100),
(@quiz_practice, 'When is the 5-second brake delay applied, and when is it cancelled?',
 'mcq',
 JSON_ARRAY(
   'Always — fixed 5-sec delay on all brake inputs',
   'Applied if wheels haven''t spun up after WOW; cancelled when wheel speed >35 kts',
   'Applied only on contaminated runways',
   'Applied only when EMERG BRAKE is engaged'
 ),
 JSON_OBJECT('correct_index', 1),
 '5-sec delay only if wheels haven''t spun up. Cancelled at 35 kts wheel speed.',
 'hard', 110),
(@quiz_practice, 'How long do the anti-skid caution lights illuminate during TEST on the ground?',
 'mcq',
 JSON_ARRAY('2 seconds','3 seconds','6 seconds','10 seconds'),
 JSON_OBJECT('correct_index', 2),
 '6 sec on ground. 3 sec in air with gear extended.',
 'medium', 120),
(@quiz_practice, 'What three triggers initiate alternate gear extension?',
 'mcq',
 JSON_ARRAY(
   'LDG GEAR INOP, indication failure, loss of No.2 hyd',
   'Loss of No.1 hyd only',
   'Battery failure',
   'Pre-flight test failure'
 ),
 JSON_OBJECT('correct_index', 0),
 'LDG GEAR INOP caution, indication failure, OR loss of No.2 hyd pressure.',
 'medium', 130),
(@quiz_practice, 'What is the FIRST step of alternate gear extension?',
 'mcq',
 JSON_ARRAY(
   'Pull MAIN L/G RELEASE handle',
   'Set LANDING GEAR INHIBIT switch to INHIBIT',
   'Open the floor extension door',
   'Operate the hand pump'
 ),
 JSON_OBJECT('correct_index', 1),
 'INHIBIT first — isolates hyd from gear system.',
 'hard', 140),
(@quiz_practice, 'What does pulling the MAIN L/G RELEASE handle do?',
 'mcq',
 JSON_ARRAY(
   'Releases main gear hydraulic doors and uplocks; gear free-falls',
   'Releases nose gear only',
   'Activates the hand pump',
   'Engages park brake'
 ),
 JSON_OBJECT('correct_index', 0),
 'Releases main gear doors + uplocks. Mains free-fall (may not fully extend without hand-pump).',
 'medium', 150),
(@quiz_practice, 'What does the hand pump in alternate extension do, and when is it needed?',
 'mcq',
 JSON_ARRAY(
   'Pumps fluid for nose gear only',
   'Drives fluid from emergency reservoir to MLG auxiliary actuators if mains haven''t reached down-and-locked after MAIN L/G RELEASE',
   'Pumps the brake accumulator',
   'Resets the PSEU'
 ),
 JSON_OBJECT('correct_index', 1),
 'Hand pump completes MLG downlock if free-fall is insufficient. Pump until handle is stiff.',
 'hard', 160),
(@quiz_practice, 'What does the ALTERNATE DOWNLOCK VERIFICATION switch do when set to AFT?',
 'mcq',
 JSON_ARRAY(
   'Locks the gear in the up position',
   'Activates 3 green floor downlock verification lights',
   'Disables the gear horn',
   'Inhibits the FCECU'
 ),
 JSON_OBJECT('correct_index', 1),
 '3 green floor lights confirm individual gear downlock. Mnemonic: 3-GREEN-FLOOR-LIGHTS.',
 'medium', 170),
(@quiz_practice, 'After alternate gear extension, what must be done with the two doors?',
 'mcq',
 JSON_ARRAY(
   'Both closed and latched',
   'Both LEFT FULLY OPEN',
   'Overhead door open, floor door closed',
   'Floor door open, overhead door closed'
 ),
 JSON_OBJECT('correct_index', 1),
 'BOTH doors fully open. Closing them defeats the alt path.',
 'hard', 180),
(@quiz_practice, 'How many gear warning tone trigger groups are there, and which one(s) may be MUTED?',
 'mcq',
 JSON_ARRAY(
   '3 groups; all may be muted',
   '3 groups; ONLY case 3 (single-engine fail at low speed) may be muted',
   '2 groups; both may be muted',
   '4 groups; none may be muted'
 ),
 JSON_OBJECT('correct_index', 1),
 'Three groups. Only case 3 (engine-fail low-speed) may be muted via HORN switch. Mnemonic: 3-TONE-GROUPS-MUTE-3.',
 'hard', 190),
(@quiz_practice, 'What KIAS and RA threshold are used in the gear warning tone logic for cases 2 and 3?',
 'mcq',
 JSON_ARRAY('KIAS <120; RA <500 ft','KIAS <156; RA <1053 ft','KIAS <200; RA <2000 ft','No KIAS / RA threshold'),
 JSON_OBJECT('correct_index', 1),
 'KIAS <156 and RA <1053 ft (321 m). Mnemonic: 156-KIAS-1053-RA.',
 'hard', 200),
(@quiz_practice, 'How many brake applications does a fully charged park brake accumulator give?',
 'mcq',
 JSON_ARRAY('2','4','6','12'),
 JSON_OBJECT('correct_index', 2),
 '~6 applications. Mnemonic: 6-APP-500-PSI-PARK.',
 'medium', 210),
(@quiz_practice, 'What is the minimum park brake pressure required before engine start?',
 'mcq',
 JSON_ARRAY('100 PSI','300 PSI','500 PSI','1000 PSI'),
 JSON_OBJECT('correct_index', 2),
 '500 PSI on the PK BRK indicator (PSA of MFD).',
 'medium', 220),
(@quiz_practice, 'What does the EMERG BRAKE NOT provide that the normal brake system provides?',
 'mcq',
 JSON_ARRAY(
   'Hydraulic pressure',
   'Differential braking AND anti-skid protection',
   'Brake pedal feedback',
   'Both anti-skid and EMERG BRAKE provide the same protection'
 ),
 JSON_OBJECT('correct_index', 1),
 'EMERG BRAKE has NO differential braking and NO anti-skid.',
 'hard', 230),
(@quiz_practice, 'TRUE or FALSE — Park brake set + engine power applied causes the T/O warning horn to sound.',
 'true_false',
 JSON_ARRAY('True','False'),
 JSON_OBJECT('correct_index', 0),
 'TRUE. T/O warning horn protects against a takeoff with the brake on.',
 'medium', 240),
(@quiz_practice, 'TRUE or FALSE — Continuous hydraulic pressure when the gear is down-and-locked is what holds the gear down.',
 'true_false',
 JSON_ARRAY('True','False'),
 JSON_OBJECT('correct_index', 1),
 'FALSE. Continuous hyd does act on the gear, but PRIMARY DOWNLOCK is by mechanical OVERCENTER LOCKS — not hydraulic pressure.',
 'hard', 250);

INSERT INTO quizzes (system_id, title, description, quiz_type, time_limit_mins, pass_score, is_published)
VALUES (@system_id,
 'Landing Gear — Type Rating Mock',
 'Ten-question mock at type-rating oral standard. Twelve-minute timer, pass score 80%.',
 'exam', 12, 80, 1);

SET @quiz_exam := LAST_INSERT_ID();

INSERT INTO quiz_questions (quiz_id, question_text, question_type, options, correct_answer, explanation, difficulty, sort_order) VALUES
(@quiz_exam, 'Hydraulic allocation: gear vs brakes.',
 'mcq',
 JSON_ARRAY(
   'Both on No.1',
   'Gear/steering on No.2; brakes on No.1',
   'Gear on No.1; brakes on No.2',
   'Gear on No.3 standby'
 ),
 JSON_OBJECT('correct_index', 1),
 'No.2 = gear + steering. No.1 = brakes. EMERG BRAKE = No.2/accumulator.',
 'easy', 10),
(@quiz_exam, 'Steering deflection ranges: tiller / pedals / caster.',
 'mcq',
 JSON_ARRAY(
   '70 / 30 / 90',
   '70 / 8 / 120',
   '8 / 17 / 35',
   '50 / 5 / 100'
 ),
 JSON_OBJECT('correct_index', 1),
 'Tiller ±70°, pedals ±8°, caster ±120°. Mnemonic: 70-HAND-8-PEDAL-120-CASTER.',
 'medium', 20),
(@quiz_exam, 'You have an LDG GEAR INOP caution. First action of alternate extension?',
 'mcq',
 JSON_ARRAY(
   'Pull MAIN L/G RELEASE handle',
   'Set LANDING GEAR INHIBIT switch to INHIBIT',
   'Operate hand pump',
   'Open floor door first'
 ),
 JSON_OBJECT('correct_index', 1),
 'INHIBIT first. Then RELEASE door + handle (mains). Then EXTENSION door + handle (nose). Then pump for downlock if needed.',
 'hard', 30),
(@quiz_exam, 'After alternate extension, what is done with the two doors?',
 'mcq',
 JSON_ARRAY('Both closed','Both LEFT FULLY OPEN','Overhead open, floor closed','Floor open, overhead closed'),
 JSON_OBJECT('correct_index', 1),
 'Both fully open. Closing defeats the alt path.',
 'medium', 40),
(@quiz_exam, 'Anti-skid speed thresholds: arm / self-test prevented / brake-delay cancel.',
 'mcq',
 JSON_ARRAY('5 / 10 / 25','10 / 17 / 35','15 / 30 / 50','17 / 25 / 60'),
 JSON_OBJECT('correct_index', 1),
 '10 / 17 / 35. Mnemonic: 10-17-35-BRAKE.',
 'hard', 50),
(@quiz_exam, 'Gear warning tone — only which case may be MUTED?',
 'mcq',
 JSON_ARRAY('Case 1 (flap >8.5°)','Case 2 (both PLA <FLT IDLE +12°)','Case 3 (single-engine failure low speed)','None — never muted'),
 JSON_OBJECT('correct_index', 2),
 'Only case 3. Mnemonic: 3-TONE-GROUPS-MUTE-3.',
 'hard', 60),
(@quiz_exam, 'Park brake — minimum pre-engine-start pressure and accumulator capacity.',
 'mcq',
 JSON_ARRAY(
   '300 PSI / 3 applications',
   '500 PSI / ~6 applications',
   '1000 PSI / ~12 applications',
   'No minimum; unlimited applications'
 ),
 JSON_OBJECT('correct_index', 1),
 '500 PSI; ~6 applications fully charged.',
 'medium', 70),
(@quiz_exam, 'Reverse taxi rule.',
 'mcq',
 JSON_ARRAY(
   'STEERING OFF',
   'STEERING ON, NO tiller or pedal input',
   'Tiller only',
   'Pedals only'
 ),
 JSON_OBJECT('correct_index', 1),
 'STEERING ON, no tiller/pedal. Differential brake + power for direction.',
 'hard', 80),
(@quiz_exam, 'Gear unsafe at 2500 AGL on ILS — NOSE green missing, NOSE red unsafe. First action?',
 'mcq',
 JSON_ARRAY(
   'Continue approach — green and red simultaneous is normal',
   'Climb to 5000+ AGL; ALTERNATE DOWNLOCK VERIFICATION to AFT; verify 3 floor lights; if unconfirmed, alt extension',
   'Land immediately',
   'Pull EMERG BRAKE to PARK'
 ),
 JSON_OBJECT('correct_index', 1),
 'Climb first. Verify via floor lights. Alt extension if not confirmed.',
 'hard', 90),
(@quiz_exam, 'TRUE or FALSE — Continuous hydraulic pressure is the primary downlock mechanism.',
 'true_false',
 JSON_ARRAY('True','False'),
 JSON_OBJECT('correct_index', 1),
 'FALSE. Primary downlock is mechanical OVERCENTER. Hyd is continuous when down + locked but not the lock itself.',
 'hard', 100);

SELECT
    (SELECT COUNT(*) FROM quizzes WHERE system_id = @system_id) AS quizzes_inserted,
    (SELECT COUNT(*) FROM quiz_questions WHERE quiz_id IN (SELECT id FROM quizzes WHERE system_id = @system_id)) AS questions_inserted;
