-- =============================================================================
-- AviatorTutor — Phase 3: ATA 22 Autoflight — quizzes (Practice 25 + Mock 10)
-- =============================================================================

SET @system_id := (SELECT id FROM systems WHERE slug = 'autoflight' LIMIT 1);
SELECT @system_id AS resolved_system_id;

DELETE FROM quizzes WHERE system_id = @system_id;

-- ===== Practice =====
INSERT INTO quizzes (system_id, title, description, quiz_type, time_limit_mins, pass_score, is_published)
VALUES (@system_id, 'Autoflight — Practice',
 'Twenty-five-question practice quiz covering AFCS architecture, engagement conditions, INHIBIT vs FAIL messages, pitch trim logic, roll mistrim, disengagement annunciations, FMA colours, and AFCS failure messages. No time limit.',
 'practice', NULL, 70, 1);
SET @quiz_practice := LAST_INSERT_ID();

INSERT INTO quiz_questions (quiz_id, question_text, question_type, options, correct_answer, explanation, difficulty, sort_order) VALUES
(@quiz_practice, 'How many Flight Guidance Modules (FGMs) does the Q400 AFCS have?',
 'mcq', JSON_ARRAY('One', 'Two', 'Three', 'Four'),
 JSON_OBJECT('correct_index', 1),
 'Two FGMs. FGM1 commands the actuators; FGM2 monitors. Both required for AP/YD; one is enough for the FD.',
 'easy', 10),
(@quiz_practice, 'Which FGM commands the AP and YD actuators?',
 'mcq', JSON_ARRAY('FGM1', 'FGM2', 'Both simultaneously', 'Whichever one was last reset'),
 JSON_OBJECT('correct_index', 0),
 'FGM1 sends the actual commands. FGM2 monitors the commands and the actuator performance.',
 'medium', 20),
(@quiz_practice, 'Engagement of the Yaw Damper is INHIBITED if the aircraft roll attitude exceeds:',
 'mcq', JSON_ARRAY('±20°', '±30°', '±45°', '±60°'),
 JSON_OBJECT('correct_index', 2),
 'YD engagement inhibited at ±45° roll. AP engagement inhibited at ±45° roll OR ±20° pitch.',
 'medium', 30),
(@quiz_practice, 'Engagement of the Autopilot is INHIBITED if the aircraft pitch attitude exceeds:',
 'mcq', JSON_ARRAY('±10°', '±20°', '±30°', '±45°'),
 JSON_OBJECT('correct_index', 1),
 'AP requires pitch within ±20°. (Roll within ±45°.) YD has no pitch limit, only ±45° roll.',
 'medium', 40),
(@quiz_practice, 'Engaging the AP automatically engages the YD. What happens to the AP if the YD disengages?',
 'mcq', JSON_ARRAY(
   'AP keeps flying without YD',
   'AP also disengages',
   'AP enters TCS mode',
   'AP reverts to FD only'),
 JSON_OBJECT('correct_index', 1),
 'YD failure or disengagement always disengages the AP.',
 'medium', 50),
(@quiz_practice, 'You press AP and the PFD shows AP INHIBIT. The cause is:',
 'mcq', JSON_ARRAY(
   'An internal AFCS failure',
   'An external condition (AHRS/ADC/attitude/GA/TCS/etc.)',
   'A pitch-trim failure',
   'A YD ground test in progress'),
 JSON_OBJECT('correct_index', 1),
 'AP INHIBIT = external cause outside the AFCS. AP FAIL = internal AFCS failure.',
 'medium', 60),
(@quiz_practice, 'You press AP and the PFD shows AP FAIL. The cause is:',
 'mcq', JSON_ARRAY(
   'External condition (e.g., AHRS disagree)',
   'An internal AFCS failure',
   'Routine engagement; no action required',
   'TCS active'),
 JSON_OBJECT('correct_index', 1),
 'AP FAIL = internal AFCS failure. If YD also affected, message is AP/YD FAIL.',
 'medium', 70),
(@quiz_practice, 'AP Pitch Trim runs at HIGH speed below what KCAS, and LOW speed above?',
 'mcq', JSON_ARRAY('150 KCAS', '180 KCAS', '200 KCAS', '220 KCAS'),
 JSON_OBJECT('correct_index', 1),
 '180 KCAS is the threshold. HIGH speed below 180 (handles flap/gear/accel/decel); LOW above 180 (precision in cruise).',
 'medium', 80),
(@quiz_practice, 'Manual pitch trim from the wheel switch with AP engaged causes:',
 'mcq', JSON_ARRAY(
   'AP to absorb the input via auto-trim',
   'AP to DISENGAGE (manual override)',
   'A trim-fail message',
   'No effect; ignored'),
 JSON_OBJECT('correct_index', 1),
 'Manual trim with AP engaged is treated as a deliberate override. AP disengages.',
 'medium', 90),
(@quiz_practice, 'When AP is engaged and TCS is held active, the AP Pitch Trim function is:',
 'mcq', JSON_ARRAY(
   'Active and trimming continuously',
   'Disabled (the pilot is overriding the AP)',
   'In LOW speed mode regardless of CAS',
   'In HIGH speed mode regardless of CAS'),
 JSON_OBJECT('correct_index', 1),
 'AP Pitch Trim is disabled while TCS is active. The pilot is overriding the AP — auto-trim stays out of the way.',
 'hard', 100),
(@quiz_practice, 'A MISTRIM [TRIM L WING DN] amber message appears on the PFD with AP engaged. Does the AP automatically disengage?',
 'mcq', JSON_ARRAY('Yes — Mistrim disengages the AP',
   'No — Mistrim is annunciation only; AP stays engaged',
   'Only if the message persists for 30 seconds',
   'Only if simultaneously a pitch mistrim is also present'),
 JSON_OBJECT('correct_index', 1),
 'Mistrim is annunciation only. AP does NOT auto-disengage. There is no automatic roll trim — crew must disengage cleanly, trim manually, re-engage.',
 'medium', 110),
(@quiz_practice, 'Does the Q400 have an AUTOMATIC ROLL TRIM function?',
 'mcq', JSON_ARRAY('Yes — equivalent to auto pitch trim',
   'No — there is no automatic roll trim function',
   'Only when below 180 KCAS',
   'Only above 25,000 ft'),
 JSON_OBJECT('correct_index', 1),
 'No automatic roll trim. Mistrim is annunciation only. Pilot trims manually after disengagement.',
 'medium', 120),
(@quiz_practice, 'AUTOMATIC AP disengagement annunciation includes:',
 'mcq', JSON_ARRAY(
   'PFD message only, 5 seconds steady',
   'Glareshield flashing red + flashing PFD message + continuous aural tone',
   'Glareshield steady red only',
   'Aural tone only'),
 JSON_OBJECT('correct_index', 1),
 'AUTO disengagement triggers all three: red glareshield AP DISENG flashing + flashing amber PFD + continuous aural until acknowledged.',
 'medium', 130),
(@quiz_practice, 'MANUAL AP disengagement annunciation includes:',
 'mcq', JSON_ARRAY(
   'Glareshield flashing + PFD flashing + aural tone',
   'Steady amber AP DISENGAGED on PFD for 5 seconds; no flashing; no aural',
   'Continuous aural tone until acknowledged',
   'Both glareshield AP DISENG segments lit'),
 JSON_OBJECT('correct_index', 1),
 'MANUAL disengagement is PFD-only, 5 seconds steady. No glareshield flashing, no aural.',
 'medium', 140),
(@quiz_practice, 'How does the crew acknowledge an AUTO disengagement?',
 'mcq', JSON_ARRAY(
   'Press the AP button on the FGCP',
   'Press AP DIS on either control wheel',
   'Cycle the YD switch',
   'Wait for the warnings to time out'),
 JSON_OBJECT('correct_index', 1),
 'Press AP DIS on either control wheel. Stops the flashing and silences the aural. PFD then steady for 5 seconds.',
 'easy', 150),
(@quiz_practice, 'Both AP DISENG glareshield segments lit means:',
 'mcq', JSON_ARRAY(
   'Both pilots have selected AP DIS',
   'AP disengagement caused by failure of one of the two FGM power sources',
   'A pitch-trim failure',
   'Routine indication after every flight'),
 JSON_OBJECT('correct_index', 1),
 'Both segments lit = FGM power-source failure caused the disengagement.',
 'hard', 160),
(@quiz_practice, 'On the FMA, WHITE indicates:',
 'mcq', JSON_ARRAY('Active mode', 'Armed mode', 'Failed mode', 'Disabled mode'),
 JSON_OBJECT('correct_index', 1),
 'WHITE = armed (waiting for capture). GREEN = active (currently flying).',
 'easy', 170),
(@quiz_practice, 'On the FMA, GREEN indicates:',
 'mcq', JSON_ARRAY('Armed mode', 'Active mode', 'Standby mode', 'Test mode'),
 JSON_OBJECT('correct_index', 1),
 'GREEN = active mode. WHITE = armed.',
 'easy', 180),
(@quiz_practice, 'In Go Around mode, the lateral target submode is:',
 'mcq', JSON_ARRAY('Heading Hold', 'Wings Level', 'Track Hold', 'NAV Tracking'),
 JSON_OBJECT('correct_index', 1),
 'Go Around lateral submode is Wings Level — zero roll target. All other armed modes are disarmed when GA active.',
 'medium', 190),
(@quiz_practice, 'TRUE or FALSE — The Q400 AP can be engaged on the ground for taxi tests.',
 'true_false', JSON_ARRAY('True','False'),
 JSON_OBJECT('correct_index', 1),
 'FALSE. "Aeroplane is airborne" is one of the engagement conditions. AP cannot engage on the ground.',
 'easy', 200),
(@quiz_practice, 'TRUE or FALSE — Both AHRS sources are required for AP engagement.',
 'true_false', JSON_ARRAY('True','False'),
 JSON_OBJECT('correct_index', 0),
 'TRUE. AHRS 1 and AHRS 2 must both be valid AND must not disagree. Same applies for ADC 1/2.',
 'medium', 210),
(@quiz_practice, 'TRUE or FALSE — A single FGM is sufficient to operate the Flight Director (FD).',
 'true_false', JSON_ARRAY('True','False'),
 JSON_OBJECT('correct_index', 0),
 'TRUE. Each FGM can independently process FD commands. AP/YD requires both.',
 'medium', 220),
(@quiz_practice, 'TRUE or FALSE — AP engagement is inhibited while AP disengagement warnings are still active.',
 'true_false', JSON_ARRAY('True','False'),
 JSON_OBJECT('correct_index', 0),
 'TRUE. Reset the warnings using AP DIS on either control wheel before attempting re-engagement.',
 'medium', 230),
(@quiz_practice, 'TRUE or FALSE — The Q400 has automatic roll trim equivalent to its automatic pitch trim.',
 'true_false', JSON_ARRAY('True','False'),
 JSON_OBJECT('correct_index', 1),
 'FALSE. There is NO automatic roll trim. Mistrim is annunciation only.',
 'medium', 240),
(@quiz_practice, 'TRUE or FALSE — Manual AP disengagement triggers the continuous aural tone.',
 'true_false', JSON_ARRAY('True','False'),
 JSON_OBJECT('correct_index', 1),
 'FALSE. Manual disengagement is PFD-only, 5 seconds steady. The aural tone is for AUTOMATIC disengagement only.',
 'medium', 250);

-- ===== Type Rating Mock =====
INSERT INTO quizzes (system_id, title, description, quiz_type, time_limit_mins, pass_score, is_published)
VALUES (@system_id, 'Autoflight — Type Rating Mock',
 'Ten-question mock at type-rating oral standard. Twelve-minute timer, pass score 80%.',
 'exam', 12, 80, 1);
SET @quiz_exam := LAST_INSERT_ID();

INSERT INTO quiz_questions (quiz_id, question_text, question_type, options, correct_answer, explanation, difficulty, sort_order) VALUES
(@quiz_exam, 'Describe Q400 AFCS architecture in one sentence.',
 'mcq', JSON_ARRAY(
   'One FGM driving two APAUs',
   'Two FGMs (FGM1 commands, FGM2 monitors) driving two APAUs',
   'Three FGMs in voting majority',
   'Two FGMs each with its own APAU and no monitoring'),
 JSON_OBJECT('correct_index', 1),
 'Two FGMs (one commands, one monitors) driving two APAUs. Mnemonic: FGM-2-FOR-1.',
 'medium', 10),
(@quiz_exam, 'AP engagement attitude limits.',
 'mcq', JSON_ARRAY('Roll ±30°, pitch ±10°', 'Roll ±45°, pitch ±20°', 'Roll ±60°, pitch ±30°', 'No attitude limits'),
 JSON_OBJECT('correct_index', 1),
 'Roll ±45°, pitch ±20°. YD only ±45° roll. Mnemonic: 45/20-INHIBIT.',
 'medium', 20),
(@quiz_exam, 'Difference between AP INHIBIT and AP FAIL.',
 'mcq', JSON_ARRAY(
   'INHIBIT = internal failure; FAIL = external condition',
   'INHIBIT = external condition; FAIL = internal AFCS failure',
   'They are interchangeable terms',
   'INHIBIT = AP only; FAIL = AP+YD'),
 JSON_OBJECT('correct_index', 1),
 'INHIBIT = external (fix the condition); FAIL = internal AFCS failure (run QRH).',
 'medium', 30),
(@quiz_exam, 'Pitch-trim speed schedule and the threshold.',
 'mcq', JSON_ARRAY(
   'HIGH below 150 KCAS, LOW above',
   'HIGH below 180 KCAS, LOW above',
   'LOW below 180 KCAS, HIGH above',
   'Single speed regardless of CAS'),
 JSON_OBJECT('correct_index', 1),
 'HIGH below 180, LOW above. Mnemonic: 180-FAST-LOW.',
 'medium', 40),
(@quiz_exam, 'Roll Mistrim message — what does it require of the crew?',
 'mcq', JSON_ARRAY(
   'Wait for AP to auto-trim',
   'Disengage AP cleanly, trim laterally until message clears, re-engage',
   'Press AP DIS immediately',
   'Apply rudder to centre the ball'),
 JSON_OBJECT('correct_index', 1),
 'Mistrim is annunciation only. Disengage cleanly with hands on the wheel, trim until clear, re-engage.',
 'hard', 50),
(@quiz_exam, 'Cockpit indications for AUTOMATIC AP disengagement.',
 'mcq', JSON_ARRAY(
   'PFD message only',
   'Glareshield flashing red + flashing amber PFD + continuous aural tone',
   'Steady glareshield red only',
   'Aural tone only'),
 JSON_OBJECT('correct_index', 1),
 'AUTO = three indications: flashing glareshield, flashing PFD, continuous aural. Manual = PFD steady amber 5 sec only.',
 'medium', 60),
(@quiz_exam, 'How does the crew acknowledge an automatic AP disengagement?',
 'mcq', JSON_ARRAY(
   'Press the AP button on FGCP',
   'Press AP DIS on either control wheel',
   'Cycle the FGCP power',
   'Wait 30 seconds'),
 JSON_OBJECT('correct_index', 1),
 'Press AP DIS on either wheel. Stops flashing, silences aural. AP can be re-engaged after warnings reset.',
 'easy', 70),
(@quiz_exam, 'FMA colour convention on the Q400.',
 'mcq', JSON_ARRAY(
   'White = active, Green = armed',
   'White = armed, Green = active',
   'Yellow = armed, White = active',
   'Green = armed, Cyan = active'),
 JSON_OBJECT('correct_index', 1),
 'White = armed (waiting for capture); Green = active (currently flying). Mnemonic: WHITE-ARM-GREEN-LIVE.',
 'easy', 80),
(@quiz_exam, 'Go Around mode lateral submode and what disarmed modes look like.',
 'mcq', JSON_ARRAY(
   'NAV tracking; armed modes preserved',
   'Wings Level; all armed modes disarmed',
   'Heading Hold; vertical armed modes preserved',
   'Bank Hold; lateral armed modes preserved'),
 JSON_OBJECT('correct_index', 1),
 'GA lateral submode is Wings Level. All other armed modes are disarmed when GA active.',
 'medium', 90),
(@quiz_exam, 'Both AP DISENG glareshield segments are lit (not flashing). What does this indicate?',
 'mcq', JSON_ARRAY(
   'Routine indication after engine start',
   'AP disengagement caused by failure of one of the two FGM power sources',
   'A pitch-trim failure',
   'Both pilots have manually disengaged'),
 JSON_OBJECT('correct_index', 1),
 'Both segments lit = FGM power-source failure was the cause of the AP disengagement.',
 'hard', 100);

SELECT
    (SELECT COUNT(*) FROM quizzes WHERE system_id = @system_id) AS quizzes_inserted,
    (SELECT COUNT(*) FROM quiz_questions WHERE quiz_id IN
        (SELECT id FROM quizzes WHERE system_id = @system_id)) AS questions_inserted;
